### ISSUE TITLE
can not import the nodes

### ISSUE THREAD

**Issue by BoosterCore** [Gourieff/comfyui-reactor-node#1]
I got this error:
`Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1604, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\faceswap.py", line 3, in <module>
    from modules import scripts, shared, images, scripts_postprocessing
ImportError: cannot import name 'images' from 'modules' (unknown location)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'images' from 'modules' (unknown location)`

**Comment by MattRM2** [comment]
Hi,

Mostly the same error for me too. I use ComfyUI portable.

`Traceback (most recent call last):
  File "E:\00_ComfyUI\ComfyUI\nodes.py", line 1596, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\faceswap.py", line 3, in <module>
    from modules import scripts, shared, images, scripts_postprocessing
ImportError: cannot import name 'images' from 'modules' (unknown location)

Cannot import E:\00_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'images' from 'modules' (unknown location)`

Matt

**Comment by Gourieff** [comment]
I think I know what's the reason, will take a look tomorrow

**Comment by Gourieff** [comment]
Fixed, it should work now

**Comment by BoosterCore** [comment]
> Fixed, it should work now

Thanks,it works!
