### ISSUE TITLE
Never been able to get Reactor working

### ISSUE THREAD

**Issue by Skettalee** [Gourieff/comfyui-reactor-node#106]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Any time i try to get reactor working, i first in comfyui manager go to custom nodes and find reactor and install it. I have also tried getting it from insider custom nodes folder git clone command and after i get the plugin, I then click the install.bat file. And it gives me errors there:

Installing...
Status: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\Cython\Build\__init__.py", line 1, in <module>
          from .Dependencies import cythonize
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\Cython\Build\Dependencies.py", line 3, in <module>
          import cython
      ModuleNotFoundError: No module named 'cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Ok
Done!

so im sure cause of this error, it then fails to load in comfyui, this code : 
G:\Sd\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-18 01:06:24.178021

Prestartup times for custom nodes:
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32457 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 SUPER : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints G:\sd\webui\models/Stable-diffusion
Adding extra search path configs G:\sd\webui\models/Stable-diffusion
Adding extra search path vae G:\sd\webui\models/VAE
Adding extra search path loras G:\sd\webui\models/Lora
Adding extra search path loras G:\sd\webui\models/LyCORIS
Adding extra search path upscale_models G:\sd\webui\models/ESRGAN
Adding extra search path upscale_models G:\sd\webui\models/RealESRGAN
Adding extra search path upscale_models G:\sd\webui\models/SwinIR
Adding extra search path embeddings G:\sd\webui\embeddings
Adding extra search path hypernetworks G:\sd\webui\models/hypernetworks
Adding extra search path controlnet G:\sd\webui\models/ControlNet
### ComfyUI Revision: 1699 [0cf4e869] | Released on '2023-11-17'
Traceback (most recent call last):
  File "G:\Sd\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
Comfyroll Custom Nodes: Loaded
G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
!! Trying to start the node
Total VRAM 8192 MB, total RAM 32457 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 SUPER : cudaMallocAsync
VAE dtype: torch.float32
G:\Sd\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
G:\Sd\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\Sd\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 197 nodes successfully.

        "Every artist was first an amateur." - Ralph Waldo Emerson

Import times for custom nodes:
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\facerestore
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds (IMPORT FAILED): G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.5 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.7 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\facedetailer
   1.1 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

### Steps to reproduce the problem

I simple try installing reactor again. errors in install.bat and obviously then follow through to trying to launch comfyui 

### Sysinfo

computer runs Windows 11 Pro on a Dell Precision 3660, equipped with a 12th Gen Intel Core i7-12700 Processor, 32GB of RAM, and an LG HDR 4K & LG Ultra HD Monitors, driven by a 4GB NVIDIA GeForce RTX 2080 SUPER Graphics Card. I use various storage options, such as SSDs and HDDs, along with a Presonus Studio 1810c Audio Interface. My peripherals include Logitech MX Master 3 Mouse, MX Keys keyboard, Elgato Stream Deck MK2, Logic Brio Webcam, Ableton Push 2 MIDI Controller, Wacom Intuos Pro Small tablet, Elgato Cam Link 4K, Akai MPK Mini Controller, M-Audio Keystation 88 keys, an iPhone 14 Pro, 2011 MacBook Pro, and an 8th gen iPad.

### Relevant console log

```Shell
TRYING INSTALL.BAT:

Installing...
Status: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\Cython\Build\__init__.py", line 1, in <module>
          from .Dependencies import cythonize
        File "G:\Sd\ComfyUI\python_embeded\Lib\site-packages\Cython\Build\Dependencies.py", line 3, in <module>
          import cython
      ModuleNotFoundError: No module named 'cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Ok
Done!
Press any key to continue . . .

TRYING COMFYUI Launch:
G:\Sd\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-18 01:06:24.178021

Prestartup times for custom nodes:
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32457 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 SUPER : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints G:\sd\webui\models/Stable-diffusion
Adding extra search path configs G:\sd\webui\models/Stable-diffusion
Adding extra search path vae G:\sd\webui\models/VAE
Adding extra search path loras G:\sd\webui\models/Lora
Adding extra search path loras G:\sd\webui\models/LyCORIS
Adding extra search path upscale_models G:\sd\webui\models/ESRGAN
Adding extra search path upscale_models G:\sd\webui\models/RealESRGAN
Adding extra search path upscale_models G:\sd\webui\models/SwinIR
Adding extra search path embeddings G:\sd\webui\embeddings
Adding extra search path hypernetworks G:\sd\webui\models/hypernetworks
Adding extra search path controlnet G:\sd\webui\models/ControlNet
### Loading: ComfyUI-Impact-Pack (V4.30.8)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Inspire-Pack (V0.45)
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1699 [0cf4e869] | Released on '2023-11-17'
Traceback (most recent call last):
  File "G:\Sd\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
Comfyroll Custom Nodes: Loaded
G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
!! Trying to start the node
Total VRAM 8192 MB, total RAM 32457 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 SUPER : cudaMallocAsync
VAE dtype: torch.float32
G:\Sd\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
G:\Sd\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\Sd\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 197 nodes successfully.

        "Every artist was first an amateur." - Ralph Waldo Emerson


Import times for custom nodes:
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\facerestore
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds (IMPORT FAILED): G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.5 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.7 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\facedetailer
   1.1 seconds: G:\Sd\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\Sd\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
```

### Additional information

Nothing more i can think of.

**Comment by Skettalee** [comment]
Actually sorry nevermind, i finally got the instatll.bat to go through i think i was installing 3.10 insightface and using python 3.11 with comfyui. Thanks anyway though.

Other people still having this problem download and put [insightface-0.7.3-cp311-cp311-win_amd64.whl ](https://raw.githubusercontent.com/Gourieff/Assets/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl)
in your comfyui root folder the one that has python_embeded and your run_nvidia_gpu.bat file 

then cmd from that directory, you can just put cmd in address bar in explorer and it pops up. then type:

`python_embeded\python.exe -m pip install -U pip`
then
`python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl`
And then go run the install.bat inside the reactor custom node folder and should be good from there
