### ISSUE TITLE
!!! Exception during processing !!! AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by whmc76** [Gourieff/comfyui-reactor-node#11]
14:03:24 - ReActor Node - STATUS - Working: source face index [0], target face index [0]
14:03:24 - ReActor Node - STATUS - Swap in 0
set det-size: (640, 640)
set det-size: (640, 640)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 38, in execute
    script.process(
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\faceswap.py", line 94, in process
    result = swap_face(
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\swapper.py", line 201, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by whmc76** [comment]
13:44:24 - ReActor Node - STATUS - Running v0.1.1b in ComfyUI

**Comment by whmc76** [comment]
i found a 110M model file in it, after change to right version, and re install it could work
