### ISSUE TITLE
Error occurred when executing ReActorFaceSwap:

### ISSUE THREAD

**Issue by XTRMsavage** [Gourieff/comfyui-reactor-node#115]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I have followed the instructions as stated but still getting the error. I have even put the models in the folder. How do I resolve this?

<img width="401" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/ec5c0923-21b1-4c00-a451-9d93fc94dd78">

<img width="298" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/14bed188-79c7-4d1c-8c93-165b041e3c6e">

### Steps to reproduce the problem

Your workflow
<img width="1220" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/0fac0670-764e-4c1d-a5a5-628a2d108c29">

### Sysinfo

Chrome, RTX4090 24GB, Windows 10, Python 10

### Relevant console log

```Shell
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 117, in execute
script.process(
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 96, in process
result = swap_face(
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 195, in swap_face
source_faces = analyze_faces(source_img)
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 114, in analyze_faces
face_analyser = copy.deepcopy(getAnalysisModel())
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 69, in getAnalysisModel
ANALYSIS_MODEL = insightface.app.FaceAnalysis(
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 59, in patched_faceanalysis_init
assert 'detection' in self.models
```

**Comment by Gourieff** [comment]
Do you have buffalo_l models inside the folder `ComfyUI\models\insightface\models\buffalo_l`?

**Comment by kevinpardo** [comment]
+1 I have the same issue here.
It seems to to work better if I lower the input image resolution.

**Comment by kevinpardo** [comment]
I don't have the file ComfyUI\models\insightface\models\buffalo_l

Where can I download it ? It's probably the cause of the issue for me... I had to do a manual install for the node already

**Comment by kevinpardo** [comment]
Don't know if it helps, but here is the log from the console : 

```
Loading 1 new model
[ReActor] 23:01:09 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 23:01:09 - STATUS - Analyzing Source Image...
2023-12-08 23:01:10.5019460 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-12-08 23:01:55.3832607 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-12-08 23:01:57.0245228 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-12-08 23:01:57.1184853 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-12-08 23:01:57.7989074 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

[ReActor] 23:01:59 - STATUS - Analyzing Target Image...
[ReActor] 23:02:00 - STATUS - Trying to halve 'det_size' parameter
2023-12-08 23:02:02.2182753 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 117, in execute
    script.process(
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 96, in process
    result = swap_face(
             ^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 244, in swap_face
    face_swapper = getFaceSwapModel(model_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 80, in getFaceSwapModel
    FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 34, in patched_get_model
    return INSwapper(model_file=self.onnx_file, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 77, in patched_inswapper_init
    model = onnx.load(self.model_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\__init__.py", line 169, in load_model
    s = _load_bytes(f)
        ^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\__init__.py", line 74, in _load_bytes
    content = readable.read()
              ^^^^^^^^^^^^^^^
MemoryError
```

**Comment by kevinpardo** [comment]
Ok I've found a solution : i just realised I was loading my base model twice by mistake... Hence the memory issue.
Now that I only load it once, everything is smooth.

**Comment by odinrinoa** [comment]
我也有同样的问题出现，目前已经够解决了，分析结果主要有以下两个原因：
1、ComfyUI\models\insightface\models\buffalo_l  文件不全删除文件夹重新下载。
2、对换脸象只有一个人的时候，（surce_faces_index  input_faces_index）都要设置为“0”
最后感谢“Gourieff ”提供的线索，没有你我将无法找到具体错误环节。

I found through observation that the program was skipped when it was downloaded to 70%.

FETCH DATA from: D:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[AnimateDiffEvo] - WARNING - This warning can be ignored, you should not be using the deprecated AnimateDiff Combine node anyway. If you are, use Video Combine from ComfyUI-VideoHelperSuite instead. ffmpeg could not be found. Outputs that require it have been disabled
got prompt
download_path: D:\Ai\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l
Downloading D:\Ai\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
 70%|██████████████████████████████████████████████████▋                     | 198419/281857 [02:07<00:53, 1552.19KB/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by odinrinoa** [comment]
I also have the same problem that has been resolved so far. The analysis results mainly have the following two reasons:

1. ComfyUI \ models \ insightface \ models \ buffalo_ Delete the folder and download again if the files are incomplete.
I found through observation that the program was skipped when it was downloaded to 70%.
2. When there is only one person in the face swapping elephant, (surce_faced_index input_faced_index) must be set to "0"

Finally, thank you to Gourieff for providing the clues. Without you, I would not be able to find the specific error link.

**Comment by PMLOVEAXURE** [comment]
> i have the same issue, but Solved by deleting ComfyUI\models\insightface
> 
> The reason for doing that is because when I executed it for the first time, I found that buffalo_l.zip was being downloaded in the background, but the download was interrupted, and the program continued to execute faceswap.

Thank you for sharing your experience, my problem has been solved, thank you!
