### ISSUE TITLE
(IMPORT FAILED) with error message: cannot import name 'mesh_core_cython'

### ISSUE THREAD

**Issue by corvo4791** [Gourieff/comfyui-reactor-node#134]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Every time I run "run_nvidia_gpu.bat" I get this error:
**ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)**

I've installed and updated everything very carefully. I also put the models in the "facerestore_models" folder.

I'm using ComfyUI Portable

### Steps to reproduce the problem

Your workflow
I just run ComfyUI Portable

### Sysinfo

Windows 10
Chrome Version 120.0.6099.71 64bit
NVidia 4070ti 12GB

### Relevant console log

```Shell
Traceback (most recent call last):
  File "C:\code\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
  File "C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>    from . import app
  File "C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)

Cannot import C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
```

**Comment by corvo4791** [comment]
EDIT: I solved deleting the 2 folders in "ComfyUI_windows_portable\python_embeded\Lib\site-packages" :
-insightface
-insightface-0.7.3.dist-info

and I did again the TRABLESHOOTING procedure at point I: (Manual installation of insightface)

**Comment by corvo4791** [comment]
I Close this hoping my solution can work for other people.
