### ISSUE TITLE
In comfyUI not portable (IMPORT FAILED): ComfyUI\custom_nodes\comfyui-reactor-node

### ISSUE THREAD

**Issue by ffdown** [Gourieff/comfyui-reactor-node#14]
21:37:43 - ReActor Node - STATUS - Running v0.1.1b in ComfyUI
Traceback (most recent call last):
  File "E:\AI\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from utils import batch_tensor_to_pil, batched_pil_to_tensor, tensor_to_pil
ImportError: cannot import name 'batch_tensor_to_pil' from 'utils' (E:\AI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\utils.py)

Cannot import E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'batch_tensor_to_pil' from 'utils' (E:\AI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\utils.py)

**Comment by Gourieff** [comment]
I will fix it soon, it's a conflict of the same filenames of different nodes

**Comment by Gourieff** [comment]
Fixed!

**Comment by ffdown** [comment]
Very operative! Thanks!
