### ISSUE TITLE
Blip Analyze (was-node-suite-comfyui) and Old BLIP method no longer works.

### ISSUE THREAD

**Issue by murphylanga** [Gourieff/comfyui-reactor-node#145]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After installation as below:

V. "ModuleNotFoundError: No module named 'basicsr'" or "subprocess-exited-with-error" during future-0.18.3 installation

described.

Blip Analyze (was-node-suite-comfyui) and Old BLIP method no longer works.

### Steps to reproduce the problem

Your workflow
[Murphylanga_SDXL_outpaint_inpaint_3.0.json](https://github.com/Gourieff/comfyui-reactor-node/files/13694198/Murphylanga_SDXL_outpaint_inpaint_3.0.json)

### Sysinfo

Betriebsystemname	Microsoft Windows 11 Home
Prozessor	12th Gen Intel(R) Core(TM) i7-12700H, 2300 MHz, 14 Kern(e), 20 logische(r) Prozessor(en)
System-SKU	LENOVO_MT_82RF_BU_idea_FM_Legion 5 Pro 16IAH7H
Installierter physischer Speicher (RAM)	32,0 GB
Adaptertyp	NVIDIA GeForce RTX 3070 Laptop GPU, NVIDIA-kompatibel
CUDA 12.3

### Relevant console log

```Shell
Input image resolution: 1024x1344
Selected SDXL resolution: 896x1152
WAS Node Suite Error: `transformers==4.26.1` is required for BLIP models. Please run the `D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\requirements.txt` through ComfyUI's ptyhon executable.
reshape position embedding from 900 to 576
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 10895, in blip_caption_image
    answer = model(tensor, question, train=False, inference='generate')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_module.py", line 336, in forward
    outputs = self.text_decoder.generate(input_ids=bos_ids,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 1797, in generate
    return self.beam_search(
           ^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 3181, in beam_search
    outputs = self(
              ^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 886, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 781, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 445, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
                              ^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 277, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0
```

### Additional information

I had the problem yesterday. Resetting my python_embeded folder and reinstalling Reactor Node and was-node-suite temporarily solved the problem. Unfortunately I have the same problem again today after an update of ComfyUI....  I solved it temporarily by resetting the python_embeded folder and reinstalling it.

Some of my workflows that use your node are published at:
https://civitai.com/models/218177/murphy-langa-collection-of-my-best-workflows?modelVersionId=263768

**Comment by murphylanga** [comment]
Good morning,
Is something being overwritten in the python_embeded directory that doesn't need to be overwritten?

If I run the following in custom_nodes/was-node-suite-comfiui with the install.bat to set:

cmake
fairscale>=0.4.4
git+https://github.com/WASasquatch/img2texture.git
git+https://github.com/WASasquatch/cstr
gitpython
imageio
joblib
matplotlib
numba
numpy>=1.18.5, <1.25.0
opencv-python-headless[ffmpeg]<=4.7.0.72
pilgram
git+https://github.com/WASasquatch/ffmpy.git
rembg
scikit-image==0.20.0
scikit-learn
scipy
timm>=0.4.12
tqdm
transformers==4.26.1

BLIP and comfyui-reactor-node work together without any problems.
I think it's about the transformers==4.26.1

I hope this hint helps
Best regards, Murphy
