### ISSUE TITLE
After installation insightface , other nodes break down

### ISSUE THREAD

**Issue by Seryogerr** [Gourieff/comfyui-reactor-node#176]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Holly, It seems to me that this is for a long time,sry.
I'll start with the fact that after the installation, Reactor node didnt work
<img width="346" alt="2024-01-10_03-52-50" src="https://github.com/Gourieff/comfyui-reactor-node/assets/147452692/2b784feb-664c-4996-a032-d1b8a7d22cd3">
First of all, I went to look for a solution on github, and I tried to install a insightface manually
But after installing ,other nodes have stopped working
![2024-01-10_03-58-21](https://github.com/Gourieff/comfyui-reactor-node/assets/147452692/0530c11b-d649-4324-991a-28a38db9df20)
And also the working part of the Reactor turned red
![2024-01-10_04-28-12](https://github.com/Gourieff/comfyui-reactor-node/assets/147452692/57f2e4f8-41d3-40cd-a88e-8b07df879dd9)

I have already tried a multiple times to check over issues,install,update ,delete everything and so on and even reinstall ComfyUI but unsuccessfully

Thank you for your attention, I hope we will succeed

### Steps to reproduce the problem

For the first try i have Windows Python 3.10.6 and 3.11.6 on portable ComfyUI,I broke all the nodes with insightface and try reinstall,fix and etc all nodes but unsuccessfully.
After, i reinstall ComfyUI and install 3.11.6 python for Windows(of course with deleting 3.10.6),but it still didn't work after installation, (install.bat didnt help to(peace of bug in console log)
I try other fix in Troubleshooting before manually installing the insightface again, specifically IV and V fix, but unsuccessfully
Then I installed the insightface again and everything broke the same way.

I also want to note that the installer did not work and gave an error, but unfortunately I only have a part of a bug, it disappears after manual installation. bug report in console log. If necessary, I can reinstall ComfyUI and get the same log but full.

### Sysinfo

Python 3.11.6
Visual Studio Community 17.8.4
update pip to 23.3.2
RTX 3070 M
Windows 11

### Relevant console log

```Shell
I also want to note that the installer did not work and gave an error, but unfortunately I only have a part of a bug, it disappears after manual installation. If necessary, I can reinstall ComfyUI and get the same log but full

 × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [18 lines of output] Traceback (most recent call last): File "C:\Godno\Ai\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module> main() File "C:\Godno\Ai\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_ho




ComfyUI Broken nodes LOG

C:\Godno\Ai\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-01-10 04:45:45.754063
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Godno\Ai\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Godno\Ai\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 16022 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints C:\Godno\Ai\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Godno\Ai\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Godno\Ai\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Godno\Ai\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Godno\Ai\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Godno\Ai\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Godno\Ai\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Godno\Ai\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Godno\Ai\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Godno\Ai\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Godno\Ai\stable-diffusion-webui\extensions\sd-webui-controlnet\models
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['C:\\Godno\\Ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models']
### Loading: ComfyUI-Manager (V1.25.3)
### ComfyUI Revision: 1890 [6a7bc35d] | Released on '2024-01-09'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'cv2'
Traceback (most recent call last):
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 15, in <module>
    from .load_video_nodes import LoadVideoUpload, LoadVideoPath
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2'
Traceback (most recent call last):
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'cv2'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FizzleDorf Custom Nodes: Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Failed!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Total VRAM 8192 MB, total RAM 16022 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'cv2'

[rgthree] Loaded 22 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

WAS Node Suite Error: OpenCV Python module still cannot be imported. There is a system conflict.
WAS Node Suite: Finished. Loaded 203 nodes successfully.

        "The only person you should try to be better than is the person you were yesterday." - Unknown


Import times for custom nodes:
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds (IMPORT FAILED): C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds (IMPORT FAILED): C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.3 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.3 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   3.0 seconds: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Godno\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
```

### Additional information

I don't know what it matters, but here's a screenshot after manual installation
![photo_2024-01-10_03-57-33](https://github.com/Gourieff/comfyui-reactor-node/assets/147452692/e81aac67-ee1d-496c-9ad5-df21e12e3a95)

Maybe I got confused in some kind of sequence, but believe me, I tried the scientific finger method

**Comment by Seryogerr** [comment]
I found another screenshot of the installation insightface
![photo_2024-01-10_02-42-15](https://github.com/Gourieff/comfyui-reactor-node/assets/147452692/376e069c-a451-4b66-9e6d-135711991941)

**Comment by Gourieff** [comment]
There's smth wrong with OpenCV library
Try to reinstall it as described here: https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node

**Comment by sankoriai** [comment]
I had the same exact issue. 
Firstly, only Reactor not working in my nodes. So i manually installed insight using:
. (For Windows users) If you still cannot build Insightface for some reasons or just don't want to install Visual Studio or VS C++ Build Tools - do the following:

Then when i rebooted, same as Seryogger, all other nodes stopped working. 
So i reinstalled openCV as instructed above.
Now im stuck with this

![comfyuipause](https://github.com/Gourieff/comfyui-reactor-node/assets/115972426/8765c987-9f7b-4fe4-b93d-1ede4c5e9acd)

any help is appreciated
