### ISSUE TITLE
facerestore and facerestore_cf IMPORT FAILED after Installing reactor-node

### ISSUE THREAD

**Issue by 5ft4** [Gourieff/comfyui-reactor-node#18]
Hello.

After Installing reactor-node, facerestore_cf import fails. This occurs using the portable comfy UI Install, and the auto1111 extension comfy ui Install. 
facerestore works until reactor is installed. This also occurs when using facerestore from civitAI

Traceback (most recent call last):
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 6, in <module>
    import cv2
  File "C:\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

`Cannot import C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'`

Import times for custom nodes:
   `0.0 seconds (IMPORT FAILED): C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf`
   `0.3 seconds: C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager`
   `0.7 seconds: C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node`
   
  I notice that you showcase a screenshot of it working, just want to know if this is a recent Issue or a me Issue.
   
  I'm also not a programmer or anything, so I'm a bit stupid. 
   
  Thanks,

**Comment by 5ft4** [comment]
I installed the ComfyUI-Faceswap, and for whatever reason now facerestore_cf Imports.
Import times for custom nodes:
   0.3 seconds (IMPORT FAILED): C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap
   0.3 seconds: C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.9 seconds: C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node`

 Tested and it is working.
