### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by bihailantian655** [Gourieff/comfyui-reactor-node#180]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

numpy.core._exceptions._ArrayMemoryError: Unable to allocate 11.3 GiB for an array with shape (480, 768, 1368, 3) and data type float64

### Steps to reproduce the problem

![hxm_00002](https://github.com/Gourieff/comfyui-reactor-node/assets/35267721/55fa04b2-ecb4-4218-85e7-a4ea903c4353)
 r

when   swap  

r
![{0D524246-724B-46ae-A706-00A4CF3B6C3C}](https://github.com/Gourieff/comfyui-reactor-node/assets/35267721/3bc65a5c-1262-4e08-80c8-7d81f74a8c56)

### Sysinfo

win11  rtx2080

### Relevant console log

```Shell
[ReActor] 00:41:15 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 00:41:15 - STATUS - Analyzing Target Image...
[ReActor] 00:41:17 - STATUS - Swapping...
[ReActor] 00:41:17 - STATUS - --Done!--
[ReActor] 00:41:27 - STATUS - Restoring with GFPGANv1.4.pth
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 169, in execute
    out_images = np.ndarray(shape=image_np.shape)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 11.3 GiB for an array with shape (480, 768, 1368, 3) and data type float64
```

**Comment by bihailantian655** [comment]
![{4D5247C0-D233-4ec9-B13E-1D7F2C66D56A}](https://github.com/Gourieff/comfyui-reactor-node/assets/35267721/108df87f-0364-46f6-a0ad-7f8eae008c0b)

**Comment by Soondols** [comment]
I just got the same issue! Did you fix it?

**Comment by Gourieff** [comment]
You should increase Virtual Memory in your OS

- Win+R
- Type `SystemPropertiesAdvanced`
- Under Performance, click Settings
- Select the Advanced tab
- Select Change...
- Uncheck Automatically managing paging file size for all drives
- Then select Custom size and fill in the appropriate size (e.g. 32768)
- Press Set - then OK - then exit from the Virtual Memory, Performance Options, and System Properties Dialog
- Reboot your system

I have 64Gb of RAM and 16384Mb of Virtual Memory and never faced this error while processing any videos

**Comment by Gourieff** [comment]
You guys can try [Evolve](https://github.com/Gourieff/comfyui-reactor-node/tree/evolve) branch to check whether this issue is fixed or not

**Comment by DonBaronFactory** [comment]
The whole script has such a bad memory management, loads too much into RAM instead of using the performance of e.g. SSD storage or even the proper use of GPU. 

I gave up with reactor and wrote our own script. With a 4060 / 16GB and 16GB Ram, we run 4 simultaneous swapping threads, each at 2.5 Frames per second (with restoration and masking) and have a 85% utilization of the GPU  and 40% CPU. Besides that there is no limitation for durations of videos anymore because of no RAM issues ...

Time is of essence here, reactor is simply much too slow

**Comment by Gourieff** [comment]
> The whole script has such a bad memory management, loads too much into RAM instead of using the performance of e.g. SSD storage or even the proper use of GPU.
> 
> I gave up with reactor and wrote our own script. With a 4060 / 16GB and 16GB Ram, we run 4 simultaneous swapping threads, each at 2.5 Frames per second (with restoration and masking) and have a 85% utilization of the GPU and 40% CPU. Besides that there is no limitation for durations of videos anymore because of no RAM issues ...
> 
> Time is of essence here, reactor is simply much too slow

You can make a PR and improve ReActor instead of complaining, it's an opensource non-commercial app that is still in development stage. Me and the other guys (to whom I am very grateful) develops ReActor in our free time

**Comment by richadlee** [comment]
> The whole script has such a bad memory management, loads too much into RAM instead of using the performance of e.g. SSD storage or even the proper use of GPU.
> 
> I gave up with reactor and wrote our own script. With a 4060 / 16GB and 16GB Ram, we run 4 simultaneous swapping threads, each at 2.5 Frames per second (with restoration and masking) and have a 85% utilization of the GPU and 40% CPU. Besides that there is no limitation for durations of videos anymore because of no RAM issues ...
> 
> Time is of essence here, reactor is simply much too slow

Same issue, can you share your script?
