### ISSUE TITLE
can't install node correctly

### ISSUE THREAD

**Issue by gouroupi** [Gourieff/comfyui-reactor-node#183]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Cannot import /root/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: attempted relative import beyond top-level package

### Steps to reproduce the problem

1.via comfyui manager install
2.restart the comfyui

### Sysinfo

** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

### Relevant console log

```Shell
root@dsw-302190-5c798c8f89-m6lz6:~/ComfyUI# python main.py
** ComfyUI startup time: 2024-01-12 16:55:24.804558
** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
** Python executable: /opt/conda/bin/python
** Log path: /root/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 16160 MB, total RAM 32165 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla V100-SXM2-16GB : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /root/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
/root/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
### Loading: ComfyUI-Manager (V1.25.4)
### ComfyUI Revision: 1895 [977eda19] | Released on '2024-01-11'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
### [START] ComfyUI AlekPet Nodes ###
Node -> TranslateNode [Loading]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Node -> PainterNode [Loading]
Node -> ExtrasNode [Loading]
Node -> PoseNode [Loading]
Node -> ArgosTranslateNode [Loading]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
### [END] ComfyUI AlekPet Nodes ###
Total VRAM 16160 MB, total RAM 32165 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla V100-SXM2-16GB : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/root/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 8, in <module>
    from modules.processing import StableDiffusionProcessingImg2Img
  File "/opt/conda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/opt/conda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/modules/ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
ImportError: attempted relative import beyond top-level package

Cannot import /root/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: attempted relative import beyond top-level package
```

**Comment by Gourieff** [comment]
> from modules.processing import StableDiffusionProcessingImg2Img
  File "/opt/conda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/opt/conda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/modules/ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
ImportError: attempted relative import beyond top-level package

ReActor has nothing to do with this
Frankly, I have no clue why it throws you this error with a very simple import procedure
But the error is about "MultiScaleDeformableAttention" module
Try to use venv instead of conda
