### ISSUE TITLE
Please install the correct version of CUDA and cuDNN

### ISSUE THREAD

**Issue by CoreyCorza** [Gourieff/comfyui-reactor-node#190]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I don't know how to install the correct version of CUDA and cuDNN :(

### Steps to reproduce the problem

Pretend like you don't know how to install the correct version of CUDA and cuDNN. 
The problem becomes evident
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/40785775/35d2053a-633b-4e75-8662-01db5047a3d5)

### Sysinfo

Windows 11, Nvidia 3060ti, OperaGX

### Relevant console log

```Shell
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 112, in execute
    script.process(
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 96, in process
    result = swap_face(
             ^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 195, in swap_face
    source_faces = analyze_faces(source_img)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 114, in analyze_faces
    face_analyser = copy.deepcopy(getAnalysisModel())
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 69, in getAnalysisModel
    ANALYSIS_MODEL = insightface.app.FaceAnalysis(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 48, in patched_faceanalysis_init
    model = model_zoo.get_model(onnx_file, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 21, in patched_get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\cjand\Downloads\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. 

Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

**Comment by CoreyCorza** [comment]
My GPU is supported btw. I use reactor in automatic1111 regularly

**Comment by Gourieff** [comment]
The issue is that the onnxruntime-gpu library requires CUDA 11.8, just downgrade CUDA version or install the appropriate build of ComfyUI with CU11.8
Or you can try the following if you skilled enough https://github.com/Gourieff/comfyui-reactor-node/issues/119#issuecomment-1841350868

**Comment by CoreyCorza** [comment]
Ok I managed to get it all working on a fresh comfyui cu11.8 version (I might suggest updating the installation instructions, literally every step failed) 

Now how do I install the restore models?
It downloaded all the models it needs except these
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/40785775/76cbb485-0485-4caa-bd9d-88b949ca07e4)

**Comment by Gourieff** [comment]
> Ok I managed to get it all working on a fresh comfyui cu11.8 version (I might suggest updating the installation instructions, pretty much every step failed)
> 
> Now how do I install the restore models? It downloaded all the models it needs except these

https://github.com/Gourieff/comfyui-reactor-node#installation

Step 5:

![изображение](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/b12e14d8-debf-4b40-831a-66384ce21854)

**Comment by XTRMsavage** [comment]
> Ok I managed to get it all working on a fresh comfyui cu11.8 version (I might suggest updating the installation instructions, pretty much every step failed)
> 
> Now how do I install the restore models? It downloaded all the models it needs except these ![image](https://private-user-images.githubusercontent.com/40785775/298218384-76cbb485-0485-4caa-bd9d-88b949ca07e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODA4NDgsIm5iZiI6MTczMTY4MDU0OCwicGF0aCI6Ii80MDc4NTc3NS8yOTgyMTgzODQtNzZjYmI0ODUtMDQ4NS00Y2FhLWJkOWQtODhiOTQ5Y2EwN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE0MjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjg2ZWIxZmE4NWExNDQ1MGYwYjk1OGQyYjU3MzBjYmMwYzIzZWFlZGFmMDVmNjcwNDhmNzA4NTE5YTM5NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JH1niwtq-U89L1SkcUGL0vOUwI1R-fl1HODsAskdZ60)

Can you please tell me how you fixed it? which method you used? Thanks
