### ISSUE TITLE
Conflict with comfy_controlnet_preprocessors

### ISSUE THREAD

**Issue by BoosterCore** [Gourieff/comfyui-reactor-node#2]
Same as ComfyUI_Roop, Conflict with comfy_controlnet_preprocessors, would u please fix this issue? 🥲

**Comment by BoosterCore** [comment]
`Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1604, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\pose.py", line 5, in <module>
    from .. import mp_pose_hand
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\mp_pose_hand\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 14, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 14, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 20, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe.framework.formats.annotation.rasterization_pb2', _globals)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 82, in BuildMessage
    create_dict[name] = BuildMessage(nested_msg)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: A Message class can only inherit from Message`

**Comment by Gourieff** [comment]
Hm... I think it's coz of dependency conflict 
What's the version of protobuf is inside the "lib\site-packages\" directory?

**Comment by BoosterCore** [comment]
> Hm... I think it's coz of dependency conflict What's the version of protobuf is inside the "lib\site-packages" directory?

It is protobuf-3.20.3

**Comment by Gourieff** [comment]
I tried to install ReActor first and then Controlnet_preprocessors - both extensions works without errors, tested separately and together

**Comment by penmoid** [comment]
Same issue for me. If I use numpy 1.23.x, reactor will load but controlnet preprocessors will not, whereas if I use numpy 1.24+, controlnet preprocessors will load but reactor will not.

**Comment by BoosterCore** [comment]
> I tried to install ReActor node first and then Controlnet_preprocessors - both extensions works without errors, tested separately and together

I tried this, still not work

**Comment by BoosterCore** [comment]
https://github.com/Fannovel16/comfy_controlnet_preprocessors/issues/86

**Comment by Gourieff** [comment]
Could you please guys provide a workflow you use to repeat this error?

**Comment by Gourieff** [comment]
ReActor doesn't work when numpy is 1.24.x or higher only because of "AttributeError: module 'numpy' has no attribute 'warnings'" error
It's fixed with this commit https://github.com/Gourieff/comfyui-reactor-node/commit/1fd08a8ec3e61bffe8a1411edff2baa7a6ec1a0f
But it didn't solve the Issue
ReActor runs fine now with the latest Numpy, but Controlnet_preprocessor fails with errors... 🤷‍♂️
I don't know guys what exactly the reason, but inside the A1111 both extensions work together pretty fine, with no errors

**Comment by BoosterCore** [comment]
Finally, This bug is fixed in Fannovel16's new project: https://github.com/Fannovel16/comfyui_controlnet_aux
