### ISSUE TITLE
Installation permission issues

### ISSUE THREAD

**Issue by mayjack0312** [Gourieff/comfyui-reactor-node#204]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blackboxprotobuf 1.0.1 requires protobuf==3.10.0, but you have protobuf 4.25.2 which is incompatible.

### Steps to reproduce the problem

After installing other plug-ins, an inexplicable problem occurred.

### Sysinfo

win10
chrome
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/102800660/f2738bf5-3050-407c-8e1a-d5ef4bf9ff9e)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/102800660/75d90a28-667c-4838-b392-4499c01b2e37)

### Relevant console log

```Shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blackboxprotobuf 1.0.1 requires protobuf==3.10.0, but you have protobuf 4.25.2 which is incompatible.

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\augmentations\__init__.py", line 2, in <module>
    from .blur.functional import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
    from .functional import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\augmentations\blur\functional.py", line 8, in <module>
    from albumentations.augmentations.functional import convolve
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\augmentations\functional.py", line 11, in <module>
    from albumentations.augmentations.utils import (
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\augmentations\utils.py", line 41, in <module>
    np.uint8: cv2.CV_8U,
              ^^^^^^^^^
AttributeError: module 'cv2' has no attribute 'CV_8U'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: module 'cv2' has no attribute 'CV_8U'
### Loading: Workspace Manager (V1.0.0)
```

**Comment by Gourieff** [comment]
You should reinstall albumentations to 1.3.1 and protobuf to 3.20.3

**Comment by selway** [comment]
check the opencv version，if  you versionis >=4.10x or <=4.7， it will like this，uninstall it and install 4.9x  it will be fixed.
