### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by darkpixel** [Gourieff/comfyui-reactor-node#206]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The latest commits appear to break things when your target image doesn't have enough faces.

If you have more faces in your source image than you do in your input image, you get an ```IndexError: list index out of range```.

### Relevant console log

```
Shell
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:18<00:00,  1.22s/it]
[ReActor] 14:51:07 - STATUS - Working: source face index [0, 1, 2, 3, 4, 5], target face index [1, 5, 4, 2, 0, 3]
[ReActor] 14:51:07 - STATUS - Swap in 0
[ReActor] 14:51:07 - STATUS - Analyzing Source Image...
[ReActor] 14:51:10 - STATUS - Analyzing Target Image...
[ReActor] 14:51:15 - STATUS - Target Face 1: Detected Gender -F-
[ReActor] 14:51:15 - STATUS - OK - Detected Gender matches Condition
[ReActor] 14:51:15 - STATUS - Swapping...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/ai/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/ai/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/ai/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 234, in execute
    script.process(
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 81, in process
    result = swap_face(
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 255, in swap_face
    target_face, wrong_gender = get_face_single(target_img, target_faces, face_index=face_num, gender_target=gender_target)
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 134, in get_face_single
    return get_face_gender(face,face_index,gender_target,"Target")
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 96, in get_face_gender
    face_gender = gender[face_index]
IndexError: list index out of range
```

**Comment by darkpixel** [comment]
Turning off gender detection bypasses this issue.

**Comment by KurtCocain** [comment]
> Turning off gender detection bypasses this issue.
I understand that, but... What If I have a short video or multiple photos of a male and a female  swapping positions a couple times during? (it's not a hypothetical that's why i'm here). That's what I thought it was for, varying genders on specific indices

**Comment by darkpixel** [comment]
It looks like you just have to know the number of genders before you to the swap.
It's a huge pain when you're generating something along the lines of "A group of friends at the movie theater" and AI randomly generates various genders.
