### ISSUE TITLE
Trouble after install comfy_mtb node

### ISSUE THREAD

**Issue by ffdown** [Gourieff/comfyui-reactor-node#21]
```
Traceback (most recent call last):
  File "E:\AI\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 3, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_swapper import swap_face
  File "E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\onnx\__init__.py", line 13, in <module>
    from onnx.external_data_helper import (
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\onnx\external_data_helper.py", line 11, in <module>    from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\onnx\onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (E:\Anaconda3\lib\site-packages\google\protobuf\internal\__init__.py)

Cannot import E:\AI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'builder' from 'google.protobuf.internal' (E:\Anaconda3\lib\site-packages\google\protobuf\internal\__init__.py)
E:\Anaconda3\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```

after uninstall comfy_mtb trouble not fixed

**Comment by Gourieff** [comment]
Smth wrong with Protobuf library

Try the following:
- Go to the `E:\AI\python_embeded\Lib\site-packages` directory and see if there are any folders with names start from "~" (for example "~rotobuf"), delete them, go to the `google` folder there and also delete any folders as "~rotobuf"
- From the `E:\AI\` directory open Console (cmd)
- Run `python_embeded\python.exe -m pip uninstall protobuf` and then `python_embeded\python.exe -m pip install protobuf==3.20.3`

**Comment by ffdown** [comment]
And one more just fix my problem and i happy!!!
