### ISSUE TITLE
[SOLVED] urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

### ISSUE THREAD

**Issue by OneStepAndTwoSteps** [Gourieff/comfyui-reactor-node#216]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Hello, I am a beginner, and I encountered a problem while importing a workflow. Based on the name, I suspect it might be related to the reactor, so I would like to ask you about what could be causing this issue. My current system is Ubuntu, and the environment is Python 3.9. Could you provide me with some advice?

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42194566/4419d79d-eda4-45e7-863f-62b915057431)

this is my import workflow: https://github.com/Dimgul/ComfyUI-Workflows/blob/main/house_of_dim_faceswap_ldsr_workflow.json

### Steps to reproduce the problem

Your workflow

### Sysinfo

platform：Ubuntu，
gpu：a800
python：3.9

### Relevant console log

```Shell
[ERROR] An error occurred while retrieving information for the 'ReActorFaceSwap' node.
Traceback (most recent call last):
  File "/path/to/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/path/to/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/path/to/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/path/to/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/path/to/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/path/to/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/path/to/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 92, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 72, in get_model_names
    models = get_models()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 66, in get_restorers
    download(model_url, model_path, model_name)
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 99, in download
    request = urllib.request.urlopen(url)
  File "/path/to/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/path/to/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/path/to/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/path/to/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/path/to/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/path/to/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
[ERROR] An error occurred while retrieving information for the 'ReActorRestoreFace' node.
Traceback (most recent call last):
  File "/path/to/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/path/to/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/path/to/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/path/to/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/path/to/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/path/to/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/path/to/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 331, in INPUT_TYPES
    "model": (get_model_names(get_restorers),),
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 72, in get_model_names
    models = get_models()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 66, in get_restorers
    download(model_url, model_path, model_name)
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 99, in download
    request = urllib.request.urlopen(url)
  File "/path/to/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/path/to/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/path/to/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/path/to/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/path/to/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/path/to/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
FETCH DATA from: /home/qjsys/kai/draw/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'ReActorFaceSwap' node.
Traceback (most recent call last):
  File "/path/to/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/path/to/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/path/to/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/path/to/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/path/to/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/path/to/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/path/to/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 92, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 72, in get_model_names
    models = get_models()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 66, in get_restorers
    download(model_url, model_path, model_name)
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 99, in download
    request = urllib.request.urlopen(url)
  File "/path/to/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/path/to/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/path/to/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/path/to/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/path/to/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/path/to/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
[ERROR] An error occurred while retrieving information for the 'ReActorRestoreFace' node.
Traceback (most recent call last):
  File "/path/to/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/path/to/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/path/to/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/path/to/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/path/to/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/path/to/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/path/to/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/path/to/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/home/qjsys/kai/draw/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 331, in INPUT_TYPES
    "model": (get_model_names(get_restorers),),
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 72, in get_model_names
    models = get_models()
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 66, in get_restorers
    download(model_url, model_path, model_name)
  File "/home/qjsys/kai/draw/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 99, in download
    request = urllib.request.urlopen(url)
  File "/path/to/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/path/to/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/path/to/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/path/to/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/path/to/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/path/to/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

**Comment by Gourieff** [comment]
Hello, you should use Python 3.10 or 3.11 for ComfyUI

**Comment by XMUykyz** [comment]
**Python 3.11 also report the error**

** ComfyUI startup time: 2024-03-21 14:05:45.463488
** Platform: Linux
** Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
** Python executable: /data/shenhx/code/SD/ComfyUI/myenv/bin/python
** Log path: /data/shenhx/code/SD/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24253 MB, total RAM 128437 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints /data/shenhx/code/SD/sd-webui-aki-v4.7/models/Stable-diffusion
Adding extra search path configs /data/shenhx/code/SD/sd-webui-aki-v4.7/models/Stable-diffusion
Adding extra search path vae /data/shenhx/code/SD/sd-webui-aki-v4.7/models/VAE
Adding extra search path loras /data/shenhx/code/SD/sd-webui-aki-v4.7/models/Lora
Adding extra search path loras /data/shenhx/code/SD/sd-webui-aki-v4.7/models/LyCORIS
Adding extra search path upscale_models /data/shenhx/code/SD/sd-webui-aki-v4.7/models/ESRGAN
Adding extra search path upscale_models /data/shenhx/code/SD/sd-webui-aki-v4.7/models/RealESRGAN
Adding extra search path upscale_models /data/shenhx/code/SD/sd-webui-aki-v4.7/models/SwinIR
Adding extra search path embeddings /data/shenhx/code/SD/sd-webui-aki-v4.7/embeddings
Adding extra search path hypernetworks /data/shenhx/code/SD/sd-webui-aki-v4.7/models/hypernetworks
Adding extra search path controlnet /data/shenhx/code/SD/sd-webui-aki-v4.7/models/ControlNet
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
[ReActor] - STATUS - Running v0.4.1-b12 in ComfyUI
Torch version: 2.2.1+cu121
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
### Loading: ComfyUI-Manager (V2.10.2)
### ComfyUI Revision: 2074 [d14bdb18] | Released on '2024-03-19'

Import times for custom nodes:
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.1 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.7 seconds: /data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: /data/shenhx/code/SD/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'ReActorFaceSwap' node.
Traceback (most recent call last):
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/data/shenhx/software/anaconda3/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/shenhx/code/SD/ComfyUI/server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 98, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 78, in get_model_names
    models = get_models()
             ^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 72, in get_restorers
    download(model_url, model_path, model_name)
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 99, in download
    request = urllib.request.urlopen(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

[ERROR] An error occurred while retrieving information for the 'ReActorRestoreFace' node.
Traceback (most recent call last):
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/data/shenhx/software/anaconda3/lib/python3.11/http/client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/data/shenhx/software/anaconda3/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/shenhx/code/SD/ComfyUI/server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 346, in INPUT_TYPES
    "model": (get_model_names(get_restorers),),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 78, in get_model_names
    models = get_models()
             ^^^^^^^^^^^^
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 72, in get_restorers
    download(model_url, model_path, model_name)
  File "/data/shenhx/code/SD/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 99, in download
    request = urllib.request.urlopen(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/shenhx/software/anaconda3/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by Jesean** [comment]
+1 I have the same issue here.

**Comment by LiuNingqian** [comment]
> +1 I have the same issue here. my server has no access to the network. I tried to download the [codeformer.pth](https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth) and [GFPGANv1.4.pth](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth). Then put them in `ComfyUI/models/facerestore_models/`, finally it works.

Do what you did, and it works~

**Comment by herbert7777** [comment]
> +1 I have the same issue here. my server has no access to the network. I tried to download the [codeformer.pth](https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth) and [GFPGANv1.4.pth](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth). Then put them in `ComfyUI/models/facerestore_models/`, finally it works.

Great
it works

**Comment by Linlintwl** [comment]
Great
it works!!!

**Comment by jaxinoman** [comment]
> +1 I have the same issue here. my server has no access to the network. I tried to download the [codeformer.pth](https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth) and [GFPGANv1.4.pth](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth). Then put them in `ComfyUI/models/facerestore_models/`, finally it works.

Thx! Finally it works!
