### ISSUE TITLE
No module named 'scripts.reactor_version'

### ISSUE THREAD

**Issue by GoDJr** [Gourieff/comfyui-reactor-node#217]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After the recent update of torch, i keep getting the following error and cant import reactor node: 

No module named 'scripts.reactor_version'

### Steps to reproduce the problem

On boot

### Sysinfo

Ubuntu
Python 3.10
Pytorch nightly Rocm 5.7
Using comfy via Conda 

### Relevant console log

```Shell
### Loading: ComfyUI-Inspire-Pack (V0.63)
Traceback (most recent call last):
  File "/home/sagar/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sagar/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/sagar/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 14, in <module>
    import scripts.reactor_version
ModuleNotFoundError: No module named 'scripts.reactor_version'

Cannot import /home/sagar/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'scripts.reactor_version'
```

### Additional information
I have tried uninstalling and reinstalling using terminal git clone and comfy manager, i also uninstalled requirements and reinstalled them with no resolution. im also getting a similar error with roop ModuleNotFoundError: No module named 'scripts.faceswap'

_No response_

**Comment by Tralen** [comment]
I'm getting a similar crash:

```
Traceback (most recent call last):
  File "/home/tralen/Gerador/AI/SD/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tralen/Gerador/AI/SD/ComfyUI/custom_nodes/comfyui-reactor-node-main/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/tralen/Gerador/AI/SD/ComfyUI/custom_nodes/comfyui-reactor-node-main/nodes.py", line 14, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
ModuleNotFoundError: No module named 'scripts.reactor_faceswap'

Cannot import /home/tralen/Gerador/AI/SD/ComfyUI/custom_nodes/comfyui-reactor-node-main module for custom nodes: No module named 'scripts.reactor_faceswap'
/home/tralen/.local/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)
```

**Comment by GoDJr** [comment]
I fixed mine by deleting roop I'm not sure why it was breaking it.

**Comment by Tralen** [comment]
No roop on my end, but I was able to fix it by doing a cleanup and full reinstallation.
