### ISSUE TITLE
Just refuses to load - despite insightface working just fine with faceid

### ISSUE THREAD

**Issue by offmybach** [Gourieff/comfyui-reactor-node#224]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I have attempted to install/uninstall via manager, git link, direct install via cmd and not once has it worked. My insightface is correctly installed - correct version for 3.11 and placed in proper directories.  My errors all point to the arch registry.

### Steps to reproduce the problem

Your workflow
just won't load. red in every one

### Sysinfo

win11, portable version, all updated

### Relevant console log

```Shell
D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[ComfyUI-Manager] Logging failed: [WinError 32] The process cannot access the file because it is being used by another process: 'comfyui.log' -> 'comfyui.prev.log'
** ComfyUI startup time: 2024-02-14 14:16:41.146766
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py']

## Execute install/(de)activation script for 'D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
 Requirement already satisfied: onnxruntime-gpu in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (1.16.3)
 Requirement already satisfied: coloredlogs in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (15.0.1)
 Requirement already satisfied: flatbuffers in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (23.5.26)
 Requirement already satisfied: numpy>=1.24.2 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.26.4)
 Requirement already satisfied: packaging in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (23.2)
 Requirement already satisfied: protobuf in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (4.23.4)
 Requirement already satisfied: sympy in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.12)
 Requirement already satisfied: humanfriendly>=9.1 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
 Requirement already satisfied: pyreadline3 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.4.1)
 CUDA 12.1
 Ok
Install: pip packages for 'D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
Install: install script for 'D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
 Requirement already satisfied: onnxruntime-gpu in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (1.16.3)
 Requirement already satisfied: coloredlogs in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (15.0.1)
 Requirement already satisfied: flatbuffers in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (23.5.26)
 Requirement already satisfied: numpy>=1.24.2 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.26.4)
 Requirement already satisfied: packaging in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (23.2)
 Requirement already satisfied: protobuf in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (4.23.4)
 Requirement already satisfied: sympy in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.12)
 Requirement already satisfied: humanfriendly>=9.1 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
 Requirement already satisfied: pyreadline3 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.4.1)
 CUDA 12.1
 Ok

[ComfyUI-Manager] Startup script completed.
#######################################################################

[Maras IT] Initialization

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MarasIT-Nodes
  14.1 seconds: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints C:\Users\mdmen\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Users\mdmen\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Users\mdmen\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Users\mdmen\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Users\mdmen\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Users\mdmen\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Users\mdmen\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Users\mdmen\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Users\mdmen\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Users\mdmen\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Users\mdmen\stable-diffusion-webui\models/ControlNet
2024-02-14 14:16:59.348409: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Bellamiss custom_nodes\\__init__.py'

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Bellamiss custom_nodes module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\Bellamiss custom_nodes\\__init__.py'
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Adding D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded efficiency nodes from D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Advanced-ControlNet\\control/control.py\\__init__.py'
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### ComfyUI-Background-Replacement: Requirements already installed.
### ComfyUI-Background-Replacement: Initializing captioner...
### ComfyUI-Background-Replacement: Initializing upscaler...
### ComfyUI-Background-Replacement: Initializing segmenter...
### ComfyUI-Background-Replacement: Initializing depth estimator...
[Crystools INFO] Crystools version: 1.11.0
[Crystools INFO] CPU: 12th Gen Intel(R) Core(TM) i7-12700H - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3070 Ti Laptop GPU
[Crystools INFO] NVIDIA Driver: 551.23
Comfy-Easy-Use (v1.0.5): Loaded
### ComfyUI-FaceSwap: Check dependencies
### ComfyUI-FaceSwap: Check basic models
### Loading: ComfyUI-Impact-Pack (V4.76.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.64)
Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.2+cu121
Package diffusers is already installed.
### Loading: ComfyUI-Manager (V2.7.2)
### ComfyUI Revision: 1973 [7f89cb48] | Released on '2024-02-14'
[Maras IT] Loaded
packaging is already installed.
cpuinfo is already installed.
git is already installed.
moviepy is already installed.
cv2 is already installed.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
skbuild is already installed.
typing is already installed.
diskcache is already installed.
llama_cpp is already installed.

OpenPose Editor: Loaded
ComfyUI-Portrait-Maker : ### : Check dependencies
ComfyUI-Portrait-Maker : D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\requirements.txt
ComfyUI-Portrait-Maker : aliyun-python-sdk-core-v3==2.13.10

ComfyUI-Portrait-Maker : opencv-python

ComfyUI-Portrait-Maker : tensorflow-cpu

ComfyUI-Portrait-Maker : tensorflow

ComfyUI-Portrait-Maker : onnx

ComfyUI-Portrait-Maker : onnxruntime

ComfyUI-Portrait-Maker : modelscope

ComfyUI-Portrait-Maker : scikit-image

ComfyUI-Portrait-Maker : matplotlib

ComfyUI-Portrait-Maker : insightface

ComfyUI-Portrait-Maker : diffusers==0.18.2

ComfyUI-Portrait-Maker : sentencepiece
2024-02-14 14:17:16,700 - modelscope - INFO - PyTorch version 2.1.2+cu121 Found.
2024-02-14 14:17:16,701 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2024-02-14 14:17:16,701 - modelscope - INFO - Loading ast index from C:\Users\mdmen\.cache\modelscope\ast_indexer
2024-02-14 14:17:16,832 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4964e32649544be02d50cfc7603a6e46 and a total number of 946 components indexed
Start Setting weights
[INFO] PromptControl: Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
[INFO] PromptControl: Weight interpretations available: comfy,A1111,compel,comfy++,down_weight,perp
[INFO] PromptControl: Normalization types available: none,mean,length,length+mean
[SD Prompt Reader] Node version: 1.3.0
[SD Prompt Reader] Core version: 1.3.4.post1
Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
[ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI
Torch version: 2.1.2+cu121
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 30, in <module>
    import scripts.r_archs.codeformer_arch
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\codeformer_arch.py", line 8, in <module>
    from scripts.r_archs.vqgan_arch import *
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\vqgan_arch.py", line 328, in <module>
    @ARCH_REGISTRY.register()
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\utils\registry.py", line 56, in deco
    self._do_register(name, func_or_class, suffix)
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\utils\registry.py", line 42, in _do_register
    assert (name not in self._obj_map), (f"An object named '{name}' was already registered "
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: An object named 'VQAutoEncoder' was already registered in 'arch' registry!

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: An object named 'VQAutoEncoder' was already registered in 'arch' registry!
### Loading: Save img prompt
### Loading: ComfyUI-Workflow-Component (V0.43.3) !! WARN: This is an experimental extension. Extremely unstable. !!
### Loading: Workspace Manager (V1.0.0)

From Bmad Custom Nodes
 Loaded 124 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
  + extension dependent nodes (2)

------------------------------------------------
Comfyroll Custom Nodes v1.55 :  165 Nodes Loaded
------------------------------------------------
Ib Custom Nodes: Loaded
PIL is already installed.
huggingface_hub is already installed.
transformers is already installed.
einops is already installed.
torchvision is already installed.
accelerate is already installed.
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: segment_anything in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
Requirement already satisfied: timm in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.4.12)
Requirement already satisfied: addict in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: yapf in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (0.40.2)
Requirement already satisfied: torch>=1.4 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (2.1.2+cu121)
Requirement already satisfied: torchvision in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.16.2+cu121)
Requirement already satisfied: importlib-metadata>=6.6.0 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (7.0.0)
Requirement already satisfied: platformdirs>=3.5.1 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (4.1.0)
Requirement already satisfied: tomli>=2.0.1 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (2.0.1)
Requirement already satisfied: zipp>=0.5 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from importlib-metadata>=6.6.0->yapf->-r requirements.txt (line 4)) (3.17.0)
Requirement already satisfied: filelock in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.4->timm->-r requirements.txt (line 2)) (3.13.1)
Requirement already satisfied: typing-extensions in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.4->timm->-r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: sympy in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.4->timm->-r requirements.txt (line 2)) (1.12)
Requirement already satisfied: networkx in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.4->timm->-r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: jinja2 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.4->timm->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: fsspec in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.4->timm->-r requirements.txt (line 2)) (2023.10.0)
Requirement already satisfied: numpy in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (1.26.4)
Requirement already satisfied: requests in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.4->timm->-r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision->timm->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision->timm->-r requirements.txt (line 2)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision->timm->-r requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision->timm->-r requirements.txt (line 2)) (2024.2.2)
Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable\new_comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.4->timm->-r requirements.txt (line 2)) (1.3.0)
Using xformers cross attention
[tinyterraNodes] Loaded
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'devices' from 'modules' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'devices' from 'modules' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
```

### Additional information

It seems that ultimatesdupscaler is somehow related here. can't import devices from modules ...reactor node.... Please help. I've spent days on trying to fix this- seriously!

**Comment by offmybach** [comment]
I just uninstalled reactor and now ultimatesdupscaler finally works. there is definitely some conflict between the 2. would be great if you guys could figure out how to get them to play nice together in the sandbox. both are really essential to many workflows.

**Comment by Vee95** [comment]
Yeah honestly, I have been struggling with Reactor Node for 2 weeks trying to include it in my workflow, this issue persists, I use stability matrix, maby its time the devs start comm's with them to keep open updates working... having the facemesh issue, would love some assistance, so we can setup a proper guide for peps experiencing this

**Comment by NiklasGollenstede** [comment]
I also just encountered this issue.

I am not exactly a python expert, but I am pretty sure that when it gets imported, `comfyui-reactor-node` adds itself to the front of pythons (process global) module lookup path.
I am quite sure that that is a borderline hacky thing to do for a (main) application (which knows what other things will load), but is almost guaranteed to break things when a library or plugin/extension-thing does it.
And indeed, there is some code in [`comfyui-reactor-node/__init__.py`](https://github.com/Gourieff/comfyui-reactor-node/blob/ae81f629a4c30804d1d68337eb3f540fa025b5f0/__init__.py#L8-L19) that tries to fix some things that were just broken, but it only covers some imports made by `a1111`, but won't fix any conflicts with other plugins.

There is probably some motivation for that hackery in `/__init__.py`, but I suspect that's what is causing this issue.
Esp. without knowing that reason, I don't know to suggest a more elegant solution, but I'm sure there is one (even with the mess that python's import logic is in general).

**Comment by Gourieff** [comment]
Cannot confirm this issue
Both extensions work fine together
