### ISSUE TITLE
Arch enemy!

### ISSUE THREAD

**Issue by offmybach** [Gourieff/comfyui-reactor-node#228]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

says reactor running in script but won't install because of arch error

### Steps to reproduce the problem

trying to load via stability matrix but have same issue in portable version

### Sysinfo

win 11 stability matrix and portable

### Relevant console log

```Shell
ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI
Torch version: 2.1.0+cu121
Traceback (most recent call last):
  File "D:\Data\Packages\ComfyUI\nodes.py", line 1899, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 30, in <module>
    import scripts.r_archs.codeformer_arch
  File "D:\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\codeformer_arch.py", line 8, in <module>
    from scripts.r_archs.vqgan_arch import *
  File "D:\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\vqgan_arch.py", line 329, in <module>
    class VQAutoEncoder(nn.Module):
  File "D:\Data\Packages\ComfyUI\venv\lib\site-packages\basicsr\utils\registry.py", line 56, in deco
    self._do_register(name, func_or_class, suffix)
  File "D:\Data\Packages\ComfyUI\venv\lib\site-packages\basicsr\utils\registry.py", line 42, in _do_register
    assert (name not in self._obj_map), (f"An object named '{name}' was already registered "
AssertionError: An object named 'VQAutoEncoder' was already registered in 'arch' registry!

Cannot import D:\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: An object named 'VQAutoEncoder' was already registered in 'arch' registry!
```

### Additional information

I've spent all week trying to load this unsuccessfully and I really need to use it

**Comment by offmybach** [comment]
It's Instaswap! They both have have same vqgan_arch.cpython-310.pyc file. I deleted Instaswap and the vqgan_arch.cpython-310.pyc file and POOF- reactor is loaded. Thanks for all your help-not.
