### ISSUE TITLE
I can't build InsightFace

### ISSUE THREAD

**Issue by Jarren5** [Gourieff/comfyui-reactor-node#233]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I can't build insightface in my machine even after installing visual studio,vs c++ Build Tools and the latest versions of python and pip.
I have portable ComfyUI (Stability Matrix) but even after trying in 2 different ways i'm unable to install reactor node for good.

### Steps to reproduce the problem

First way: clicking on install.bat on the reactor node folder.
Second way:CMD python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl on root folder of ComfyUI

### Sysinfo

Windows 11, Firefox,RTX 4070 laptop,no other additional extension added to ComfyUI
<img width="602" alt="1" src="https://github.com/Gourieff/comfyui-reactor-node/assets/161534905/f07d9b15-4c83-49a8-8daf-33238e0b3de4">

<img width="1073" alt="2" src="https://github.com/Gourieff/comfyui-reactor-node/assets/161534905/d56d2088-da1f-46ab-af2e-84dd4ed2c438">

### Relevant console log

```Shell
1) I couldn't find an embedded version of Python, but I did find Python 3.12.2 in your Windows PATH.
Would you like to proceed with the install using that version? (Y/N)
Y
Installing...
python: can't open file 'C:\\Windows\\System32\\install.py': [Errno 2] No such file or directory
Done

2)Processing c:\users\device\pictures\ai\data\packages\comfyui\insightface-0.7.3-cp312-cp312-win_amd64.whl
Collecting numpy (from insightface==0.7.3)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting onnx (from insightface==0.7.3)
  Using cached onnx-1.15.0.tar.gz (12.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Device\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Device\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Device\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Device\AppData\Local\Temp\pip-build-env-7_qo44qw\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Device\AppData\Local\Temp\pip-build-env-7_qo44qw\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Device\AppData\Local\Temp\pip-build-env-7_qo44qw\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
      AssertionError: Could not find cmake in PATH
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by soklamon** [comment]
same problem
what can we do until then?

**Comment by Gourieff** [comment]
Those who don't want to wait till the latest ONNX will be released - can try `pip install onnx-weekly` (dev version with Py312 support) for ComfyUI embedded python

**Comment by soklamon** [comment]
After successfully installing the development version of ONNX (onnx-weekly) I try again the install.bat in comfyui-reactor-node 
all run good until 
...
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... error
  error: subprocess-exited-with-error
...
the full list of info here: 

Installing...
CUDA 12.1
Status: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.26.4)
Requirement already satisfied: onnx in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.15.0)
Requirement already satisfied: tqdm in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (4.66.2)
Requirement already satisfied: requests in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (2.31.0)
Collecting matplotlib (from insightface==0.7.3)
  Using cached matplotlib-3.8.3-cp311-cp311-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: Pillow in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (10.2.0)
Requirement already satisfied: scipy in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.12.0)
Collecting scikit-learn (from insightface==0.7.3)
  Using cached scikit_learn-1.4.1.post1-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting scikit-image (from insightface==0.7.3)
  Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting easydict (from insightface==0.7.3)
  Using cached easydict-1.12-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: cython in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (3.0.8)
Collecting albumentations (from insightface==0.7.3)
  Using cached albumentations-1.4.0-py3-none-any.whl.metadata (35 kB)
Collecting prettytable (from insightface==0.7.3)
  Using cached prettytable-3.10.0-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: PyYAML in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Collecting qudida>=0.0.4 (from albumentations->insightface==0.7.3)
  Using cached qudida-0.0.4-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: opencv-python>=4.9.0 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (4.9.0.80)
Requirement already satisfied: networkx>=2.8 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
Collecting imageio>=2.27 (from scikit-image->insightface==0.7.3)
  Using cached imageio-2.34.0-py3-none-any.whl.metadata (4.9 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->insightface==0.7.3)
  Using cached tifffile-2024.2.12-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: packaging>=21 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (23.2)
Collecting lazy_loader>=0.3 (from scikit-image->insightface==0.7.3)
  Using cached lazy_loader-0.3-py3-none-any.whl.metadata (4.3 kB)
Collecting contourpy>=1.0.1 (from matplotlib->insightface==0.7.3)
  Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib->insightface==0.7.3)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->insightface==0.7.3)
  Using cached fonttools-4.49.0-cp311-cp311-win_amd64.whl.metadata (162 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->insightface==0.7.3)
  Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->insightface==0.7.3)
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib->insightface==0.7.3)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: protobuf>=3.20.2 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from onnx->insightface==0.7.3) (4.25.3)
Collecting wcwidth (from prettytable->insightface==0.7.3)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (2024.2.2)
Collecting joblib>=1.2.0 (from scikit-learn->insightface==0.7.3)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn->insightface==0.7.3)
  Using cached threadpoolctl-3.3.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->insightface==0.7.3)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: typing-extensions in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.10.0)
Requirement already satisfied: opencv-python-headless>=4.0.1 in c:\program files\comfyui_windows_portable\python_embeded\lib\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.9.0.80)
Using cached albumentations-1.4.0-py3-none-any.whl (123 kB)
Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl (24.5 MB)
Using cached easydict-1.12-py3-none-any.whl (6.7 kB)
Using cached matplotlib-3.8.3-cp311-cp311-win_amd64.whl (7.6 MB)
Using cached prettytable-3.10.0-py3-none-any.whl (28 kB)
Using cached scikit_learn-1.4.1.post1-cp311-cp311-win_amd64.whl (10.6 MB)
Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl (187 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.49.0-cp311-cp311-win_amd64.whl (2.2 MB)
Using cached imageio-2.34.0-py3-none-any.whl (313 kB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl (56 kB)
Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Using cached threadpoolctl-3.3.0-py3-none-any.whl (17 kB)
Using cached tifffile-2024.2.12-py3-none-any.whl (224 kB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for insightface (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [225 lines of output]
      WARNING: pandoc not enabled
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\insightface
      copying insightface\__init__.py -> build\lib.win-amd64-cpython-311\insightface
      creating build\lib.win-amd64-cpython-311\insightface\app
      copying insightface\app\common.py -> build\lib.win-amd64-cpython-311\insightface\app
      copying insightface\app\face_analysis.py -> build\lib.win-amd64-cpython-311\insightface\app
      copying insightface\app\mask_renderer.py -> build\lib.win-amd64-cpython-311\insightface\app
      copying insightface\app\__init__.py -> build\lib.win-amd64-cpython-311\insightface\app
      creating build\lib.win-amd64-cpython-311\insightface\commands
      copying insightface\commands\insightface_cli.py -> build\lib.win-amd64-cpython-311\insightface\commands
      copying insightface\commands\model_download.py -> build\lib.win-amd64-cpython-311\insightface\commands
      copying insightface\commands\rec_add_mask_param.py -> build\lib.win-amd64-cpython-311\insightface\commands
      copying insightface\commands\__init__.py -> build\lib.win-amd64-cpython-311\insightface\commands
      creating build\lib.win-amd64-cpython-311\insightface\data
      copying insightface\data\image.py -> build\lib.win-amd64-cpython-311\insightface\data
      copying insightface\data\pickle_object.py -> build\lib.win-amd64-cpython-311\insightface\data
      copying insightface\data\rec_builder.py -> build\lib.win-amd64-cpython-311\insightface\data
      copying insightface\data\__init__.py -> build\lib.win-amd64-cpython-311\insightface\data
      creating build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\arcface_onnx.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\attribute.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\inswapper.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\landmark.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\model_store.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\scrfd.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      copying insightface\model_zoo\__init__.py -> build\lib.win-amd64-cpython-311\insightface\model_zoo
      creating build\lib.win-amd64-cpython-311\insightface\thirdparty
      copying insightface\thirdparty\__init__.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty
      creating build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\constant.py -> build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\download.py -> build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\face_align.py -> build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\filesystem.py -> build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\storage.py -> build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\transform.py -> build\lib.win-amd64-cpython-311\insightface\utils
      copying insightface\utils\__init__.py -> build\lib.win-amd64-cpython-311\insightface\utils
      creating build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d
      copying insightface\thirdparty\face3d\__init__.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d
      creating build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\io.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\light.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\render.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\transform.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\vis.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\__init__.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh
      creating build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\io.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\light.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\render.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\transform.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\vis.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\__init__.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh_numpy
      creating build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\fit.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\load.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\morphabel_model.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\__init__.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\morphable_model
      running egg_info
      writing insightface.egg-info\PKG-INFO
      writing dependency_links to insightface.egg-info\dependency_links.txt
      writing entry points to insightface.egg-info\entry_points.txt
      writing requirements to insightface.egg-info\requires.txt
      writing top-level names to insightface.egg-info\top_level.txt
      reading manifest file 'insightface.egg-info\SOURCES.txt'
      writing manifest file 'insightface.egg-info\SOURCES.txt'
      C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
              already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.data.images' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.data.images' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'insightface.data.images' to be distributed and are
              already explicitly excluding 'insightface.data.images' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.data.objects' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.data.objects' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'insightface.data.objects' to be distributed and are
              already explicitly excluding 'insightface.data.objects' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      creating build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      creating build\lib.win-amd64-cpython-311\insightface\data\images
      copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-311\insightface\data\images
      copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-311\insightface\data\images
      copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-311\insightface\data\images
      copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-311\insightface\data\images
      copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-311\insightface\data\images
      copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-311\insightface\data\images
      creating build\lib.win-amd64-cpython-311\insightface\data\objects
      copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-311\insightface\data\objects
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-311\insightface\thirdparty\face3d\mesh\cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\insightface
      creating build\temp.win-amd64-cpython-311\Release\insightface\thirdparty
      creating build\temp.win-amd64-cpython-311\Release\insightface\thirdparty\face3d
      creating build\temp.win-amd64-cpython-311\Release\insightface\thirdparty\face3d\mesh
      creating build\temp.win-amd64-cpython-311\Release\insightface\thirdparty\face3d\mesh\cython
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython "-IC:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\include" "-IC:\Program Files\ComfyUI_windows_portable\python_embeded\include" "-IC:\Program Files\ComfyUI_windows_portable\python_embeded\Include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-311\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
      mesh_core.cpp
      c1xx: fatal error C1083: Cannot open source file: 'insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
Ok
Done
Press any key to continue . . .

**Comment by gonzalu** [comment]
BTW, installing this custom node break UltimateSDUpscale Node

Uninstalling this node fixes USDU... just FYI.

**Comment by Gourieff** [comment]
@gonzalu what Python do you use?
With Py310 all this nodes work perfectly together
With Py312 unfortunately not and still a lot of bugs with different nodes and dependencies
Py311 has no difference in performance comparing with Py310
The best ComfyUI builds with no issues for different nodes - based on Py310

**Comment by Gourieff** [comment]
@soklamon try to install pre-built Insightface before running install.bat 
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild (choose one according to your Python's version)

**Comment by gonzalu** [comment]
@Gourieff  thank you.  I am using Ng the portable version which came with 3.12 I believe 😭

Thank you
