### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by bertoo87** [Gourieff/comfyui-reactor-node#237]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Can't do a swap, no matter the settings. Example workflow attached with Error Message 
![Screenshot_4](https://github.com/Gourieff/comfyui-reactor-node/assets/50058369/a55608ac-2a81-41eb-a574-767a5f02ff98)

### Steps to reproduce the problem

Workflow:
fresh install of ComfyUI portable, installed the CUDA12 package as per instructions, ran the install.bat, installed insightface for my Python version which i checked via the command (3.11)

### Sysinfo

Win 11, Chrome, RTX3080 10GB, no other Custom Nodes so far, except for the Manager.

### Relevant console log

```Shell
got prompt
[ReActor] 00:00:39 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 00:00:39 - STATUS - Analyzing Source Image...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyNew\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 240, in execute
    script.process(
  File "D:\ComfyNew\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 86, in process
    result = swap_face(
             ^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 195, in swap_face
    source_faces = analyze_faces(source_img)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 114, in analyze_faces
    face_analyser = copy.deepcopy(getAnalysisModel())
                                  ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 69, in getAnalysisModel
    ANALYSIS_MODEL = insightface.app.FaceAnalysis(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyNew\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 59, in patched_faceanalysis_init
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by Amit30swgoh** [comment]
AssertionError 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/2bc3e2e5-abf3-4eeb-a824-409189b2ce22)
also no face model ? 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/c6d2d6b5-196e-41e4-9093-a31d9d6f9e58)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/7412bcb7-a7f8-4bda-9cc3-5d264ef7ba42)

    assert 'detection' in self.models
AssertionError
