### ISSUE TITLE
his ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

### ISSUE THREAD

**Issue by bihailantian655** [Gourieff/comfyui-reactor-node#239]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Error occurred when executing ReActorFaceSwap:

This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

File "H:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "H:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "H:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 240, in execute
script.process(
File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 86, in process
result = swap_face(
File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 195, in swap_face
source_faces = analyze_faces(source_img)
File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 114, in analyze_faces
face_analyser = copy.deepcopy(getAnalysisModel())
File "copy.py", line 172, in deepcopy
File "copy.py", line 271, in _reconstruct
File "copy.py", line 146, in deepcopy
File "copy.py", line 231, in _deepcopy_dict
File "copy.py", line 146, in deepcopy
File "copy.py", line 231, in _deepcopy_dict
File "copy.py", line 172, in deepcopy
File "copy.py", line 271, in _reconstruct
File "copy.py", line 146, in deepcopy
File "copy.py", line 231, in _deepcopy_dict
File "copy.py", line 172, in deepcopy
File "copy.py", line 273, in _reconstruct
File "H:\ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
self.__init__(model_path)
File "H:\ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
super().__init__(model_path, **kwargs)
File "H:\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
raise e
File "H:\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "H:\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
raise ValueError(

### Steps to reproduce the problem

Your workflow
![workflow (2)](https://github.com/Gourieff/comfyui-reactor-node/assets/35267721/2cd9dab9-2556-4c0c-9b1b-59242aac0085)

### Sysinfo

  win11      recently  update  to    pytorch 2.2   cuda12.1+xformer 0.0.24

### Relevant console log

```Shell
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 240, in execute
    script.process(
  File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 86, in process
    result = swap_face(
  File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 195, in swap_face
    source_faces = analyze_faces(source_img)
  File "H:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 114, in analyze_faces
    face_analyser = copy.deepcopy(getAnalysisModel())
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 273, in _reconstruct
  File "H:\ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
    self.__init__(model_path)
  File "H:\ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "H:\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
    raise e
  File "H:\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "H:\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

Prompt executed in 0.16 seconds
```

**Comment by wangfeng35** [comment]
same problem here

**Comment by w84itngetit** [comment]
> same problem here

did you managed to fix it?

**Comment by camoody1** [comment]
Same problem here. Same error message and unable to proceed.
