### ISSUE TITLE
[SOLVED] onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF

### ISSUE THREAD

**Issue by moviejimmy** [Gourieff/comfyui-reactor-node#242]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Error messages during or right after face detection. I have changed a lot of images but the problem remains

### Steps to reproduce the problem

Your workflow

### Sysinfo

Windows, Chrome, Comfyui, RTX4090

### Relevant console log

```Shell
[ReActor] 11:34:13 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 11:34:13 - STATUS - Analyzing Source Image...
[ReActor] 11:34:38 - STATUS - Analyzing Target Image...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_cu121\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 240, in execute
    script.process(
  File "C:\ComfyUI_cu121\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 86, in process
    result = swap_face(
             ^^^^^^^^^^
  File "C:\ComfyUI_cu121\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 245, in swap_face
    face_swapper = getFaceSwapModel(model_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 80, in getFaceSwapModel
    FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_log_patch.py", line 21, in patched_get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_cu121\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\ComfyUI_cu121\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\ComfyUI_cu121\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\ComfyUI_cu121\ComfyUI\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.

Prompt executed in 26.03 seconds
```

**Comment by Gourieff** [comment]
The main model file is corrupted, just download it manually again (https://huggingface.co/datasets/Gourieff/ReActor/blob/main/models/inswapper_128.onnx) to the `ComfyUI\models\insightface` directory replacing existing one

**Comment by iielse** [comment]
The solution you offer is effective. The inswapper_128.onnx file size should be around 541264kb.
