### ISSUE TITLE
Reactor is never installed properly.

### ISSUE THREAD

**Issue by nothingness6** [Gourieff/comfyui-reactor-node#245]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I recently downloaded video to video workflow from CivitAI and gave it a shot, and then faced the error:
![StabilityMatrix-01](https://github.com/LykosAI/StabilityMatrix/assets/105210258/3d3945d5-d31d-4e79-a414-fb61136e960a)

So, I checked Stability Matrix and found two errors:

I re-installed Reactor Node several times, but it's never installed properly. Thus, I asked it to ChatGPT and was trying to figure it out, but no luck.
So, how do I fix it? 

### Steps to reproduce the problem

Your workflow
I installed all requirements again. 

### Sysinfo

i5 12400F 
RTX 3060 12GB
Windows 10 64 bit
Ram 16GB

### Relevant console log

```Shell
Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py)


Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from scripts.reactor_faceswap import (
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_logger import logger
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
```

### Additional information

It runs with Stability Matrix

**Comment by Gourieff** [comment]
> ModuleNotFoundError: No module named 'insightface'

https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27

**Comment by nothingness6** [comment]
> > ModuleNotFoundError: No module named 'insightface'
> 
> https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
> 
> https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27

Hi, thanks for the answer.
I already tried the instruction from the scratch, but it showed me this error:
```
I couldn't find an embedded version of Python, but I did find Python 3.10.11 in your Windows PATH.
Would you like to proceed with the install using that version? (Y/N)
y
Installing...
Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\install.py", line 10, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
Done
Press any key to continue . . .
```
That's why I installed it in ComfyUI, but no luck as well. I also checked the forum to solve the issue, but it didn't help.
I guess ComfyUI updates too frequently and it causes tons of issues.

**Comment by Gourieff** [comment]
> ModuleNotFoundError: No module named 'tqdm'

tqdm lib usually goes from the box - very strange that it's missing
try to install it manually

**Comment by D0xide** [comment]
This issue is problably caused by the differences of fold which embeded python located. You may solve this issue by editing the install.bat file.

**Comment by Spidynino** [comment]
---Asking for Help Please---
Hi is there any chance you can help me out installing ReActor in Comfyui. I have tried everything and it shows up in the Comfyui folder but when I launch Comfyui the ReActor button is no where to be found. I am an noob to all of this and I am working on a film project for school that involves swapping cartoon faces/heads. I could really use some help in fixing this issue! Can you help me please?

**Comment by Gourieff** [comment]
> ---Asking for Help Please--- Hi is there any chance you can help me out installing ReActor in Comfyui. I have tried everything and it shows up in the Comfyui folder but when I launch Comfyui the ReActor button is no where to be found. I am an noob to all of this and I am working on a film project for school that involves swapping cartoon faces/heads. I could really use some help in fixing this issue! Can you help me please?

Just follow the instructions carefully my friend and you will succeed
If not - I can provide you with individual help https://boosty.to/artgourieff/posts/0bc15231-3e89-4ec9-afc9-fe4f595c5643

**Comment by Frimurare** [comment]
Hi @Gourieff 

Did you get it to work? I have the exact same issue and have sat with ChatGPT for a few hours trying to figure it out too. No success here.
