### ISSUE TITLE
[SOLVED] StabilityMatrix | ReActor node doesn't show up. 

### ISSUE THREAD

**Issue by nothingness6** [Gourieff/comfyui-reactor-node#251]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I installed Visual Studio 2022 and installed ReActor through ComfyUI Manager. Although I search it, but it doesn't show up.
![Reactor](https://github.com/Gourieff/comfyui-reactor-node/assets/105210258/6d23a032-8ea6-4d22-890f-668f2a4950d7)
![Reactor-01](https://github.com/Gourieff/comfyui-reactor-node/assets/105210258/4ac71fde-f697-438f-bb74-5dfde73d4bbd)
![Reactor-02](https://github.com/Gourieff/comfyui-reactor-node/assets/105210258/a68c3a6f-0376-463e-b034-edc4874541d5)

### Steps to reproduce the problem

Your workflow
Updated all and Visual Studio 2022 as well. 

### Sysinfo

ComfyUI
Windows 10 64 bit
Edge
RTX 3060 12GB

### Relevant console log

```Shell
** ComfyUI startup time: 2024-03-21 23:51:43.671510
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Scripts\python.exe
** Log path: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 16237 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\StableDiffusion
Adding extra search path vae M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\VAE
Adding extra search path loras M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\Lora
Adding extra search path loras M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\LyCORIS
Adding extra search path upscale_models M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\ESRGAN
Adding extra search path upscale_models M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\RealESRGAN
Adding extra search path upscale_models M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\SwinIR
Adding extra search path embeddings M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\TextualInversion
Adding extra search path hypernetworks M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\Hypernetwork
Adding extra search path controlnet M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\ControlNet
Adding extra search path controlnet M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\T2IAdapter
Adding extra search path clip M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\CLIP
Adding extra search path clip_vision M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\InvokeClipVision
Adding extra search path diffusers M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\Diffusers
Adding extra search path gligen M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\GLIGEN
Adding extra search path vae_approx M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\ApproxVAE
Adding extra search path ipadapter M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\IpAdapter
Adding extra search path ipadapter M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\InvokeIpAdapters15
Adding extra search path ipadapter M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion M:\AI_Tools\StabilityMatrix-win-x64\Data\Models\PromptExpansion
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py)

Cannot import M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved module for custom nodes: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py)
[Crystools INFO] Crystools version: 1.11.0
[Crystools INFO] CPU: 12th Gen Intel(R) Core(TM) i5-12400F - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 551.61
### Loading: ComfyUI-Impact-Pack (V4.83.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
### Loading: ComfyUI-Inspire-Pack (V0.67.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.9)
### ComfyUI Revision: 2072 [40e124c6] | Released on '2024-03-18'
Failed to auto update `Quality of Life Suit` 
QualityOfLifeSuit_Omar92_DIR: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[ReActor] - STATUS - Running v0.4.1-b12 in ComfyUI
Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from scripts.reactor_faceswap import (
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_logger import logger
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
FizzleDorf Custom Nodes: Loaded
[tinyterraNodes] Loaded
Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'devices' from 'modules' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'devices' from 'modules' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
Traceback (most recent call last):
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfy_vid2vid\sd.py", line 3, in <module>
    from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_unet, model_lora_keys_clip
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\sd.py)

Cannot import M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfy_vid2vid module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\sd.py)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.


[rgthree] Loaded 34 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 212 nodes successfully.

	"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill

FETCH DATA from: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
```

**Comment by jinkexue** [comment]
same issue

**Comment by Gourieff** [comment]
You guys just need to install Insightface properly
I don't use StabilityMatrix because of different difficulties with installing additional things, so I cannot say what exact steps you should do, but try to read the following solutions:

https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27

**Comment by jakopo87** [comment]
I had the same problem and this worked for me:
1. Check your version of Python in <path-to-StabilityMatrix>\Data\Assets
2. Download the prebuilt insight package of for your version of Python from https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
3. In the package list of StabilityMatrix, open the 3 dots menu on ComfyUI e select Python Packages
4. Install insightface using the fullpath to the prebuilt package of insightface

**Comment by nothingness6** [comment]
> I had the same problem and this worked for me:
> 
>     1. Check your version of Python in \Data\Assets
> 
>     2. Download the prebuilt insight package of for your version of Python from https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
> 
>     3. In the package list of StabilityMatrix, open the 3 dots menu on ComfyUI e select Python Packages
> 
>     4. Install insightface using the fullpath to the prebuilt package of insightface

I tried it as well, but no luck.
I just gave it up. It's been more than 6 months I've been struggling with, but can't figure it out somehow.

**Comment by Adestrio** [comment]
Let's just admit Reactor node isn't built very well and recently a lot of people are having similar issues. But they get the same replies with links to follow the same instructions which don't solve anything

**Comment by MasLibman** [comment]
Wow finally. This has been such a pain getting it to work. THANK YOU for the tip.

I had to download the install package into ..\Packages\ComfyUI\venv\Lib\site-packages - once it was located there the install worked. Thanks for the help.
