### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'ReActorMaskHelper' node.

### ISSUE THREAD

**Issue by 925-Studio** [Gourieff/comfyui-reactor-node#275]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Every time I open or refresh the ComfyUI page in the browser, this error appears in the terminal. 

### Workflow
Have already put 2 model files in the right position as readme says: `/home/silver/Playgrounds/AI/sd-comfyui/models/sams/sam_vit_b_01ec64.pth `, `/home/silver/Playgrounds/AI/sd-comfyui/models/ultralytics/bbox/face_yolov8m.pt`.

### Sysinfo

Linux
4080 Super

### Relevant console log

```Shell
Import times for custom nodes:
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_essentials
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI-Manager
   0.2 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_InstantID
   0.3 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_tinyterraNodes
   0.8 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/comfyui-reactor-node

Starting server

To see the GUI go to: http://0.0.0.0:2001
FETCH DATA from: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI-Manager/extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'ReActorMaskHelper' node.
Traceback (most recent call last):
  File "/home/silver/Playgrounds/AI/sd-comfyui/server.py", line 414, in get_object_info
    out[x] = node_info(x)
  File "/home/silver/Playgrounds/AI/sd-comfyui/server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/comfyui-reactor-node/nodes.py", line 606, in INPUT_TYPES
    bboxs = ["bbox/"+x for x in folder_paths.get_filename_list("ultralytics_bbox")]
  File "/home/silver/Playgrounds/AI/sd-comfyui/folder_paths.py", line 223, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/home/silver/Playgrounds/AI/sd-comfyui/folder_paths.py", line 190, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'ultralytics_bbox'
```

**Comment by Gourieff** [comment]
Fixed!

**Comment by Gourieff** [comment]
> Is there a chance I did something wrong?

No, it's on my side
Please try again, should work now

**Comment by 925-Studio** [comment]
> > Is there a chance I did something wrong?
> 
> No, it's on my side Please try again, should work now

I can confirm after your second fix the problem is solved. Thank you for your quick response.

**Comment by ajithradnus** [comment]
Hi got this same Error, How to solve?

`KeyError: 'ultralytics_bbox'`
