### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by topshu** [Gourieff/comfyui-reactor-node#302]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I run comfyUI in ubuntu os and i see the success logs "[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI"

******************************
root@autodl-container-5e5249940a-a28e1f78:~/autodl-tmp/djc/ComfyUI# python main.py 
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-07 18:40:47.677745
** Platform: Linux
** Python version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
** Python executable: /root/miniconda3/bin/python
** Log path: /root/autodl-tmp/djc/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: /root/autodl-tmp/djc/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24217 MB, total RAM 1031695 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16

Using pytorch cross attention
### ComfyUI Revision: 2162 [565eb6d1] | Released on '2024-05-05'
[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI
Torch version: 2.0.0+cu118

Import times for custom nodes:
   0.0 seconds: /root/autodl-tmp/djc/ComfyUI/custom_nodes/websocket_image_save.py
   0.2 seconds: /root/autodl-tmp/djc/ComfyUI/custom_nodes/ComfyUI-Manager
   1.7 seconds: /root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:6006
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: /root/autodl-tmp/djc/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json
FETCH DATA from: /root/autodl-tmp/djc/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json
FETCH DATA from: /root/autodl-tmp/djc/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json
FETCH DATA from: /root/autodl-tmp/djc/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
********************************

but afer a few minutes i found  error logs like that :

[ERROR] An error occurred while retrieving information for the 'ReActorFaceSwap' node.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1414, in connect
    super().connect()
  File "/root/miniconda3/lib/python3.8/http/client.py", line 918, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/djc/ComfyUI/server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "/root/autodl-tmp/djc/ComfyUI/server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 127, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 107, in get_model_names
    models = get_models()
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 101, in get_restorers
    download(model_url, model_path, model_name)
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 113, in download
    request = urllib.request.urlopen(url)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

so,how i can i do to fix it?thanks!

### Steps to reproduce the problem

the error occurs at comfyui startup

### Sysinfo

** Platform: Linux
** Python version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]

Total VRAM 24217 MB, total RAM 1031695 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16

### Relevant console log

```Shell
[ERROR] An error occurred while retrieving information for the 'ReActorFaceSwap' node.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/root/miniconda3/lib/python3.8/http/client.py", line 1414, in connect
    super().connect()
  File "/root/miniconda3/lib/python3.8/http/client.py", line 918, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/djc/ComfyUI/server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "/root/autodl-tmp/djc/ComfyUI/server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 127, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 107, in get_model_names
    models = get_models()
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 101, in get_restorers
    download(model_url, model_path, model_name)
  File "/root/autodl-tmp/djc/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 113, in download
    request = urllib.request.urlopen(url)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
```

**Comment by Gourieff** [comment]
> urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

You should be connected to the Internet for the first run to let ReActor download some models

> python3.8

Also never tested with Py3.8, no guarantee it will work properly and with no errors
