### ISSUE TITLE
I got an error on startup

### ISSUE THREAD

**Issue by sakiyo18** [Gourieff/comfyui-reactor-node#313]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When starting, the terminal shows that the import failed.

### Steps to reproduce the problem

Your workflow

### Sysinfo

Windows10,RTX3050

### Relevant console log

```Shell
ComfyUI Launcher Diagnostic File

Date: 2024-05-19 15:16:56
Launcher Version: 2.8.4.332
Data File Version: 2024-05-18 17:21
ComfyUI Version: 4201181b35402e0a992b861f8d2f0e0b267f52fa (2024-04-09 16:25:45)
Working Directory: G:\Comfyui_MR
------------------------
System Information: 
OS: Microsoft Windows NT 10.0.19045.0
CPU: 12 cores
Memory Size: 49152 MB
Page File Size: 7168 MB

NVIDIA Management Library:
  NVIDIA Driver Version: 536.23
  NVIDIA Management Library Version: 12.536.23

CUDA Driver:
  Version: 12020
  Devices: 
    00000000:01:00.0 0: NVIDIA GeForce RTX 3050 [86] 8 GB

NvApi:
  Version: 53623 r536_08

HIP Driver:
  Not Available

DirectML Driver: 
  Devices: 
    9479 0: NVIDIA GeForce RTX 3050 7 GB
    9479 1: NVIDIA GeForce RTX 3050 7 GB

Intel Level Zero Driver:
  Not Available

------------------------
Environment Variables: 
USERDOMAIN=DESKTOP-NI7UAH8
PROCESSOR_LEVEL=6
ProgramW6432=C:\Program Files
PROCESSOR_ARCHITECTURE=AMD64
SystemRoot=C:\Windows
NUMBER_OF_PROCESSORS=12
FPS_BROWSER_USER_PROFILE_STRING=Default
USERDOMAIN_ROAMINGPROFILE=DESKTOP-NI7UAH8
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
ProgramFiles=C:\Program Files
TEMP=C:\Users\mengru\AppData\Local\Temp
OS=Windows_NT
PUBLIC=C:\Users\Public
CommonProgramFiles=C:\Program Files\Common Files
PROCESSOR_REVISION=9705
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;H:\Bandizip\;H:\Git\cmd;C:\Program Files\dotnet\;C:\Users\mengru\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\mengru\AppData\Local\Programs\Python\Python311\;C:\Users\mengru\AppData\Local\Microsoft\WindowsApps;
ProgramFiles(x86)=C:\Program Files (x86)
ALLUSERSPROFILE=C:\ProgramData
HOMEDRIVE=C:
USERPROFILE=C:\Users\mengru
CommonProgramW6432=C:\Program Files\Common Files
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SESSIONNAME=Console
HOMEPATH=\Users\mengru
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel
LOCALAPPDATA=C:\Users\mengru\AppData\Local
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
USERNAME=mengru
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
COMPUTERNAME=DESKTOP-NI7UAH8
ProgramData=C:\ProgramData
SystemDrive=C:
windir=C:\Windows
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
LOGONSERVER=\\DESKTOP-NI7UAH8
APPDATA=C:\Users\mengru\AppData\Roaming
TMP=C:\Users\mengru\AppData\Local\Temp
------------------------
Paths: 
Python: G:\Comfyui_MR\python\python.exe
  - Python Paths:
    - G:\Comfyui_MR\python\DLLs
    - G:\Comfyui_MR\python\lib
    - G:\Comfyui_MR\python
    - G:\Comfyui_MR\python\lib\site-packages
    - G:\Comfyui_MR\python\lib\site-packages\win32
    - G:\Comfyui_MR\python\lib\site-packages\win32\lib
    - G:\Comfyui_MR\python\lib\site-packages\Pythonwin
  - Python Packages:
    - absl_py 2.0.0 
    - accelerate 0.23.0 
    - addict 2.4.0 
    - aiohttp 3.8.5 
    - aiosignal 1.3.1 
    - albumentations 1.3.1 
    - alibabacloud_credentials 0.3.2 
    - alibabacloud_endpoint_util 0.0.3 
    - alibabacloud_gateway_spi 0.0.1 
    - alibabacloud_imageseg20191230 3.0.0 
    - alibabacloud_openapi_util 0.2.2 
    - alibabacloud_openplatform20191219 2.0.0 
    - alibabacloud_oss_sdk 0.1.0 
    - alibabacloud_oss_util 0.0.6 
    - alibabacloud_tea 0.3.6 
    - alibabacloud_tea_console 0.0.1 
    - alibabacloud_tea_fileform 0.0.5 
    - alibabacloud_tea_openapi 0.3.8 
    - alibabacloud_tea_util 0.3.11 
    - alibabacloud_tea_xml 0.0.2 
    - annotated_types 0.6.0 
    - antlr4_python3_runtime 4.9.3 
    - anyio 4.2.0 
    - argostranslate 1.9.1 
    - async_timeout 4.0.3 
    - attrs 23.1.0 
    - beautifulsoup4 4.12.2 
    - boltons 23.0.0 
    - cachetools 5.3.3 
    - certifi 2023.7.22 
    - cffi 1.16.0 
    - chardet 5.2.0 
    - charset_normalizer 3.2.0 
    - click 8.1.7 
    - clip_interrogator 0.6.0 
    - cmake 3.27.7 
    - colorama 0.4.6 
    - coloredlogs 15.0.1 
    - colorlog 6.8.0 
    - colour_science 0.4.4 
    - contourpy 1.1.1 
    - cryptography 42.0.5 
    - cssselect2 0.7.0 
    - ctranslate2 3.20.0 
    - cycler 0.12.1 
    - Cython 3.0.8 
    - deepdiff 6.7.1 
    - deep_translator 1.11.4 
    - diffusers 0.25.0 
    - einops 0.6.1 
    - embreex 2.17.7.post4 
    - exceptiongroup 1.2.0 
    - fairscale 0.4.13 
    - fastapi 0.110.1 
    - filelock 3.12.4 
    - flatbuffers 23.5.26 
    - fonttools 4.43.1 
    - frozenlist 1.4.0 
    - fsspec 2023.9.1 
    - ftfy 6.1.1 
    - future 1.0.0 
    - gdown 5.1.0 
    - gitdb 4.0.11 
    - GitPython 3.1.40 
    - googleapis_common_protos 1.63.0 
    - google_ai_generativelanguage 0.4.0 
    - google_api_core 2.17.1 
    - google_auth 2.28.2 
    - google_auth_oauthlib 0.4.6 
    - google_generativeai 0.4.1 
    - grpcio 1.62.1 
    - grpcio_status 1.48.2 
    - h11 0.14.0 
    - h2 4.1.0 
    - hpack 4.0.0 
    - httpcore 1.0.2 
    - httpx 0.26.0 
    - huggingface_hub 0.20.2 
    - humanfriendly 10.0 
    - hyperframe 6.0.1 
    - idna 3.4 
    - imageio 2.31.5 
    - importlib_metadata 6.8.0 
    - insightface 0.7.3 
    - Jinja2 3.1.2 
    - joblib 1.3.2 
    - jsonschema 4.20.0 
    - jsonschema_specifications 2023.7.1 
    - kiwisolver 1.4.5 
    - kornia 0.7.2 
    - kornia_rs 0.1.1 
    - lazy_loader 0.3 
    - lightning_utilities 0.10.1 
    - llvmlite 0.41.1 
    - lmdb 1.4.1 
    - loguru 0.7.2 
    - lpips 0.1.4 
    - lxml 4.9.3 
    - mapbox_earcut 1.0.1 
    - Markdown 3.6 
    - markdown_it_py 3.0.0 
    - MarkupSafe 2.1.3 
    - matplotlib 3.7.1 
    - matrix_client 0.4.0 
    - mdurl 0.1.2 
    - mediapipe 0.10.7 
    - mpmath 1.3.0 
    - multidict 6.0.4 
    - networkx 3.1 
    - numba 0.58.1 
    - numexpr 2.8.8 
    - numpy 1.23.5 
    - oauthlib 3.2.2 
    - omegaconf 2.3.0 
    - onnx 1.15.0 
    - onnxruntime 1.17.0 
    - onnxruntime_gpu 1.17.0 
    - opencv_contrib_python 4.8.1.78 
    - opencv_python 4.8.1.78 
    - opencv_python_headless 4.7.0.72 
    - open_clip_torch 2.24.0 
    - ordered_set 4.1.0 
    - packaging 23.1 
    - pandas 2.1.3 
    - piexif 1.1.3 
    - pilgram 1.2.1 
    - Pillow 9.5.0 
    - pip 23.0.1 
    - platformdirs 3.11.0 
    - pooch 1.8.0 
    - portalocker 2.8.2 
    - prettytable 3.9.0 
    - protobuf 3.19.6 
    - proto_plus 1.23.0 
    - psutil 5.9.5 
    - pyasn1 0.5.1 
    - pyasn1_modules 0.3.0 
    - pycparser 2.21 
    - pydantic 2.6.4 
    - pydantic_core 2.16.3 
    - pygments 2.17.2 
    - PyMatting 1.1.12 
    - pynvml 11.5.0 
    - pyparsing 3.1.1 
    - pyreadline3 3.4.1 
    - PySocks 1.7.1 
    - python_dateutil 2.8.2 
    - pytorch_lightning 2.1.2 
    - pytz 2023.3.post1 
    - pywavelets 1.5.0 
    - pywin32 306 
    - PyYAML 6.0.1 
    - py_cpuinfo 9.0.0 
    - qudida 0.0.4 
    - referencing 0.30.2 
    - regex 2023.8.8 
    - rembg 2.0.52 
    - reportlab 4.0.6 
    - requests 2.31.0 
    - requests_oauthlib 1.4.0 
    - rich 13.7.1 
    - rpds_py 0.12.0 
    - rsa 4.9 
    - Rtree 1.1.0 
    - safetensors 0.4.2 
    - scikit_image 0.20.0 
    - scikit_learn 1.3.2 
    - scipy 1.12.0 
    - seaborn 0.13.0 
    - segment_anything 1.0 
    - sentencepiece 0.1.99 
    - setuptools 65.5.0 
    - shapely 2.0.2 
    - shellingham 1.5.4 
    - simpleeval 0.9.13 
    - six 1.16.0 
    - smmap 5.0.1 
    - sniffio 1.3.0 
    - sounddevice 0.4.6 
    - soupsieve 2.5 
    - stanza 1.1.1 
    - starlette 0.37.2 
    - svg.path 6.3 
    - sympy 1.12 
    - tabulate 0.9.0 
    - tb_nightly 2.11.0a20220906 
    - tensorboard_data_server 0.6.1 
    - tensorboard_plugin_wit 1.8.1 
    - termcolor 2.3.0 
    - thop 0.1.1.post2209072238 
    - threadpoolctl 3.2.0 
    - tifffile 2023.9.26 
    - timm 0.6.13 
    - tinycss2 1.2.1 
    - tokenizers 0.15.1 
    - tomli 2.0.1 
    - torch 2.1.2+cu118 
    - torchmetrics 1.3.1 
    - torchsde 0.2.5 
    - torchvision 0.16.2+cu118 
    - tqdm 4.66.1 
    - trampoline 0.1.2 
    - transformers 4.37.2 
    - trimesh 4.0.9 
    - typer 0.12.3 
    - typer_config 1.4.0 
    - typing_extensions 4.8.0 
    - tzdata 2023.3 
    - ultralytics 8.0.223 
    - urllib3 1.26.18 
    - vhacdx 0.0.5 
    - wcwidth 0.2.8 
    - webencodings 0.5.1 
    - werkzeug 3.0.1 
    - wget 3.2 
    - wheel 0.43.0 
    - win32_setctime 1.1.0 
    - xformers 0.0.23.post1+cu118 
    - xxhash 3.4.1 
    - yacs 0.1.8 
    - yapf 0.40.2 
    - yarl 1.9.2 
    - zipp 3.17.0 
    - cstr 0.1.0 
    - easydict 1.11 
    - ffmpy 0.3.0 
    - fvcore 0.1.5.post20221221 
    - googletrans_py 4.0.0 
    - img2texture 1.0.6 
    - iopath 0.1.10 
    - openai_clip 1.0.1 
    - pycollada 0.8 
    - sacremoses 0.0.53 
    - svglib 1.5.1 
Git: G:\Comfyui_MR\git\cmd\git.exe
Shell: C:\Windows\system32\cmd.exe
Cache Path: G:\Comfyui_MR\.cache
------------------------
Engine Validator: 
PyTorch: 2.1.2+cu118 C(11080)___
OnnxRuntime: CUDA(11080)
------------------------
Config: 
Audience Type: 高级
Engine: CUDA GPU 0: NVIDIA GeForce RTX 3050 (8 GB) [0]
VRAM Optimization: Auto [Auto]
Port: 8188 [8188]
XAttn Optimization: Xformers [Xformers]
Upcast Attention: True [True]
Precision: Auto [Auto]
Text Encoder Precision: Auto [Auto]
UNet Precision: Auto [Auto]
VAE Precision: Auto [Auto]
Preview Method: Auto [Auto]
Smart Memory: True [True]
Deterministic: False [False]
Listen: False [False]
Server Name:  []
HF Offline Mode: False [False]
Cuda Allocator Backend: CudaMallocAsync [CudaMallocAsync]
Prevent Sysmem Fallback: False
Extra Args: 
------------------------
Network Preferences: 
Proxy Address: http://127.0.0.1:10809
Proxy Git: True
Proxy Pip: True
Proxy Model Download: True
Proxy Env: True
Mirror Pypi: False
Mirror Git: False
Mirror ExtensionList: True
Mirror Huggingface: True
Github Acceleration: False
------------------------
Log: 
FETCH DATA from: G:\Comfyui_MR\custom_nodes\ComfyUI-Manager\extension-node-map.json
** ComfyUI startup time: 2024-05-19 15:16:24.613472
** Platform:
 
Windows
** Python version: 
3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: G:\Comfyui_MR\python\python.exe

** Log path: G:\Comfyui_MR\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Marigold

   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 48994 MB
xformers version: 0.0.23.post1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
[Crystools [0;32mINFO[0m] Crystools version: 1.11.0
[Crystools [0;32mINFO[0m] CPU: 12th Gen Intel(R) Core(TM) i5-12400F - Arch: AMD64 - OS: Windows 10
[Crystools [0;32mINFO[0m] GPU/s:
[Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 3050
[Crystools [0;32mINFO[0m] NVIDIA Driver: 536.23
[34mComfy-Easy-Use (v1.1.1): [92mLoaded[0m
### Loading: ComfyUI-Impact-Pack (V4.83.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
### Loading: ComfyUI-Inspire-Pack (V0.63)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.7.2)
### ComfyUI Revision: 2120 [4201181b] | Released on '2024-04-09'
[34mOpenPose Editor: [92mLoaded[0m
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/alter-list.json
Traceback (most recent call last):
  File "G:\Comfyui_MR\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Comfyui_MR\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\Comfyui_MR\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.external_data_helper import (
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\external_data_helper.py", line 11, in <module>
    from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (G:\Comfyui_MR\python\lib\site-packages\google\protobuf\internal\__init__.py)

Cannot import G:\Comfyui_MR\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'builder' from 'google.protobuf.internal' (G:\Comfyui_MR\python\lib\site-packages\google\protobuf\internal\__init__.py)
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/model-list.json
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/custom-node-list.json
------------------------------------------
[34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: G:\Comfyui_MR\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
DWPose: Onnxruntime with acceleration providers detected
[1;35m### [START] ComfyUI AlekPet Nodes ###[0m
[92mNode -> ArgosTranslateNode [Loading][0m
[92mNode -> ExtrasNode [Loading][0m
[92mNode -> PainterNode [Loading][0m
[92mNode -> PoseNode [Loading][0m
[92mNode -> TranslateNode [Loading][0m
[1;35m### [END] ComfyUI AlekPet Nodes ###[0m
[34mFizzleDorf Custom Nodes: [92mLoaded[0m
Traceback (most recent call last):
  File "G:\Comfyui_MR\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Comfyui_MR\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\Comfyui_MR\custom_nodes\ComfyUI_InstantID\InstantID.py", line 14, in <module>
    from insightface.app import FaceAnalysis
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "G:\Comfyui_MR\python\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.external_data_helper import (
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\external_data_helper.py", line 11, in <module>
    from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "G:\Comfyui_MR\python\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (G:\Comfyui_MR\python\lib\site-packages\google\protobuf\internal\__init__.py)

Cannot import G:\Comfyui_MR\custom_nodes\ComfyUI_InstantID module for custom nodes: cannot import name 'builder' from 'google.protobuf.internal' (G:\Comfyui_MR\python\lib\site-packages\google\protobuf\internal\__init__.py)
# 😺dzNodes: LayerStyle -> [1;33mCannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to [4mhttps://github.com/chflame163/ComfyUI_LayerStyle/issues/5[0m[m
# 😺dzNodes: LayerStyle -> [1;33mInvalid FONT directory, default to be used. check G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini[m
# 😺dzNodes: LayerStyle -> [1;33mInvalid LUT directory, default to be used. check G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini[m
# 😺dzNodes: LayerStyle -> [1;33mFind 1 LUTs in G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle\lut[m
# 😺dzNodes: LayerStyle -> [1;33mFind 1 Fonts in G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle\font[m
Traceback (most recent call last):
  File "G:\Comfyui_MR\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle\__init__.py", line 60, in <module>
    imported_module = importlib.import_module(".py.{}".format(name), __name__)
  File "G:\Comfyui_MR\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle\py\person_mask_ultra_v2.py", line 4, in <module>
    import mediapipe as mp
  File "G:\Comfyui_MR\python\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "G:\Comfyui_MR\python\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "G:\Comfyui_MR\python\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "G:\Comfyui_MR\python\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "G:\Comfyui_MR\python\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (G:\Comfyui_MR\python\lib\site-packages\google\protobuf\internal\__init__.py)

Cannot import G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle module for custom nodes: cannot import name 'builder' from 'google.protobuf.internal' (G:\Comfyui_MR\python\lib\site-packages\google\protobuf\internal\__init__.py)
[92m[tinyterraNodes] [32mLoaded[0m

[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
[1;32m[Power Noise Suite]: 🦚🦚🦚 [93m[3mSup.[0m 🦚🦚🦚
[1;32m[Power Noise Suite]:[0m Tamed [93m11[0m wild nodes.

Import times for custom nodes:
   0.0 seconds: G:\Comfyui_MR\custom_nodes\websocket_image_save.py
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Catcat
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-N-Sidebar
   0.0 seconds: G:\Comfyui_MR\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_Noise
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_Adapter
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: G:\Comfyui_MR\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_experiments
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-SuperBeasts
   0.0 seconds: G:\Comfyui_MR\custom_nodes\PowerNoiseSuite
   0.0 seconds: G:\Comfyui_MR\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: G:\Comfyui_MR\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: G:\Comfyui_MR\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds (IMPORT FAILED): G:\Comfyui_MR\custom_nodes\ComfyUI_InstantID
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: G:\Comfyui_MR\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Marigold
   0.0 seconds: G:\Comfyui_MR\custom_nodes\facerestore_cf
   0.0 seconds: G:\Comfyui_MR\custom_nodes\Comfyui_ALY
   0.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: G:\Comfyui_MR\custom_nodes\comfyui_segment_anything
   0.1 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-BiRefNet-ZHO
   0.2 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Gemini
   0.2 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Easy-Use
   0.2 seconds (IMPORT FAILED): G:\Comfyui_MR\custom_nodes\ComfyUI_LayerStyle
   0.3 seconds (IMPORT FAILED): G:\Comfyui_MR\custom_nodes\comfyui-reactor-node
   0.3 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_FizzNodes
   0.4 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Manager
   0.5 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_tinyterraNodes
   1.3 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-SUPIR
   2.8 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Impact-Pack
   5.3 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   6.0 seconds: G:\Comfyui_MR\custom_nodes\ComfyUI-Crystools

Starting server

------------------------
Fault Traceback: 
Not Available
```

**Comment by Gourieff** [comment]
> - protobuf 3.19.6 

Try to install protobuf 3.20.3
