### ISSUE TITLE
Video processing takes a lot of memory

### ISSUE THREAD

**Issue by start-life** [Gourieff/comfyui-reactor-node#314]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I was working with a video that weighs 75 MB and I had 19 GB free and it would work, use all the free memory (19 GB) and give an error that there is no memory

### Steps to reproduce the problem

Working with video
Using ComfyUI-VideoHelperSuite
comfyui-reactor-node

### Sysinfo

Using ComfyUI-VideoHelperSuite
comfyui-reactor-node

### Relevant console log

```Shell
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5472 but got size 1080 for tensor number 1 in the list.

Prompt executed in 0.35 seconds
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1478, in load_image
    output_image = torch.cat(output_images, dim=0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5472 but got size 1080 for tensor number 1 in the list.
```

**Comment by Gourieff** [comment]
Feel free to test "mem_test" branch https://github.com/Gourieff/comfyui-reactor-node/tree/mem_test with the latest commit https://github.com/Gourieff/comfyui-reactor-node/commit/7bd408b67520f8259bcc1e1bae3beb4d48f59b11 to see if there are any RAM benefits by combining different methods of analyzing images:

> Additional fields in the ReActorOptions Node:
> - analyzer_load: "fast" or "slow" (old method)
> - processing_method: "analyzing -> swapping" or "analyzing + swapping" (old way)

**Comment by Gourieff** [comment]
Related #310 #312

**Comment by start-life** [comment]
Hi I'm not talking about the processing memory or the RAM I'm talking about it taking up a lot of disk space HDD or SSD I put a 75 MB video and I had 19 GB free and it used all 19 GB And then he wrote that there was a memory error because there was no more space left

**Comment by flynet** [comment]
Faced the same problem, 300MB file took over 70GB RAM and end up with error unable allocate memory array.

As temporary solution, use Load Image (Path ) with frames. ( in images took 1.7 GB )
`ffmpeg -i in.mp4 -qscale:v 1 -qmin 1 -qmax 1 -vsync 0 tmp_frames\frame%08d.jpg`
To loop over each file, added primitive increment node for frame ID and enabled instant Auto Query, and then back to mp4
`ffmpeg -framerate 29.97 -i tmp_frames\frame%08d.jpg -i in.mp4 -map 0:v -map 1:a:0 -c:a aac -b:a 128k -c:v libx264 -r 29.97 -pix_fmt yuv420p out.mp4`

**Comment by dociinhohot** [comment]
I  received a 

> Faced the same problem, 300MB file took over 70GB RAM and end up with error unable allocate memory array.
> 
> As temporary solution, I use Load Image (Path ) with frames. (300MB (30fps ) took 1.7GB space) `ffmpeg -i in.mp4 -qscale:v 1 -qmin 1 -qmax 1 -vsync 0 tmp_frames\frame_%06d.jpg` To loop over each file, added primitive increment node for frame ID and enabled instant Auto Query, process will end with error no files in directory when it's done. You may need custom Image Save Node (Save Image Extended ) to customize image names with preserved frame index. and then back to mp4 `ffmpeg -framerate 29.97 -i tmp_frames\frame_%06d.jpg -i in.mp4 -map 0:v -map 1:a:0 -c:a aac -b:a 128k -c:v libx264 -r 29.97 -pix_fmt yuv420p out.mp4`
> 
> With this simple workflow u can pause process, and continue from the last frame adjusting increment value [test_workflow.json](https://github.com/Gourieff/comfyui-reactor-node/files/15449260/test_workflow.json) .

`Error occurred when executing FILM VFI:

The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
File "code/__torch__/util.py", line 30, in forward
features1 = pyramid1[_9]
features2 = pyramid2[_9]
_10 = torch.cat([features1, features2], 1)
~~~~~~~~~ <--- HERE
_11 = torch.append(_7, _10)
return _7

Traceback of TorchScript, original code (most recent call last):
File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\util.py", line 143, in forward
result = []
for features1, features2 in zip(pyramid1, pyramid2):
result.append(torch.cat([features1, features2], dim=1))
~~~~~~~~~ <--- HERE
return result
RuntimeError: Allocation on device


File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\film\__init__.py", line 94, in vfi
relust = inference(model, frame_0, frame_1, multipliers[frame_itr] - 1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\film\__init__.py", line 36, in inference
prediction = model(x0, x1, dt)
^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by dociinhohot** [comment]
> Faced the same problem, 300MB file took over 70GB RAM and end up with error unable allocate memory array.
> 
> As temporary solution, I use Load Image (Path ) with frames. (300MB (30fps ) took 1.7GB space) `ffmpeg -i in.mp4 -qscale:v 1 -qmin 1 -qmax 1 -vsync 0 tmp_frames\frame_%06d.jpg` To loop over each file, added primitive increment node for frame ID and enabled instant Auto Query, process will end with error no files in directory when it's done. You may need custom Image Save Node (Save Image Extended ) to customize image names with preserved frame index. and then back to mp4 `ffmpeg -framerate 29.97 -i tmp_frames\frame_%06d.jpg -i in.mp4 -map 0:v -map 1:a:0 -c:a aac -b:a 128k -c:v libx264 -r 29.97 -pix_fmt yuv420p out.mp4`
> 
> With this simple workflow u can pause process, and continue from the last frame adjusting increment value [test_workflow.json](https://github.com/Gourieff/comfyui-reactor-node/files/15449260/test_workflow.json) .

I have a similar memory problem, but it happens on the FILM VFI node. I can't clear the interpolation cache, but it still overflows my memory and I need to run the queue again for it to interpolate the missing frames. However, doing this takes a long time to finish processing the video.
