### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by cobaltbeau** [Gourieff/comfyui-reactor-node#338]
EDIT: sorry, I made this before I was ready - this can be deleted.

### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

My initial install wasn't successful, it looks like it's having trouble with the insightface module.

### Sysinfo

I'm on Windows with a 4070

### Relevant console log

```Shell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-21 13:01:55.054757
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\p\ComfyUI\python_embeded\python.exe
** Log path: D:\p\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   1.0 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 31905 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
Using pytorch cross attention
Adding extra search path checkpoints D:\p\temp\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs D:\p\temp\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae D:\p\temp\stable-diffusion-webui\models/VAE
Adding extra search path loras D:\p\temp\stable-diffusion-webui\models/Lora
Adding extra search path loras D:\p\temp\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models D:\p\temp\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models D:\p\temp\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models D:\p\temp\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings D:\p\temp\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks D:\p\temp\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet D:\p\temp\stable-diffusion-webui\models/ControlNet
Adding extra search path checkpoints D:\p\ComfyUI\models/checkpoints/
Adding extra search path clip D:\p\ComfyUI\models/clip/
Adding extra search path clip_vision D:\p\ComfyUI\models/clip_vision/
Adding extra search path configs D:\p\ComfyUI\models/configs/
Adding extra search path controlnet D:\p\ComfyUI\models/controlnet/
Adding extra search path embeddings D:\p\ComfyUI\models/embeddings/
Adding extra search path loras D:\p\ComfyUI\models/loras/
Adding extra search path upscale_models D:\p\ComfyUI\models/upscale_models/
Adding extra search path vae D:\p\ComfyUI\models/vae/
### Loading: ComfyUI-Impact-Pack (V5.15.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.38.2)
### ComfyUI Revision: 2265 [55f0dc12] | Released on '2024-06-18'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Traceback (most recent call last):
  File "D:\p\ComfyUI\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\p\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\p\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\p\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[06/21/24 13:01:59] WARNING  Your inference package version 0.9.13 is out of date! Please upgrade to      __init__.py:35
                             version 0.12.1 of inference for the latest features and bug fixes by running
                             `pip install --upgrade inference`.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\p\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\p\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 216 nodes successfully.

        "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." - Steve Jobs


Import times for custom nodes:
   0.0 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds (IMPORT FAILED): D:\p\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.6 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
   1.8 seconds: D:\p\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\p\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

**Comment by darcwader** [comment]
am facing same issue.

**Comment by Yinghoo** [comment]
I have the same issue.

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+%22No+module+named+%27insightface%27%22
