### ISSUE TITLE
Error occurred when executing ReActorFaceSwap:  'reactor' object has no attribute 'boost_model'

### ISSUE THREAD

**Issue by atuoyi** [Gourieff/comfyui-reactor-node#348]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Error occurred when executing ReActorFaceSwap:

'reactor' object has no attribute 'boost_model'

File "F:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 350, in execute
face_restore_model=self.boost_model,

### Steps to reproduce the problem

[32m[rgthree] Using rgthree's optimized recursive execution.[0m
!!! Exception during processing!!! 'reactor' object has no attribute 'boost_model'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 350, in execute
    face_restore_model=self.boost_model,
AttributeError: 'reactor' object has no attribute 'boost_model'

### Sysinfo

[32m[rgthree] Using rgthree's optimized recursive execution.[0m
!!! Exception during processing!!! 'reactor' object has no attribute 'boost_model'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 350, in execute
    face_restore_model=self.boost_model,
AttributeError: 'reactor' object has no attribute 'boost_model'

### Relevant console log

```Shell
[32m[rgthree] Using rgthree's optimized recursive execution.[0m
!!! Exception during processing!!! 'reactor' object has no attribute 'boost_model'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 350, in execute
    face_restore_model=self.boost_model,
AttributeError: 'reactor' object has no attribute 'boost_model'
```

**Comment by atuoyi** [comment]
已经解决

**Comment by romeo5460** [comment]
? 

> 已经解决

同样问题 请问如何解决？

**Comment by Gourieff** [comment]
> ?
> 
> > 已经解决
> 
> 同样问题 请问如何解决？

I think you should just update ReActor to the latest commit

**Comment by MarkoCa1** [comment]
一开始是
ImportError: cannot import name 'builder' from 'google.protobuf.internal'，cannot import name 'devices' from 'models'
然后我更新了protobuf后就没有出现上面的报错，但是运行时出现ReActorFaceSwap: 'reactor' object has no attribute 'boost_model'
更新ReActor也没有解决问题

**Comment by wenroo** [comment]
working,  thank u so much.

**Comment by darkpixel** [comment]
The latest commit didn't fix it on my end:

```
!!! Exception during processing!!! 'ReActorPlusOpt' object has no attribute 'boost_model'
Traceback (most recent call last):
  File "/ai/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/ai/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/ai/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 431, in execute
    result = reactor.execute(
  File "/ai/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 361, in execute
    face_restore_model=self.boost_model,
AttributeError: 'ReActorPlusOpt' object has no attribute 'boost_model'
```

```
$ git log -1
commit a48fbf533140b0ed91054c69c17bd03adfd6a941 (HEAD -> main, origin/main, origin/HEAD)
Author: Art Gourieff <85128026+Gourieff@users.noreply.github.com>
Date:   Tue Jul 2 13:32:51 2024 +0700

    VersionUP
    
    0.5.1 alpha4
```

**Comment by robertobalestri** [comment]
I have the same problem

**Comment by Gourieff** [comment]
Fixed

**Comment by ThatStar9527** [comment]
Exactly how to solve, also do not give a systematic solution???
