### ISSUE TITLE
error when running - new install

### ISSUE THREAD

**Issue by alenknight** [Gourieff/comfyui-reactor-node#37]
getting the following error on a fresh install of comfyui.
tried on 2 machines... same error.

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/22153900/12eac8b0-21c6-4892-8fc3-f6ef9592a1e9)

**Comment by alenknight** [comment]
I should note - I did the Vbasic install and it's running in a4. Just not in comfyui.

**Comment by Gourieff** [comment]
Try the following but for `python_embeded\python.exe` enclosure: https://github.com/Gourieff/sd-webui-reactor/issues/107#issuecomment-1728783507

**Comment by alenknight** [comment]
now... after trying that comment suggestion....  i'm getting some error about 'protobuf' needing to be downgraded?

```
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-09-25 02:08:51.063118

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32704 MB
xformers version: 0.0.21
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_management.py", line 211, in <module>
    import accelerate
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\__init__.py", line 142, in <module>
    from .megatron_lm import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\main.py", line 72, in <module>
    import execution
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\AI\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 12, in <module>
    from . import clip_vision
  File "C:\AI\ComfyUI\ComfyUI\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, CLIPImageProcessor, modeling_utils
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .utils import is_tokenizers_available
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by alenknight** [comment]
i got past that error by downgrading protobuf - deleting google in site-packages... but that fix you pointed to... maybe i'm doing it wrong? takes me back to the same error and upgrades my protobuf.... breaking everything

```
Error occurred when executing ReActorFaceSwap:

This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

File "C:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 75, in execute
script.process(
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 91, in process
result = swap_face(
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 137, in swap_face
source_face, wrong_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 81, in get_face_single
face_analyser = copy.deepcopy(getAnalysisModel())
File "copy.py", line 172, in deepcopy
File "copy.py", line 271, in _reconstruct
File "copy.py", line 146, in deepcopy
File "copy.py", line 231, in _deepcopy_dict
File "copy.py", line 146, in deepcopy
File "copy.py", line 231, in _deepcopy_dict
File "copy.py", line 172, in deepcopy
File "copy.py", line 271, in _reconstruct
File "copy.py", line 146, in deepcopy
File "copy.py", line 231, in _deepcopy_dict
File "copy.py", line 172, in deepcopy
File "copy.py", line 273, in _reconstruct
File "C:\AI\ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
self.__init__(model_path)
File "C:\AI\ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
super().__init__(model_path, **kwargs)
File "C:\AI\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
raise e
File "C:\AI\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "C:\AI\ComfyUI\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
raise ValueError(
```

**Comment by Gourieff** [comment]
What version of onnxruntime library do you have?
If 1.16.0 - it's buggy

**Comment by alenknight** [comment]
perhaps that's the issue... how do i find out?  i saw your reqs.txt file has 1.14.0... i can rerun for that... but before i do, how do i check which version i have?

**Comment by Gourieff** [comment]
`python_embeded\python.exe -m pip show onnxruntime` or `python_embeded\python.exe -m pip show onnxruntime-gpu`

if you have `onnxruntime 1.16.0` or `onnxruntime-gpu` ReActor Node won't work

Just install the appropriate version: 
`python_embeded\python.exe -m pip uninstall -y onnxruntime onnxruntime-gpu`
`python_embeded\python.exe -m pip install onnxruntime==1.15.1`

**Comment by alenknight** [comment]
thanks.  reinstalling and rerunning the scripts you mentioned fixed this issue.

**Comment by ArmouryGaming** [comment]
> `python_embeded\python.exe -m pip show onnxruntime` or `python_embeded\python.exe -m pip show onnxruntime-gpu`
> 
> if you have `onnxruntime 1.16.0` or `onnxruntime-gpu` ReActor Node won't work
> 
> Just install the appropriate version: `python_embeded\python.exe -m pip uninstall -y onnxruntime onnxruntime-gpu` `python_embeded\python.exe -m pip install onnxruntime==1.15.1`

This is really good to know. This comment just let me fix a totally different onnxruntime error. (CUDA/cDNN installed but not found, check PATH or install the right version). It was installed and the PATH was fine, it was just version 1.16.0 causing issues.

**Comment by QueenPuxxi** [comment]
> `python_embeded\python.exe -m pip show onnxruntime` or `python_embeded\python.exe -m pip show onnxruntime-gpu`
> 
> if you have `onnxruntime 1.16.0` or `onnxruntime-gpu` ReActor Node won't work
> 
> Just install the appropriate version: `python_embeded\python.exe -m pip uninstall -y onnxruntime onnxruntime-gpu` `python_embeded\python.exe -m pip install onnxruntime==1.15.1`

I have done so, but it will still report the error. Is there any other solution?
