### ISSUE TITLE
Since ORT 1.9, you are required to explicitly set the providers parameter

### ISSUE THREAD

**Issue by LukeOvermind** [Gourieff/comfyui-reactor-node#38]
Hi thanks for the great Nodes. Just my luck, I actually got it to work with one image last night yet this morning I am unable to do and give the below error,

I use comfyui on Colab pro.  I had to and still run the following with every runtime: 

!pip install insightface
!pip install onnxruntime

Which seemed to work untill it didnt. Other changes I made was to download the the upscalers?

Sorry I have no coding experience

Please help! And Thank you!

Here the console error:

  8:21:54 - ReActor Node - STATUS - Working: source face index [0], target face index [0]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 75, in execute
    script.process(
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 91, in process
    result = swap_face(
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 137, in swap_face
    source_face, wrong_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 81, in get_face_single
    face_analyser = copy.deepcopy(getAnalysisModel())
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 273, in _reconstruct
    y.__setstate__(state)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 33, in __setstate__
    self.__init__(model_path)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by rr3khan** [comment]
Running into a similar error

"D:\Projects\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvide

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/37#issuecomment-1728803735

I'm curious what the Node causes installing of `onnxruntime-extension` and why - `AzureExecutionProvider` needs for audio as I know
What is reason to use `ort-extension` build?

**Comment by LukeOvermind** [comment]
Hi thanks for coming back to me. So I deleted my runtime and restarted. Might be Impact Pack? But it only created a folder for it

### ComfyUI-Impact-Pack: onnx model directory created (/content/drive/MyDrive/ComfyUI/models/onnx)

But I am not using Impact Pack in my workflow

Below my extentions. I did not Pip Install InsightFace

Import times for custom nodes:
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/saturation_ally.py
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/brightness_contrast_ally.py
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/histogram_equalization.py
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/gaussian_blur_ally.py
   0.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/imageflip_ally.py
   0.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/Pseudo_HDR_ally.py
   0.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/gcLatentTunnel.py
   0.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/yugioh-presets.py
   0.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sdxl_utility.py
   0.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/conditioning_sizing_for_SDXL.py
   0.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sharpness_ally.py
   1.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sdxl-recommended-res-calc
   1.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_dagthomas
   1.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/wlsh_nodes
   1.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_TiledKSampler
   1.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/mikey_nodes
   2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sdxl_prompt_styler
   2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/braintacles-comfyui-nodes
   2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUi_PromptStylers
   2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-SDXL-EmptyLatentImage
   2.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUi_NNLatentUpscale
   2.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
   3.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Jjk-Nodes
   3.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Bmad-DirtyUndoRedo
   3.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   4.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Fans
   4.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui
   5.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   7.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyMath
   8.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
   8.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/failfast-comfyui-extensions
   9.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/facedetailer
  10.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
  12.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
  12.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui
  12.7 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-reactor-node
  30.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/rgthree-comfy
  34.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_smZNodes
  44.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
  53.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
  56.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL

**Comment by LukeOvermind** [comment]
Hi Thank you!!!!

The https://github.com/Gourieff/comfyui-reactor-node/issues/37#issuecomment-1728803735 worked!
