### ISSUE TITLE
After updating to the latest version, “ComfyUI-InstaSwap”, “comfyui-reactor-node”, two extensions have problems importing modules.

### ISSUE THREAD

**Issue by DreamLoveBetty** [Gourieff/comfyui-reactor-node#390]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Traceback (most recent call last):
  File "D:\Program\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 25, in <module>
    import scripts.reactor_version
ModuleNotFoundError: No module named 'scripts.reactor_version'

Cannot import D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'scripts.reactor_version'

### Steps to reproduce the problem

Failed to import node

### Sysinfo

win11,
edge,
4090,

### Relevant console log

```Shell
Traceback (most recent call last):
  File "D:\Program\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 25, in <module>
    import scripts.reactor_version
ModuleNotFoundError: No module named 'scripts.reactor_version'

Cannot import D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'scripts.reactor_version'
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
3D OpenPose Editor: Loaded
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### [START] ComfyUI AlekPet Nodes v1.0.16 ###
Node -> TranslateNode:  [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode Node -> ArgosTranslateNode: Node -> DeepTranslatorNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode[Loading]  DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode[Loading]

[Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> PoseNode: PoseNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Imported node: FV_NodeGroup_1
Imported node: FV_NodeGroup_1
LOADED 6 FONTS


███╗   ███╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗███████╗
████╗ ████║██╔══██╗██╔════╝██║  ██║██║████╗  ██║██╔════╝
██╔████╔██║███████║██║     ███████║██║██╔██╗ ██║█████╗
██║╚██╔╝██║██╔══██║██║     ██╔══██║██║██║╚██╗██║██╔══╝
██║ ╚═╝ ██║██║  ██║╚██████╗██║  ██║██║██║ ╚████║███████╗
╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝

██████╗ ███████╗██╗     ██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
██╔══██╗██╔════╝██║     ██║   ██║██╔════╝██║██╔═══██╗████╗  ██║██╔════╝
██║  ██║█████╗  ██║     ██║   ██║███████╗██║██║   ██║██╔██╗ ██║███████╗
██║  ██║██╔══╝  ██║     ██║   ██║╚════██║██║██║   ██║██║╚██╗██║╚════██║
██████╔╝███████╗███████╗╚██████╔╝███████║██║╚██████╔╝██║ ╚████║███████║
╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝



FizzleDorf Custom Nodes: Loaded
tqdm is already installed.
ImageReward is already installed.
Pillow的当前版本10.4.0满足要求，无需安装10.1.0版本。
huggingface_hub的当前版本0.23.4满足要求，无需安装0.20.1版本。
CUDA extension not installed.
CUDA extension not installed.
auto-gptq的当前版本0.7.1满足要求，无需安装0.7.1版本。
einops的当前版本0.8.0满足要求，无需安装0.7.0版本。
torchvision is already installed.
accelerate的当前版本0.30.0满足要求，无需安装0.25.0版本。
timm的当前版本1.0.8满足要求，无需安装0.9.16版本。
autoawq的当前版本0.2.3满足要求，无需安装0.2.3版本。
tiktoken is already installed.
attrdict is already installed.
einops的当前版本0.8.0满足要求，无需安装0.7.0版本。
sentencepiece的当前版本0.2.0满足要求，无需安装0.2.0版本。
deepseek_vl is already installed.
transformers的当前版本4.38.2满足要求，无需安装4.38.2版本。
accelerate的当前版本0.30.0满足要求，无需安装0.29.3版本。
bitsandbytes的当前版本0.43.1满足要求，无需安装0.43.1版本。
Crypto is already installed.
D:\Program\ComfyUI\custom_nodes\Comfyui_image2prompt\js
D:\Program\ComfyUI\web\extensions\fofo
# �dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
# �dzNodes: LayerStyle -> Invalid FONT directory, default to be used. check D:\Program\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini
# �dzNodes: LayerStyle -> Invalid LUT directory, default to be used. check D:\Program\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini
# �dzNodes: LayerStyle -> Find 27 LUTs in D:\Program\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# �dzNodes: LayerStyle -> Find 1 Fonts in D:\Program\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font
[tinyterraNodes] Loaded
All packages from requirements.txt are installed and up to date.
llama-cpp installed
All packages from requirements.txt are installed and up to date.
AutoGPTQ installed
# �dzNodes: WordCloud ->  find 200 fonts in C:\Windows\fonts
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.
D:\Program\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
D:\Program\ComfyUI\web\extensions\failfast-comfyui-extensions
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
[Power Noise Suite]: ��� Sup. ���
[Power Noise Suite]: Tamed 11 wild nodes.
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree] Loaded 43 magnificent nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

Searge-SDXL v4.3.1 in D:\Program\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: Importing styles from `D:\Program\ComfyUI\custom_nodes\was-node-suite-comfyui\styles.csv`.
WAS Node Suite: Styles import complete.
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: D:\Program\ffmpeg6.0\bin
WAS Node Suite: Finished. Loaded 219 nodes successfully.

        "Don't wait. The time will never be just right." - Napoleon Hill

[WAS Extras] Loading extra custom nodes...
Found `ComfyUI_ADV_CLIP_emb`. Using BLK Advanced CLIPTextEncode for Conditioning Sequencing
[WAS Extras]  Import times for extras:
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras\ConditioningBlend.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras\DebugThis.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras\VAEEncodeForInpaint.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras\VividSharpen.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras\ksampler_sequence.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras\BLVaeEncode.py

Import times for custom nodes:
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\rembg-comfyui-node
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\rembg-comfyui-node-better
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\TTP_tile_preprocessor_v5.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\style_aligned_comfy
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\LZCNodes.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\FRED_Auto_Crop_Image_SDXL_Face_Detect_v1.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-exec
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui_lora_tag_loader
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-CascadeResolutions
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui_easy_padding
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-image-round
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyUI_TJ_NormalLighting
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-LightGlue
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-tcd-scheduler
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_Pipeline_Tool
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-ScenarioPrompt
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\prompt_injection
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\Vector_Sculptor_ComfyUI
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfy-PonyNote
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_PerpWeight
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-mxToolkit
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Ollama-Describer
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_TGate
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\Lora-Training-in-Comfy
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\DJZ-Nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-RAVE
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_ImageProcessing
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_MiniCPM-V
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\sd-webui-color-enhance
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_TravelSuite_Zho
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-diffusion-cg
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-yaResolutionSelector
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\A8R8_ComfyUI_nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-fitsize
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-mape-Helpers
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-previewlatent
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Prompt-Expansion
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfy-plasma
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_restart_sampling
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\SyrianFalconNodes.py
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\FreeU_Advanced
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_densediffusion
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_VisualStylePrompting
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyUI_FrequencySeparation_RGB-HSV
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Selector-CoInput-Multilingual
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-ELLA
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Fans
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-RAVE_ATTN
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-mask-util
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-3d-photo-inpainting
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\Comfyui-StableSR
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\AuraSR-ComfyUI
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-magic-clothing
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_omost
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\antrobots-comfyUI-nodepack
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_Fictiverse
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-oms-diffusion
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-PhotoMaker
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfy_PoP
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\Chaosaiart-Nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui_jankhidiffusion
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Flowty-LDSR
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Prompt-MZ
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-AutoCropFaces
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI_Llama3_8B
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
   0.0 seconds (IMPORT FAILED): D:\Program\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\Comfy_KepListStuff
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\WAS_Extras
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-AuraSR-ZHO
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-browser
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: D:\Program\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter
```

**Comment by selim-yildirim** [comment]
Same problem

**Comment by terliu** [comment]
Same problem +1

**Comment by Gourieff** [comment]
Please, don't use ComfyUI-InstaSwap - this is fake app, the stolen code of ReActor
https://github.com/Gourieff/comfyui-reactor-node/discussions/243

**Comment by Gourieff** [comment]
I've just installed ComfyUI from the scratch alongside with ReActor nodes and everything works with no errors
If you use ReActor with fake clone called "ComfyUI-InstaSwap" it may cause the error you described

**Comment by selim-yildirim** [comment]
@Gourieff . Hi Bro.


> ComfyUI'yi ReActor düğümleriyle birlikte sıfırdan kurdum ve her şey hatasız çalışıyor. ReActor'ı "ComfyUI-InstaSwap" adlı sahte klonla kullanırsanız açıkladığınız hataya neden olabilir.

Thank you very much. The comfyui-insta-swap plugin is broken. Well, insta swap is still there. If it is stolen, shouldn't it be deleted immediately?

**Comment by DreamLoveBetty** [comment]
Thank you for your answer.It was indeed the ComfyUI-InstaSwap - this is fake app issue, after deleting it the reactor worked fine, oh sorry, I didn't know it was a fake app, I guess I can leave this issue for more people to know!

> 我刚刚从头开始安装了 ComfyUI 和 ReActor 节点，一切正常，没有错误如果您将 ReActor 与名为“ComfyUI-InstaSwap”的假克隆一起使用，可能会导致您描述的错误

**Comment by terliu** [comment]
> Thank you for your answer.It was indeed the ComfyUI-InstaSwap - this is fake app issue, after deleting it the reactor worked fine, oh sorry, I didn't know it was a fake app, I guess I can leave this issue for more people to know!
> 
> > 我刚刚从头开始安装了 ComfyUI 和 ReActor 节点，一切正常，没有错误如果您将 ReActor 与名为“ComfyUI-InstaSwap”的假克隆一起使用，可能会导致您描述的错误

确实如此，删除了ComfyUI-InstaSwap就在正常了。ComfyUI-InstaSwap平时也没有用，安装了之后比较发现和reactor一样的就没有用，但是没有删除这个节点，昨天comfyui更新后就出现这个问题了。现在解决了！

**Comment by Gourieff** [comment]
> @Gourieff . Hi Bro.
> 
> > ComfyUI'yi ReActor düğümleriyle birlikte sıfırdan kurdum ve her şey hatasız çalışıyor. ReActor'ı "ComfyUI-InstaSwap" adlı sahte klonla kullanırsanız açıkladığınız hataya neden olabilir.
> 
> Thank you very much. The comfyui-insta-swap plugin is broken. Well, insta swap is still there. If it is stolen, shouldn't it be deleted immediately?

Hello my friend, yeah, just delete insta-swap and ReActor should work ok after that

**Comment by anseltrust** [comment]
Yeah fellas, just delete the insta-swap
