### ISSUE TITLE
 No module named 'scripts.instaswap_faceswap'

### ISSUE THREAD

**Issue by ssuukk** [Gourieff/comfyui-reactor-node#412]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Since two days thes extension is failing with:

```
Traceback (most recent call last):
  File "/mnt/e/Projekty/_AI/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/e/Projekty/_AI/ComfyUI/custom_nodes/ComfyUI-InstaSwap/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/mnt/e/Projekty/_AI/ComfyUI/custom_nodes/ComfyUI-InstaSwap/nodes.py", line 14, in <module>
    from scripts.instaswap_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
ModuleNotFoundError: No module named 'scripts.instaswap_faceswap'
```

### Steps to reproduce the problem

Your workflow

### Sysinfo

Linux WSL, 3070Tx

### Relevant console log

```Shell
(most recent call last):
  File "/mnt/e/Projekty/_AI/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/e/Projekty/_AI/ComfyUI/custom_nodes/ComfyUI-InstaSwap/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/mnt/e/Projekty/_AI/ComfyUI/custom_nodes/ComfyUI-InstaSwap/nodes.py", line 14, in <module>
    from scripts.instaswap_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
ModuleNotFoundError: No module named 'scripts.instaswap_faceswap'
```

**Comment by Gourieff** [comment]
Just delete ComfyUI-InstaSwap (it's a fake and a copy of the whole ReActor's code w/o any credits) and use these original ReActor nodes

**Comment by ryanbest99** [comment]
@Gourieff Thanks bro. You saved my tons of time. 

Even though my comfyUI logs never mentioned about InstaSwap, I just deleted it and rerun the app. And finally it works. My Import Failed reason was '**comfyui-reactor-node import failed because it cannot find the module scripts.reactor_version**'. So I kept focusing on reactor_version module until I found your answer. However I just followed your advice and boom!! It works!
