### ISSUE TITLE
ImportError: DLL load failed while importing mesh_core_cython - The specified module could not be found.

### ISSUE THREAD

**Issue by W1nOfGood** [Gourieff/comfyui-reactor-node#439]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I've been trying to get this node installed correctly for the past couple of hours, but I always seem to find a new issue.
I have installed the node then I got an
`ImportError: DLL load failed while importing mesh_core_cython: The specified module could not be found.`
I have tried the [Troubleshooting ----> I.](https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting) by both installing build-tools and also installed from pre-compiled
I have build the cython using [python setup.py install](https://github.com/yfeng95/face3d/issues/79#issuecomment-907715999)

In addition of that I have tried looking into both of these which yield no result #78 #94 
![image](https://github.com/user-attachments/assets/2afb87e9-e3b5-4095-a847-369e063f9051)
![image](https://github.com/user-attachments/assets/ae638e3c-e3f2-47cd-89bc-2657c8d8a1d6)
![image](https://github.com/user-attachments/assets/2daeb401-0a9a-4843-b221-916077f3a251)

### Steps to reproduce the problem

[Your workflow](https://openart.ai/workflows/civet_fine_1/tenofas-v20---flux-with-loras-face-detailer-and-ultimate-sd-upscaler/mC53ge31vojzvo1gZrJs)

Installed everything.

### Sysinfo

```
WIN32_NT 10.0.26100.1301 (24H2)
CPU: Intel(R) Xeon(R) E5-2696 v3 (72) @ 2.29 GHz
GPU: NVIDIA GeForce RTX 3060 (11.83 GiB) [Discrete]
Memory: 8.04 GiB / 127.88 GiB (6%)
```

### Relevant console log

```Shell
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\insightface\app\mask_renderer.py", line 6, in <module>
    from ..thirdparty import face3d
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\insightface\thirdparty\face3d\__init__.py", line 5, in <module>
    from . import mesh
  File "C:\Users\Administrator\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: DLL load failed while importing mesh_core_cython: The specified module could not be found.
```

### Additional information

**Let me know if you would like any another info I'll be happy to provide!**

**Comment by beansfotos** [comment]
Same exact error.. Never works

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+ImportError%3A+DLL+load+failed+while+importing+mesh_core_cython

**Comment by W1nOfGood** [comment]
Seem like people are also having the same problem but no one ever solved it
![image](https://github.com/user-attachments/assets/981d74df-612a-468c-ac36-7b7a4d6e042d)

**Comment by mw9554** [comment]
You might need to build mesh_core_cython before you can use it. To do this, you'll usually run a script called setup.py. Find this script in your project folder and run it.
```
cd ./insightface/thirdparty/face3d/mesh/cython
python.exe setup.py build_ext --inplace
python.exe setup.py install
```

**Comment by zzzz88881** [comment]
![image](https://github.com/user-attachments/assets/a26d7031-0912-4bd6-9c20-b5b14eb147e1)
Brother, isn't this issue unresolved?
