### ISSUE TITLE
no module named google?

### ISSUE THREAD

**Issue by alenknight** [Gourieff/comfyui-reactor-node#44]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

tried running - as i was having protobuf errors - tried this fix - https://github.com/Gourieff/comfyui-reactor-node/issues/5

and now it's telling me i am missing the google module.... from when i followed the step to delete the google folder

### Steps to reproduce the problem

Your workflow
Close ComfyUI, go to the "site-packages" and see if there are any folders with names start from "~" (e.g. "~rotobuf"), delete them, do the same inside the folder "site-packages\google"
Then run CMD from ComfyUI root folder and:
python_embeded\python.exe -m pip install protobuf==3.20.3

### Sysinfo

windows 10, rtx 3090

### Relevant console log

```Shell
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-09-25 03:09:47.283366
Total VRAM 24576 MB, total RAM 32704 MB
xformers version: 0.0.21
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_management.py", line 211, in <module>
    import accelerate
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\__init__.py", line 142, in <module>
    from .megatron_lm import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Failed to execute startup-script: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\prestartup_script.py / No module named 'google'

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   2.1 seconds (PRESTARTUP FAILED): C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\main.py", line 72, in <module>
    import execution
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\AI\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 12, in <module>
    from . import clip_vision
  File "C:\AI\ComfyUI\ComfyUI\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, CLIPImageProcessor, modeling_utils
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .utils import is_tokenizers_available
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

C:\AI\ComfyUI>pause
Press any key to continue . . .
```

**Comment by Gourieff** [comment]
> and now it's telling me i am missing the google module.... from when i followed the step to delete the google folder

But you didn't have to delete the whole "google" folder, you should need to delete two "~rotobuf" folders only (if they exists): the first one - inside the "site-packages" directory and the second one - inside the "site-packages/google" directory
And then reinstall the protobuf library:
`python_embeded\python.exe -m pip install protobuf>=3.20.3`

So, just install Protobuf again, you can try the newer version (and before installation look one more time for "~rotobuf" folders just in case):
`python_embeded\python.exe -m pip install protobuf==4.24.3`
