### ISSUE TITLE
No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

### ISSUE THREAD

**Issue by GentlemanHu** [Gourieff/comfyui-reactor-node#46]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

IMPORT FAILED at ComfyUI startup.

```python
Traceback (most recent call last):
  File "/content/drive/colab_ai/ComfyUI/nodes.py", line 1742, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 3, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_swapper import swap_face
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 10, in <module>
    import insightface
  File "/usr/local/lib/python3.10/dist-packages/insightface/__init__.py", line 16, in <module>
    from . import model_zoo
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/arcface_onnx.py", line 10, in <module>
    import onnx
  File "/usr/local/lib/python3.10/dist-packages/onnx/__init__.py", line 52, in <module>
    from onnx import (
  File "/usr/local/lib/python3.10/dist-packages/onnx/checker.py", line 16, in <module>
    import onnx.defs
  File "/usr/local/lib/python3.10/dist-packages/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package
```

### Steps to reproduce the problem

Your workflow
1. git clone comfyui-reactor-node repo to custom_nodes/
2. launch ComfyUI

### Sysinfo

system info:

<img width="620" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/34559079/361d9e53-69c8-46e7-8b12-2f40bb843aee">

GPU : A4000 16GB vram

### Relevant console log

```Shell
Traceback (most recent call last):
  File "/content/drive/colab_ai/ComfyUI/nodes.py", line 1742, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 3, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_swapper import swap_face
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 10, in <module>
    import insightface
  File "/usr/local/lib/python3.10/dist-packages/insightface/__init__.py", line 16, in <module>
    from . import model_zoo
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/arcface_onnx.py", line 10, in <module>
    import onnx
  File "/usr/local/lib/python3.10/dist-packages/onnx/__init__.py", line 52, in <module>
    from onnx import (
  File "/usr/local/lib/python3.10/dist-packages/onnx/checker.py", line 16, in <module>
    import onnx.defs
  File "/usr/local/lib/python3.10/dist-packages/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package
```

### Additional information

custom_nodes

<img width="798" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/34559079/c733b945-8731-45e4-bace-065e4988c18a">

=====
python deps

```python
Package                           Version
--------------------------------- --------------------
absl-py                           1.4.0
accelerate                        0.23.0
addict                            2.4.0
agate                             1.6.0
agate-dbf                         0.2.0
agate-excel                       0.2.3
agate-sql                         0.5.2
aiohttp                           3.8.4
aiosignal                         1.3.1
albumentations                    1.3.1
antlr4-python3-runtime            4.9.3
anyio                             3.6.2
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
asttokens                         2.2.1
astunparse                        1.6.3
async-timeout                     4.0.2
attrs                             23.1.0
awscli                            1.25.91
Babel                             2.12.1
backcall                          0.2.0
basicsr                           1.4.2
beautifulsoup4                    4.11.2
bleach                            6.0.0
blis                              0.7.9
boto3                             1.24.90
botocore                          1.27.90
cached-property                   1.5.2
cachetools                        5.3.0
catalogue                         2.0.8
certifi                           2019.11.28
cffi                              1.15.1
chardet                           3.0.4
charset-normalizer                3.1.0
chex                              0.1.6
click                             8.1.3
click-completion                  0.5.2
click-didyoumean                  0.3.0
click-help-colors                 0.9.1
cloudpickle                       2.2.0
cmake                             3.27.5
colorama                          0.4.3
coloredlogs                       15.0.1
comm                              0.1.2
confection                        0.0.4
contourpy                         1.0.7
csvkit                            1.0.2
cycler                            0.11.0
cymem                             2.0.7
Cython                            0.29.32
datasets                          2.4.0
dbfread                           2.0.7
dbus-python                       1.2.16
debugpy                           1.6.6
decorator                         5.1.1
defusedxml                        0.7.1
diffusers                         0.21.2
dill                              0.3.5.1
discord-webhook                   1.3.0
dm-tree                           0.1.8
docker-pycreds                    0.4.0
docutils                          0.16
easydict                          1.10
einops                            0.6.1
entrypoints                       0.4
et-xmlfile                        1.0.1
etils                             1.0.0
executing                         1.2.0
facexlib                          0.3.0
fastjsonschema                    2.16.3
filelock                          3.9.0
filterpy                          1.4.5
flatbuffers                       23.5.26
flax                              0.6.3
fonttools                         4.39.0
frozenlist                        1.3.3
fsspec                            2023.3.0
ftfy                              6.1.1
future                            0.18.2
fvcore                            0.1.5.post20221221
gast                              0.4.0
gdown                             4.5.1
gitdb                             4.0.10
GitPython                         3.1.31
google-auth                       2.16.2
google-auth-oauthlib              1.0.0
google-pasta                      0.2.0
gql                               3.0.0a6
gradient                          2.0.6
gradient-utils                    0.5.0
graphql-core                      3.1.7
greenlet                          2.0.2
grpcio                            1.51.3
h11                               0.14.0
h5py                              3.8.0
halo                              0.0.31
httpcore                          0.17.3
httpx                             0.24.1
huggingface-hub                   0.17.3
humanfriendly                     10.0
idna                              2.8
imageio                           2.26.0
importlib-metadata                6.8.0
importlib-resources               5.12.0
insightface                       0.7.3
iopath                            0.1.10
ipykernel                         6.16.0
ipython                           8.5.0
ipython-genutils                  0.2.0
ipywidgets                        8.0.2
isodate                           0.6.0
jax                               0.4.6
jaxlib                            0.4.6+cuda11.cudnn82
jdcal                             1.0
jedi                              0.18.2
Jinja2                            3.1.2
jmespath                          1.0.1
joblib                            1.2.0
json5                             0.9.11
jsonify                           0.5
jsonschema                        4.17.3
jupyter-client                    7.3.4
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.2.0
jupyter-highlight-selected-word   0.2.0
jupyter-nbextensions-configurator 0.6.1
jupyter-server                    1.23.6
jupyter-server-mathjax            0.2.6
jupyterlab                        3.4.6
jupyterlab-git                    0.41.0
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.20.0
jupyterlab-snippets               0.4.1
jupyterlab-widgets                3.0.5
keras                             2.14.0
Keras-Preprocessing               1.1.2
kiwisolver                        1.4.4
langcodes                         3.3.0
leather                           0.3.3
libclang                          15.0.6.1
lit                               17.0.1
llvmlite                          0.41.0
lmdb                              1.4.1
log-symbols                       0.0.14
lxml                              4.5.0
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.2
marshmallow                       2.21.0
matplotlib                        3.6.1
matplotlib-inline                 0.1.6
mdurl                             0.1.2
mediapipe                         0.10.5
mistune                           2.0.5
ml-dtypes                         0.2.0
mpmath                            1.3.0
msgpack                           1.0.5
multidict                         6.0.4
multiprocess                      0.70.13
murmurhash                        1.0.9
nbclassic                         0.5.3
nbclient                          0.7.2
nbconvert                         7.2.9
nbdime                            3.1.1
nbformat                          5.7.3
nest-asyncio                      1.5.6
networkx                          3.0
nltk                              3.7
notebook                          6.5.3
notebook_shim                     0.2.2
numba                             0.58.0
numexpr                           2.8.7
numpy                             1.25.2
nvidia-cublas-cu11                11.10.3.66
nvidia-cuda-cupti-cu11            11.7.101
nvidia-cuda-nvrtc-cu11            11.7.99
nvidia-cuda-runtime-cu11          11.7.99
nvidia-cudnn-cu11                 8.5.0.96
nvidia-cufft-cu11                 10.9.0.58
nvidia-curand-cu11                10.2.10.91
nvidia-cusolver-cu11              11.4.0.1
nvidia-cusparse-cu11              11.7.4.91
nvidia-nccl-cu11                  2.14.3
nvidia-nvtx-cu11                  11.7.91
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.14.1
onnxruntime                       1.15.1
onnxruntime-gpu                   1.15.1
opencv-contrib-python             4.8.0.76
opencv-python                     4.8.0.76
opencv-python-headless            4.8.0.76
openpyxl                          3.0.3
opt-einsum                        3.3.0
optax                             0.1.4
orbax                             0.1.3
packaging                         23.0
pandas                            1.5.0
pandocfilters                     1.5.0
parsedatetime                     2.4
parso                             0.8.3
pathtools                         0.1.2
pathy                             0.10.1
pexpect                           4.8.0
pickleshare                       0.7.5
piexif                            1.1.3
Pillow                            9.2.0
pip                               23.0.1
platformdirs                      3.10.0
pooch                             1.7.0
portalocker                       2.8.2
preshed                           3.0.8
prettytable                       3.6.0
progressbar2                      4.2.0
prometheus-client                 0.9.0
promise                           2.3
prompt-toolkit                    3.0.38
protobuf                          3.20.3
psutil                            5.9.4
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyarrow                           11.0.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycparser                         2.21
pydantic                          1.9.2
Pygments                          2.14.0
PyGObject                         3.36.0
PyMatting                         1.1.8
pymongo                           3.13.0
pyparsing                         3.0.9
pypng                             0.20220715.0
pyrsistent                        0.19.3
PySocks                           1.7.1
python-apt                        2.0.1
python-dateutil                   2.8.2
python-distutils-extra            2.39
python-slugify                    4.0.0
python-telegram-bot               20.5
python-utils                      3.5.2
pytimeparse                       1.1.5
pytz                              2022.7.1
PyWavelets                        1.4.1
PyYAML                            5.4.1
pyzmq                             25.0.0
qrcode                            7.4.2
qudida                            0.0.4
regex                             2022.10.31
rembg                             2.0.50
requests                          2.28.2
requests-oauthlib                 1.3.1
requests-toolbelt                 0.10.1
requests-unixsocket               0.2.0
responses                         0.18.0
rich                              13.3.2
rsa                               4.7.2
s3transfer                        0.6.0
safetensors                       0.3.3
scikit-image                      0.19.3
scikit-learn                      1.1.2
scipy                             1.9.2
seaborn                           0.12.0
segment-anything                  1.0
Send2Trash                        1.8.0
sentence-transformers             2.2.2
sentencepiece                     0.1.97
sentry-sdk                        1.16.0
setproctitle                      1.3.2
setuptools                        67.6.0
shellingham                       1.5.0.post1
shortuuid                         1.0.11
simpleeval                        0.9.13
simplejson                        3.19.1
six                               1.14.0
smart-open                        6.3.0
smmap                             5.0.0
sniffio                           1.3.0
sounddevice                       0.4.6
soupsieve                         2.4
spacy                             3.4.1
spacy-legacy                      3.0.12
spacy-loggers                     1.0.4
spinners                          0.0.24
SQLAlchemy                        1.4.41
srsly                             2.4.6
stack-data                        0.6.2
sympy                             1.12
tabulate                          0.9.0
tb-nightly                        2.15.0a20230926
tensorboard                       2.14.0
tensorboard-data-server           0.7.1
tensorboard-plugin-wit            1.8.1
tensorflow                        2.14.0
tensorflow-estimator              2.14.0
tensorflow-io-gcs-filesystem      0.31.0
tensorstore                       0.1.33
termcolor                         2.2.0
terminado                         0.17.1
terminaltables                    3.1.10
thinc                             8.1.9
threadpoolctl                     3.1.0
tifffile                          2023.2.28
timm                              0.6.7
tinycss2                          1.2.1
tokenizers                        0.12.1
tomli                             2.0.1
toolz                             0.12.0
torch                             2.0.1
torchaudio                        2.0.2
torchsde                          0.2.6
torchvision                       0.15.2
tornado                           6.1
tqdm                              4.64.1
traitlets                         5.9.0
trampoline                        0.1.2
transformers                      4.33.2
triton                            2.0.0
typer                             0.4.2
typing_extensions                 4.5.0
ultralytics                       8.0.188
Unidecode                         1.1.1
urllib3                           1.26.15
wandb                             0.13.4
wasabi                            0.10.1
wcwidth                           0.2.6
webencodings                      0.5.1
websocket-client                  0.57.0
websockets                        11.0.3
Werkzeug                          2.2.3
wheel                             0.35.1
widgetsnbextension                4.0.5
wrapt                             1.14.1
xformers                          0.0.21
xgboost                           1.6.2
xlrd                              1.1.0
xxhash                            3.2.0
yacs                              0.1.8
yapf                              0.40.2
yarl                              1.8.2
zipp                              3.17.0
```

**Comment by kamranr123** [comment]
i faced same issue

**Comment by Gourieff** [comment]
You can read about this error in the official ONNX documentation: https://github.com/onnx/onnx#common-errors
> Note: the import onnx command does not work from the source checkout directory; in this case you'll see ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export'. Change into another directory to fix this error.

I've never faced this error, you can try to ask the ONNX team about it

But also I noticed that you have a little mess in dependencies

> onnx                              1.14.1
onnxruntime                       1.15.1
onnxruntime-gpu                   1.15.1
opencv-contrib-python             4.8.0.76
opencv-python                     4.8.0.76
opencv-python-headless            4.8.0.76

ORT won't work like this
You have to use only one of onnxruntime libraries, not both of them
The current version of ReActor Node uses onnxruntime and cannot work with onnxruntime-gpu
The same thing with opencv-python

So, to fix it you need to do the following:
`pip uninstall -y onnxruntime onnxruntime-gpu opencv-python opencv-contrib-python opencv-python-headless`
`pip install onnxruntime==1.15.1`
`pip install opencv-python==4.7.0.72`

**Comment by roop03988** [comment]
> You can read about this error in the official ONNX documentation: https://github.com/onnx/onnx#common-errors
> 
> > Note: the import onnx command does not work from the source checkout directory; in this case you'll see ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export'. Change into another directory to fix this error.
> 
> I've never faced this error, you can try to ask the ONNX team about it
> 
> But also I noticed that you have a little mess in dependencies
> 
> > onnx                              1.14.1
> > onnxruntime                       1.15.1
> > onnxruntime-gpu                   1.15.1
> > opencv-contrib-python             4.8.0.76
> > opencv-python                     4.8.0.76
> > opencv-python-headless            4.8.0.76
> 
> ORT won't work like this You have to use only one of onnxruntime libraries, not both of them The current version of ReActor Node uses onnxruntime and cannot work with onnxruntime-gpu The same thing with opencv-python
> 
> So, to fix it you need to do the following: `pip uninstall -y onnxruntime onnxruntime-gpu opencv-python opencv-contrib-python opencv-python-headless` `pip install onnxruntime==1.15.1` `pip install opencv-python==4.7.0.72`

Having the same issue and tried this solution but still the same error..

**Comment by Gourieff** [comment]
> I have the same env cloned in SD webui auto1111 with reactor force and it's working there

Yes, because A1111 works with virtual env or embedded enclosure (you can try to install ComfyUI there and install this node)
ComfyUI also works pretty fine with embedded python enclosure or with venv
But if to use ComfyUI (or any other WebUI) directly with OS-installed python's dependencies there can be issues with such libraries as ONNX, ORT, Insightface

> `File "/usr/local/lib/python3.10/dist-packages/insightface/__init__.py", line 16, in <module>`
`File "/usr/local/lib/python3.10/dist-packages/onnx/__init__.py", line 52, in <module>`

I don't know what the Colab for ComfyUI you use guys, but it installs all the the deps directly inside the OS but not in a separate enclosure
It's not right

You have to use venv, conda or a simple separate embedded python's enclosure - even if you organize your build with a Docker container

**Comment by roop03988** [comment]
Oh, weird, I use 2 separate conda envs for my auto1111 and comfyui, here's my stack trace for comfyui (local only)

Traceback (most recent call last):
  File "/media/ian/My Book/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/ian/My Book/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/media/ian/My Book/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 3, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "/media/ian/My Book/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_swapper import swap_face
  File "/media/ian/My Book/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 10, in <module>
    import insightface
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/insightface/__init__.py", line 16, in <module>
    from . import model_zoo
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/insightface/model_zoo/__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/insightface/model_zoo/arcface_onnx.py", line 10, in <module>
    import onnx
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/onnx/__init__.py", line 52, in <module>
    from onnx import (
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/onnx/checker.py", line 16, in <module>
    import onnx.defs
  File "/home/ian/miniconda3/envs/comfy/lib/python3.10/site-packages/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

**Comment by roop03988** [comment]
This seems related:

https://github.com/melMass/comfy_mtb/issues/83

**Comment by Gourieff** [comment]
Very strange... I've run out of variants how to resolve it

So guys try to ask the ONNX team about this error because it's noted in the ONNX official documentation:
https://github.com/onnx/onnx#common-errors

Or you can also ask the Insightface team, because the Insightface library is causing this error

**Comment by zae-park** [comment]
face same issue.

**Comment by Gourieff** [comment]
@zae-park I think the probable cause is disclosed here https://github.com/melMass/comfy_mtb/issues/87

**Comment by cian0** [comment]
Btw for some reason this finally worked for me when I uninstalled onnx as described here, then reinstalled onnx, updated onnxruntime to the latest version (not 1.15.1). I also didn't touch opencv and didn't install onnxruntime-gpu

> You can read about this error in the official ONNX documentation: https://github.com/onnx/onnx#common-errors
> 
> > Note: the import onnx command does not work from the source checkout directory; in this case you'll see ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export'. Change into another directory to fix this error.
> 
> I've never faced this error, you can try to ask the ONNX team about it
> 
> But also I noticed that you have a little mess in dependencies
> 
> > onnx                              1.14.1
> > onnxruntime                       1.15.1
> > onnxruntime-gpu                   1.15.1
> > opencv-contrib-python             4.8.0.76
> > opencv-python                     4.8.0.76
> > opencv-python-headless            4.8.0.76
> 
> ORT won't work like this You have to use only one of onnxruntime libraries, not both of them The current version of ReActor Node uses onnxruntime and cannot work with onnxruntime-gpu The same thing with opencv-python
> 
> So, to fix it you need to do the following: `pip uninstall -y onnxruntime onnxruntime-gpu opencv-python opencv-contrib-python opencv-python-headless` `pip install onnxruntime==1.15.1` `pip install opencv-python==4.7.0.72`

**Comment by cian0** [comment]
Is it possible to use GPU?

**Comment by Gourieff** [comment]
> Is it possible to use GPU?

https://github.com/Gourieff/comfyui-reactor-node/discussions/61#discussioncomment-7248512

**Comment by zae-park** [comment]
In my case, after installing **FaceSwapNode**, the onnx import error disappeared and reactor node worked fine.
The link is [here](https://github.com/imb101/ComfyUI-FaceSwap), and I should be helpful.

**Comment by murphylanga** [comment]
I had several failed attempts to get the reactor node to run after the Cuda12.3 update.
Only this post achieved the goal.
After installing the FaceSwapNode, the Reactor node worked again.

**Comment by Gourieff** [comment]
Perhaps when you installed FaceSwapNode - ORT was reinstalled to the appropriate version

**Comment by Yimusilang** [comment]
Really appreciate!!!  👍 
this problem has been bothering me for several days .


> In my case, after enabling [**FaceSwapNode**](https://github.com/imb101/ComfyUI-FaceSwap), the onnx import error disappeared and reactor node worked fine. Perhaps including the **FaceSwapNode** when disabling unused nodes was the problem, because I think **Reactor-node** can replace**FaceSwapNode**. I hope it should be helpful.
