### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

### ISSUE THREAD

**Issue by 705284036** [Gourieff/comfyui-reactor-node#463]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

![屏幕截图 2024-10-19 160716](https://github.com/user-attachments/assets/329cae2b-2e84-4a77-8dd4-f8e805be2600)

### Steps to reproduce the problem

![屏幕截图 2024-10-19 160646](https://github.com/user-attachments/assets/aa7c5b76-5c65-45af-bafe-6a34d701ee0f)

### Sysinfo

win 11  谷歌浏览器  3060ti 

### Relevant console log

```Shell
Traceback (most recent call last):
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node\install.py", line 62, in <module>
    download(model_url, model_path, model_name)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node\install.py", line 53, in download
    request = urllib.request.urlopen(url)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "E:\AI\comfyui\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

--------
[程序异常退出，退出代码为 1 (0x00000001)]
```

**Comment by mx5nabcd** [comment]
I solved it by adding the following code to the "comfyui-reactor-node\install.py" file.

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

There could be a better way.

**Comment by rasen0** [comment]
If it is a Windows system, you can try to configure the environment variable like this: set SSL_CERT_FILE=%APPDATA%\Python\Python39\site-packages\certifi\cacert.pem. The reason is that Python fails to locate the CA certificate.

**Comment by luongbaohoanggia19977** [comment]
> If it is a Windows system, you can try to configure the environment variable like this: set SSL_CERT_FILE=%APPDATA%\Python\Python39\site-packages\certifi\cacert.pem. The reason is that Python fails to locate the CA certificate.

can you explain more, i'm in the same issue, thanksss !

**Comment by Sethchen001** [comment]
This problem has troubled me for too long. I checked all the required dependency version files and there were no problems, but the startup still reported this error

**Comment by Sethchen001** [comment]
> cacert.pem

The environment variables of this file have been set, but the same error is still displayed. Is there something wrong with the cacert.pem certificate file?

**Comment by Sethchen001** [comment]
> 如果是Windows系统，可以尝试这样配置环境变量：set SSL_CERT_FILE=%APPDATA%\Python\Python39\site-packages\certifi\cacert.pem。原因是Python无法找到CA证书。

The environment variables of this file have been set, but the same error is still displayed. Is there something wrong with the cacert.pem certificate file?

**Comment by NKZDDD** [comment]
Where to find certifi's certificate:

Run the following command at the command prompt:

python -c "import certifi;  print(certifi.where())" prints your certificate path

Finally set in the environment variable

![image](https://github.com/user-attachments/assets/1b279704-7015-4dbb-b1de-702819532e2d)

After setting, restart and normal download will begin

**Comment by Idmon** [comment]
I am running on MacOS Sequoia 15.1 and ran across the same problem.

What helped me was running this command:
`open "/Applications/Python 3.x/Install Certificates.command"`

Change the `x` to your python version

**Comment by quryq** [comment]
> Where to find certifi's certificate:
> 
> Run the following command at the command prompt:
> 
> python -c "import certifi; print(certifi.where())" prints your certificate path
> 
> Finally set in the environment variable
> 
> ![image](https://private-user-images.githubusercontent.com/66771920/386029913-1b279704-7015-4dbb-b1de-702819532e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDEzODgsIm5iZiI6MTczMjEwMTA4OCwicGF0aCI6Ii82Njc3MTkyMC8zODYwMjk5MTMtMWIyNzk3MDQtNzAxNS00ZGJiLWIxZGUtNzAyODE5NTMyZTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDExMTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlY2VjMWI0MTM4NzRlMzRhNTA2NjQzNDhkOTY3YWVkMzBlMjJiY2NkNzUwYmRmZDIzODYwZTFhN2VmM2M0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LsZJ6SLlilBVdvL4WKcYNdsrUdpLfIsDDM-cUvoRr4o)
> 
> After setting, restart and normal download will begin

It work! thanks!!!

**Comment by Daliuq** [comment]
如果你挂了不好的代理，你要把
`import ssl
ssl._create_default_https_context = ssl._create_unverified_context`
加到./reactor_utils.py 下
