### ISSUE TITLE
Unexpected EOF error when running face restoration algorithm

### ISSUE THREAD

**Issue by snowwaft** [Gourieff/comfyui-reactor-node#466]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I encountered an issue when configuring the Reactor node in ComfyUI. When I set a restoration model, such as GFPGANv1.4.pth, I get the following error: "unexpected EOF, expected 280734 more bytes. The file might be corrupted."

I have tried re-downloading these models and verified the hash values, but the issue persists. I have also searched through all resolved issues but couldn't find a specific solution.

### Steps to reproduce the problem

Here is an example workflow that consistently triggers this exception:
[workflow.json](https://github.com/user-attachments/files/17448308/workflow.json)

### Sysinfo

OS: Windows 11
GPU: 4070
CUDA version: 12.4
PyTorch version: 2.5.0+cu124
ComfyUI Revision: 2771 [518c0dc2] | Released on '2024-10-18'

### Relevant console log

```Shell
[ReActor] 11:13:42 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 11:13:42 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 11:13:42 - STATUS - Using Hashed Target Face(s) Model...
[ReActor] 11:13:42 - STATUS - Swapping...
[ReActor] 11:13:43 - STATUS - --Done!--
[ReActor] 11:13:43 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
!!! Exception during processing !!!
unexpected EOF, expected 280734 more bytes. The file might be corrupted.

Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 379, in execute
    result = reactor.restore_face(self,result,face_restore_model,face_restore_visibility,codeformer_weight,facedetection)
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 221, in restore_face
    self.face_helper = FaceRestoreHelper(1, face_size=faceSize, crop_ratio=(1, 1), det_model=facedetection, save_ext='png', use_parse=True, device=device)
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\r_facelib\utils\face_restoration_helper.py", line 109, in __init__
    self.face_parse = init_parsing_model(model_name='parsenet', device=self.device)
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\r_facelib\parsing\__init__.py", line 19, in init_parsing_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\ComfyUI\venv\lib\site-packages\torch\serialization.py", line 1384, in load
    return _legacy_load(
  File "C:\ComfyUI\venv\lib\site-packages\torch\serialization.py", line 1647, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 280734 more bytes. The file might be corrupted.
```

**Comment by snowwaft** [comment]
the log is:
[ReActor] 11:13:42 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 11:13:42 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 11:13:42 - STATUS - Using Hashed Target Face(s) Model...
[ReActor] 11:13:42 - STATUS - Swapping...
[ReActor] 11:13:43 - STATUS - --Done!--
[ReActor] 11:13:43 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
!!! Exception during processing !!! unexpected EOF, expected 280734 more bytes. The file might be corrupted.
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 379, in execute
    result = reactor.restore_face(self,result,face_restore_model,face_restore_visibility,codeformer_weight,facedetection)
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 221, in restore_face
    self.face_helper = FaceRestoreHelper(1, face_size=faceSize, crop_ratio=(1, 1), det_model=facedetection, save_ext='png', use_parse=True, device=device)
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\r_facelib\utils\face_restoration_helper.py", line 109, in __init__
    self.face_parse = init_parsing_model(model_name='parsenet', device=self.device)
  File "C:\ComfyUI\custom_nodes\comfyui-reactor-node\r_facelib\parsing\__init__.py", line 19, in init_parsing_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\ComfyUI\venv\lib\site-packages\torch\serialization.py", line 1384, in load
    return _legacy_load(
  File "C:\ComfyUI\venv\lib\site-packages\torch\serialization.py", line 1647, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 280734 more bytes. The file might be corrupted.

**Comment by snowwaft** [comment]
After further investigation, I discovered that the issue was caused by a corrupted file: C:\ComfyUI\models\facedetection\parsing_parsenet.pth. After deleting this file and re-downloading it, the issue was resolved.
