### ISSUE TITLE
Precompiled insightface wheel not compatible with Portable ComfyUI v0.2.4

### ISSUE THREAD

**Issue by Quaggles** [Gourieff/comfyui-reactor-node#471]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The new [ComfyUI v0.2.4 portable release](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.2.4) uses Python 1.12, CUDA 12.4, pytorch 2.5 and numpy v2.1.2. When I install the Python 1.12 wheel of insightface (https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) I get the error: 
`Cannot import C:\comfy\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

If I install cython and manually copy over the `include` and `libs` folders from `C:\Users\<User>\AppData\Local\Programs\Python\Python312` to `comfy\python_embeded` and run a regular `pip install insightface` it compiles and works but for many end users compiling it themselves will be too complicated.

Is the error occuring because the wheel was compiled with numpy 1.x.x? If so since the official ComfyUI release has moved to numpy v2 would you be able to provide a compatible wheel for that version?

### Steps to reproduce the problem

1. Download and extract the ComfyUI v0.2.4 release, https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.2.4
2. Install the precompiled insightface wheel with `.\python_embeded\python.exe -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl`
3. Clone ReActor into `ComfyUI\custom_nodes`
4. Run `comfyui-reactor-node\install.bat`
5. Run ComfyUI and see error

### Sysinfo

Windows 11
Chrome
RTX 2080ti
No other custom nodes installed

### Relevant console log

```Shell
C:\comfy>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 11264 MB, total RAM 32683 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\comfy\ComfyUI\web
C:\comfy\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "C:\comfy\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\comfy\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\comfy\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "C:\comfy\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\comfy\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\comfy\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\comfy\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\comfy\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface\\thirdparty\\face3d\\mesh\\cython\\mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Cannot import C:\comfy\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Import times for custom nodes:
   0.0 seconds: C:\comfy\ComfyUI\custom_nodes\websocket_image_save.py
   0.6 seconds (IMPORT FAILED): C:\comfy\ComfyUI\custom_nodes\comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by Raees760** [comment]
Having same issue and idk how to fix it

**Comment by embeddedDevices** [comment]
Hello, 
having same issue, perfect describtion of the problem.

**Comment by patrice74** [comment]
Good morning,
To work around the problem:
In your "ComfyUI_windows_portable\python_embeded" directory, run the command: python.exe -m pip install numpy==1.26.4
It works for me.

**Comment by embeddedDevices** [comment]
> Good morning, To work around the problem: In your "ComfyUI_windows_portable\python_embeded" directory, run the command: python.exe -m pip install numpy==1.26.4 It works for me.

Thank you so much. That worked fine.
