### ISSUE TITLE
After installation of ReActor Node, comfyUI just stops before it starts.

### ISSUE THREAD

**Issue by Cosmos-Shin** [Gourieff/comfyui-reactor-node#472]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I'm using StabilityMatrix.
I installed ReActor Node in ComfyUI-Manager.
When I restart, it stops during preparing course.
If I remove the folder of 'comfyui-reactor-node', ComfyUI starts well again.
All library versions are satisfied in requirements.txt.
I can't find what is the problem.
Could anyone help me, please?

### Steps to reproduce the problem

I installed insightfase well. (0.7.3)
It works well when I use 'instant id'.
I loaded the workflow in which there is ReActor Node.
I installed ReActor Node thru ComfyUI-Manager.
(Install missing node function)

### Sysinfo

OS : Windows 11 Home
browser : Chrome
GPU : RTX 4090
CPU : intel i9-14900K
RAM : 64G
I'm using StabilityMatrix

### Relevant console log

```Shell
Restarting... [Legacy Mode]


[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-27 16:20:36.692261
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: D:\StabilityMatrix\Data\Packages\ComfyUI
** Log path: D:\StabilityMatrix\Data\Packages\ComfyUI\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

[SKIP] Downgrading pip package isn't allowed: albumentations (cur=1.4.20)
[SKIP] Downgrading pip package isn't allowed: onnx (cur=1.17.0)
[SKIP] Downgrading pip package isn't allowed: opencv-python (cur=4.10.0.84)

## ComfyUI-Manager: EXECUTE => ['D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'segment_anything']

## Execute install/(de)activation script for 'D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node'
 
## ComfyUI-Manager: EXECUTE => ['D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py']

## Execute install/(de)activation script for 'D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node'
 CUDA 12.4
 Ok

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   3.9 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65299 MB
pytorch version: 2.5.0+cu124
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\StabilityMatrix\Data\Packages\ComfyUI\web
Adding extra search path checkpoints D:\StabilityMatrix\Data\Models\StableDiffusion
Adding extra search path vae D:\StabilityMatrix\Data\Models\VAE
Adding extra search path loras D:\StabilityMatrix\Data\Models\Lora
Adding extra search path loras D:\StabilityMatrix\Data\Models\LyCORIS
Adding extra search path upscale_models D:\StabilityMatrix\Data\Models\ESRGAN
Adding extra search path upscale_models D:\StabilityMatrix\Data\Models\RealESRGAN
Adding extra search path upscale_models D:\StabilityMatrix\Data\Models\SwinIR
Adding extra search path embeddings D:\StabilityMatrix\Data\Models\TextualInversion
Adding extra search path hypernetworks D:\StabilityMatrix\Data\Models\Hypernetwork
Adding extra search path controlnet D:\StabilityMatrix\Data\Models\ControlNet
Adding extra search path controlnet D:\StabilityMatrix\Data\Models\T2IAdapter
Adding extra search path clip D:\StabilityMatrix\Data\Models\CLIP
Adding extra search path clip_vision D:\StabilityMatrix\Data\Models\InvokeClipVision
Adding extra search path diffusers D:\StabilityMatrix\Data\Models\Diffusers
Adding extra search path gligen D:\StabilityMatrix\Data\Models\GLIGEN
Adding extra search path vae_approx D:\StabilityMatrix\Data\Models\ApproxVAE
Adding extra search path ipadapter D:\StabilityMatrix\Data\Models\IpAdapter
Adding extra search path ipadapter D:\StabilityMatrix\Data\Models\InvokeIpAdapters15
Adding extra search path ipadapter D:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion D:\StabilityMatrix\Data\Models\PromptExpansion
Adding extra search path ultralytics D:\StabilityMatrix\Data\Models\Ultralytics
Adding extra search path ultralytics_bbox D:\StabilityMatrix\Data\Models\Ultralytics\bbox
Adding extra search path ultralytics_segm D:\StabilityMatrix\Data\Models\Ultralytics\segm
Adding extra search path sams D:\StabilityMatrix\Data\Models\Sams
Adding extra search path diffusion_models D:\StabilityMatrix\Data\Models\unet
D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Adding D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V7.10.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
### Loading: ComfyUI-Impact-Pack (V7.10.3)
[Impact Pack] Wildcards loading done.
Loaded ImpactPack nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.19.0
[Crystools INFO] CPU: Intel(R) Core(TM) i9-14900K - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 561.09
### Loading: ComfyUI-Impact-Pack (V7.10.3)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.5.1)
Total VRAM 24564 MB, total RAM 65299 MB
pytorch version: 2.5.0+cu124
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2785 [52810907] | Released on '2024-10-24'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
--------------
 ### Mixlab Nodes: Loaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: D:\StabilityMatrix\Data\Packages\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: D:\StabilityMatrix\Data\Packages\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: D:\StabilityMatrix\Data\Packages\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available False
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 -------------- 
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.5.0+cu124
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
3D OpenPose Editor: Loaded
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki

=========※※※======※※※======※※※========※※※======※※※=====※※※=====※※※========
=========※※※======※※※======※※※========※※※======※※※=====※※※=====※※※========
=========※※※======※※※======※※※========※※※======※※※=====※※※=====※※※========
-> It stops here!!! Just stop. Nothing happens afterwards.

When I delete the folder of 'comfyui-reactor-node', ComfyUI starts well again.
And below is the log.
There are some error messages, but I think it's not related with this problem. because it's showed always and comfyUI works fine.
=========※※※======※※※======※※※========※※※======※※※=====※※※=====※※※========
=========※※※======※※※======※※※========※※※======※※※=====※※※=====※※※========
=========※※※======※※※======※※※========※※※======※※※=====※※※=====※※※========

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-27 16:46:08.626482
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: D:\StabilityMatrix\Data\Packages\ComfyUI
** Log path: D:\StabilityMatrix\Data\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.9 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65299 MB
pytorch version: 2.5.0+cu124
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\StabilityMatrix\Data\Packages\ComfyUI\web
Adding extra search path checkpoints D:\StabilityMatrix\Data\Models\StableDiffusion
Adding extra search path vae D:\StabilityMatrix\Data\Models\VAE
Adding extra search path loras D:\StabilityMatrix\Data\Models\Lora
Adding extra search path loras D:\StabilityMatrix\Data\Models\LyCORIS
Adding extra search path upscale_models D:\StabilityMatrix\Data\Models\ESRGAN
Adding extra search path upscale_models D:\StabilityMatrix\Data\Models\RealESRGAN
Adding extra search path upscale_models D:\StabilityMatrix\Data\Models\SwinIR
Adding extra search path embeddings D:\StabilityMatrix\Data\Models\TextualInversion
Adding extra search path hypernetworks D:\StabilityMatrix\Data\Models\Hypernetwork
Adding extra search path controlnet D:\StabilityMatrix\Data\Models\ControlNet
Adding extra search path controlnet D:\StabilityMatrix\Data\Models\T2IAdapter
Adding extra search path clip D:\StabilityMatrix\Data\Models\CLIP
Adding extra search path clip_vision D:\StabilityMatrix\Data\Models\InvokeClipVision
Adding extra search path diffusers D:\StabilityMatrix\Data\Models\Diffusers
Adding extra search path gligen D:\StabilityMatrix\Data\Models\GLIGEN
Adding extra search path vae_approx D:\StabilityMatrix\Data\Models\ApproxVAE
Adding extra search path ipadapter D:\StabilityMatrix\Data\Models\IpAdapter
Adding extra search path ipadapter D:\StabilityMatrix\Data\Models\InvokeIpAdapters15
Adding extra search path ipadapter D:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion D:\StabilityMatrix\Data\Models\PromptExpansion
Adding extra search path ultralytics D:\StabilityMatrix\Data\Models\Ultralytics
Adding extra search path ultralytics_bbox D:\StabilityMatrix\Data\Models\Ultralytics\bbox
Adding extra search path ultralytics_segm D:\StabilityMatrix\Data\Models\Ultralytics\segm
Adding extra search path sams D:\StabilityMatrix\Data\Models\Sams
Adding extra search path diffusion_models D:\StabilityMatrix\Data\Models\unet
D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Adding D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V7.10.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
### Loading: ComfyUI-Impact-Pack (V7.10.3)
Loaded ImpactPack nodes from D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.19.0
[Crystools INFO] CPU: Intel(R) Core(TM) i9-14900K - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 561.09
### Loading: ComfyUI-Impact-Pack (V7.10.3)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.5.1)
Total VRAM 24564 MB, total RAM 65299 MB
pytorch version: 2.5.0+cu124
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2785 [52810907] | Released on '2024-10-24'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
--------------
 ### Mixlab Nodes: Loaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: D:\StabilityMatrix\Data\Packages\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: D:\StabilityMatrix\Data\Packages\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: D:\StabilityMatrix\Data\Packages\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available False
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 -------------- 
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
3D OpenPose Editor: Loaded
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)

[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree-comfy] Loaded 42 epic nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

	"Art is the most beautiful of all lies." - Claude Debussy


Import times for custom nodes:
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-openpose-editor
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-VisualArea-Nodes
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-portrait-master
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_segment_anything
   0.2 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.2 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools
   0.3 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Gemini_Flash
   0.4 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.6 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-art-venture
   1.1 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.6 seconds: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\input\\IF_AI\\presets\\agents'

[comfy_mtb] | INFO -> Found multiple match, we will pick the last D:\StabilityMatrix\Data\Models\SwinIR
['D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\models\\upscale_models', 'D:\\StabilityMatrix\\Data\\Models\\ESRGAN', 'D:\\StabilityMatrix\\Data\\Models\\RealESRGAN', 'D:\\StabilityMatrix\\Data\\Models\\SwinIR']
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'D:\\StabilityMatrix\\Data\\Packages\\ComfyUI\\input\\IF_AI\\presets\\agents'

data_path:  D:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
```

**Comment by Cosmos-Shin** [comment]
I removed a custom node 'ComfyUI_Gemini_Flash'.
Then comfyUI starts well and ReActor Node and Instant ID works well, too.
I think ReActor Node conflicts with 'ComfyUI_Gemini_Flash' node.

**Comment by freddogitub** [comment]
Hi, i removed 'ComfyUI-Detail-Daemon' and 'comfyui_dagthomas' and deleted the '__pycache__' then comfyui starts well and Reactor node works well.
If it can help.

**Comment by VeryElusiveMoose** [comment]
> Same Problem. Removed Plugin "comfyui_LLM_party". But this plugin runs when i remove ReActor with no problems.

Saved me after hours of digging - thank you!
