### ISSUE TITLE
 assert 'detection' in self.models AssertionError

### ISSUE THREAD

**Issue by Troyificus** [Gourieff/comfyui-reactor-node#473]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Reactor worked with no issues up until a few weeks ago. Haven't used it for a while, tried it yesterday and it fails every time. I've updated Comfy latest version, removed Reactor entirely and installed it via both Comfy Manager and git clone. Torch is on latest version as well. I see someone else reported a similar issue in April but the outcome of that one is unclear.

### Steps to reproduce the problem

Your workflow
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":4,"last_link_id":3,"nodes":[{"id":2,"type":"LoadImage","pos":{"0":342,"1":-118},"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["448800638_1137153660832851_3946545270902387364_n.jpg","image"]},{"id":3,"type":"LoadImage","pos":{"0":349,"1":244},"size":[315,314],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Screenshot 2024-06-21 150854.png","image"]},{"id":4,"type":"SaveImage","pos":{"0":1097,"1":84},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":3}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":1,"type":"ReActorFaceSwap","pos":{"0":731,"1":95},"size":{"0":315,"1":358},"flags":{},"order":2,"mode":0,"inputs":[{"name":"input_image","type":"IMAGE","link":1},{"name":"source_image","type":"IMAGE","link":2,"shape":7},{"name":"face_model","type":"FACE_MODEL","link":null,"shape":7},{"name":"face_boost","type":"FACE_BOOST","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[3],"slot_index":0},{"name":"FACE_MODEL","type":"FACE_MODEL","links":null}],"properties":{"Node name for S&R":"ReActorFaceSwap"},"widgets_values":[true,"1k3d68.onnx","retinaface_resnet50","GFPGANv1.4.pth",1,0.5,"no","no","0","0",1]}],"links":[[1,2,0,1,0,"IMAGE"],[2,3,0,1,1,"IMAGE"],[3,1,0,4,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[-49,38]}},"version":0.4}

### Sysinfo

Windows 10, Firefox, RTX 4060Ti 16GB, 

### Relevant console log

```Shell
# ComfyUI Error Report
## Error Details
- **Node Type:** ReActorFaceSwap
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace

  File "C:\Users\Trism\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\Trism\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 350, in execute
    script.process(

  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 101, in process
    result = swap_face(
             ^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 246, in swap_face
    source_faces = analyze_faces(source_img)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 151, in analyze_faces
    face_analyser = getAnalysisModel(det_size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 81, in getAnalysisModel
    ANALYSIS_MODEL = insightface.app.FaceAnalysis(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_patcher.py", line 59, in patched_faceanalysis_init
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.4-9-gc3ffbae
- **Arguments:** main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175019520
  - **VRAM Free:** 15964569600
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-27 13:56:12,872 - root - INFO - Total VRAM 16379 MB, total RAM 65480 MB
2024-10-27 13:56:12,872 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-27 13:56:12,875 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-27 13:56:12,875 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-10-27 13:56:14,444 - root - INFO - Using pytorch cross attention
2024-10-27 13:56:16,221 - root - INFO - [Prompt Server] web root: C:\Users\Trism\ComfyUI\web
2024-10-27 13:56:16,223 - root - INFO - Adding extra search path checkpoints path/to/stable-diffusion-webui/models/Stable-diffusion
2024-10-27 13:56:16,223 - root - INFO - Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
2024-10-27 13:56:16,223 - root - INFO - Adding extra search path vae path/to/stable-diffusion-webui/models/VAE
2024-10-27 13:56:16,223 - root - INFO - Adding extra search path loras path/to/stable-diffusion-webui/models/Lora
2024-10-27 13:56:16,223 - root - INFO - Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
2024-10-27 13:56:16,223 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
2024-10-27 13:56:16,224 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
2024-10-27 13:56:16,225 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
2024-10-27 13:56:16,225 - root - INFO - Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
2024-10-27 13:56:16,225 - root - INFO - Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
2024-10-27 13:56:16,226 - root - INFO - Adding extra search path controlnet path/to/stable-diffusion-webui/models/ControlNet
2024-10-27 13:56:16,226 - root - INFO - Adding extra search path ipadapter C:\Users\Trism\ComfyUI\models\ipadapter
2024-10-27 13:56:19,312 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-27 13:56:19,328 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-10-27 13:56:19,330 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-27 13:56:19,501 - dinov2 - WARNING - xFormers not available
2024-10-27 13:56:19,504 - dinov2 - WARNING - xFormers not available
2024-10-27 13:56:20,278 - root - INFO - Total VRAM 16379 MB, total RAM 65480 MB
2024-10-27 13:56:20,278 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-27 13:56:20,280 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-27 13:56:20,280 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-10-27 13:56:27,854 - root - INFO - 
Import times for custom nodes:
2024-10-27 13:56:27,854 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\rembg-comfyui-node
2024-10-27 13:56:27,855 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\sdxl_utility.py
2024-10-27 13:56:27,855 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Image-Selector
2024-10-27 13:56:27,855 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-27 13:56:27,856 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\canvas_tab
2024-10-27 13:56:27,856 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\SDXLAspectRatio.py
2024-10-27 13:56:27,856 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-CascadeResolutions
2024-10-27 13:56:27,857 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-10-27 13:56:27,858 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\hakkun_nodes.py
2024-10-27 13:56:27,858 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-GlifNodes
2024-10-27 13:56:27,859 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler
2024-10-27 13:56:27,859 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-27 13:56:27,859 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-string-util
2024-10-27 13:56:27,860 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-10-27 13:56:27,860 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-mxToolkit
2024-10-27 13:56:27,860 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-27 13:56:27,861 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\AuraSR-ComfyUI
2024-10-27 13:56:27,861 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyLiterals
2024-10-27 13:56:27,861 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
2024-10-27 13:56:27,862 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-27 13:56:27,862 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
2024-10-27 13:56:27,862 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-SuperBeasts
2024-10-27 13:56:27,863 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-10-27 13:56:27,863 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-10-27 13:56:27,863 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-portrait-master
2024-10-27 13:56:27,864 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-10-27 13:56:27,864 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-prompt-composer
2024-10-27 13:56:27,864 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\DJZ-Nodes
2024-10-27 13:56:27,865 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\mikey_nodes
2024-10-27 13:56:27,865 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-various
2024-10-27 13:56:27,865 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-27 13:56:27,866 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfy-image-saver
2024-10-27 13:56:27,866 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-27 13:56:27,866 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
2024-10-27 13:56:27,867 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
2024-10-27 13:56:27,867 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-27 13:56:27,867 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-10-27 13:56:27,868 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-27 13:56:27,868 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-27 13:56:27,868 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-10-27 13:56:27,869 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData
2024-10-27 13:56:27,869 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-DirGir
2024-10-27 13:56:27,869 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension
2024-10-27 13:56:27,870 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\All-IN-ONE-style
2024-10-27 13:56:27,870 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\rgthree-comfy
2024-10-27 13:56:27,870 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\x-flux-comfyui
2024-10-27 13:56:27,871 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-JakeUpgrade
2024-10-27 13:56:27,871 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-PixelArt-Detector
2024-10-27 13:56:27,871 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-27 13:56:27,872 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-27 13:56:27,872 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-10-27 13:56:27,872 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-27 13:56:27,873 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\facerestore_cf
2024-10-27 13:56:27,875 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-10-27 13:56:27,875 - root - INFO -    0.0 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-dream-project
2024-10-27 13:56:27,876 - root - INFO -    0.1 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-27 13:56:27,876 - root - INFO -    0.1 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-27 13:56:27,876 - root - INFO -    0.1 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-prompt-reader-node
2024-10-27 13:56:27,877 - root - INFO -    0.1 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-27 13:56:27,877 - root - INFO -    0.1 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node
2024-10-27 13:56:27,877 - root - INFO -    0.1 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-27 13:56:27,878 - root - INFO -    0.2 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-tensorops
2024-10-27 13:56:27,878 - root - INFO -    0.2 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-27 13:56:27,878 - root - INFO -    0.2 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-27 13:56:27,879 - root - INFO -    0.3 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui_segment_anything
2024-10-27 13:56:27,879 - root - INFO -    0.3 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfy_mtb
2024-10-27 13:56:27,879 - root - INFO -    0.4 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-OllamaGemini
2024-10-27 13:56:27,880 - root - INFO -    0.5 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-27 13:56:27,880 - root - INFO -    0.5 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration
2024-10-27 13:56:27,880 - root - INFO -    0.5 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Manager-main
2024-10-27 13:56:27,881 - root - INFO -    0.5 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-10-27 13:56:27,881 - root - INFO -    0.7 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-liveportrait
2024-10-27 13:56:27,881 - root - INFO -    0.7 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-10-27 13:56:27,882 - root - INFO -    0.8 seconds: C:\Users\Trism\ComfyUI\custom_nodes\comfyui-propost
2024-10-27 13:56:27,882 - root - INFO -    0.9 seconds: C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI-Allor
2024-10-27 13:56:27,882 - root - INFO -    2.9 seconds: C:\Users\Trism\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-27 13:56:27,883 - root - INFO - 
2024-10-27 13:56:27,902 - root - INFO - Starting server

2024-10-27 13:56:27,902 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-27 13:56:49,275 - root - INFO - got prompt
2024-10-27 13:56:49,665 - root - ERROR - !!! Exception during processing !!! 
2024-10-27 13:56:49,667 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Trism\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Trism\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 350, in execute
    script.process(
  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 101, in process
    result = swap_face(
             ^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 246, in swap_face
    source_faces = analyze_faces(source_img)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 151, in analyze_faces
    face_analyser = getAnalysisModel(det_size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 81, in getAnalysisModel
    ANALYSIS_MODEL = insightface.app.FaceAnalysis(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_patcher.py", line 59, in patched_faceanalysis_init
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-27 13:56:49,669 - root - INFO - Prompt executed in 0.26 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":4,"last_link_id":3,"nodes":[{"id":2,"type":"LoadImage","pos":{"0":342,"1":-118},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["448800638_1137153660832851_3946545270902387364_n.jpg","image"]},{"id":3,"type":"LoadImage","pos":{"0":349,"1":244},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Screenshot 2024-06-21 150854.png","image"]},{"id":4,"type":"SaveImage","pos":{"0":1097,"1":84},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":3}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":1,"type":"ReActorFaceSwap","pos":{"0":731,"1":95},"size":{"0":315,"1":358},"flags":{},"order":2,"mode":0,"inputs":[{"name":"input_image","type":"IMAGE","link":1},{"name":"source_image","type":"IMAGE","link":2,"shape":7},{"name":"face_model","type":"FACE_MODEL","link":null,"shape":7},{"name":"face_boost","type":"FACE_BOOST","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[3],"slot_index":0},{"name":"FACE_MODEL","type":"FACE_MODEL","links":null}],"properties":{"Node name for S&R":"ReActorFaceSwap"},"widgets_values":[true,"1k3d68.onnx","retinaface_resnet50","GFPGANv1.4.pth",1,0.5,"no","no","0","0",1]}],"links":[[1,2,0,1,0,"IMAGE"],[2,3,0,1,1,"IMAGE"],[3,1,0,4,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[-49,38]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Additional information

_No response_

**Comment by Gourieff** [comment]
Try the following: https://github.com/Gourieff/comfyui-reactor-node/issues/115#issuecomment-1851207032

**Comment by Troyificus** [comment]
Yep, that fixed it. Thank you!
