### ISSUE TITLE
Cannot import D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'distutils'

### ISSUE THREAD

**Issue by dxyklp** [Gourieff/comfyui-reactor-node#480]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

在更新到comfyui2.7后出现的问题，我尝试了主页的修复方式但是并没有作用

### Steps to reproduce the problem

Your workflow

### Sysinfo

win11,12700k,rtx4060ti16g

### Relevant console log

```Shell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-07 02:20:08.038053
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\ComfyUI\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI\ComfyUI
** Log path: D:\ComfyUI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.4 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16380 MB, total RAM 32509 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI\ComfyUI\web
Adding extra search path checkpoints D:\SD-WebUI-aki/models/Stable-diffusion
Adding extra search path configs D:\SD-WebUI-aki/models/Stable-diffusion
Adding extra search path vae D:\SD-WebUI-aki/models/VAE
Adding extra search path loras D:\SD-WebUI-aki/models/Lora
Adding extra search path loras D:\SD-WebUI-aki/models/LyCORIS
Adding extra search path upscale_models D:\SD-WebUI-aki/models/ESRGAN
Adding extra search path upscale_models D:\SD-WebUI-aki/models/RealESRGAN
Adding extra search path upscale_models D:\SD-WebUI-aki/models/SwinIR
Adding extra search path embeddings D:\SD-WebUI-aki/embeddings
Adding extra search path hypernetworks D:\SD-WebUI-aki/models/hypernetworks
Adding extra search path controlnet D:\SD-WebUI-aki/models/ControlNet
D:\ComfyUI\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.20.0
[Crystools INFO] CPU: 12th Gen Intel(R) Core(TM) i7-12700K - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4060 Ti
[Crystools INFO] NVIDIA Driver: 565.90
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
### Loading: ComfyUI-Impact-Pack (V7.10.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2812 [5e29e7a4] | Released on '2024-11-06'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
--------------
 ### Mixlab Nodes: Loaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
## clip_interrogator_model not found: D:\ComfyUI\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
## text_generator_model not found: D:\ComfyUI\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: D:\ComfyUI\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available False
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 --------------
D:\ComfyUI\python_embeded\Lib\site-packages\albumentations\check_version.py:51: UserWarning: Error fetching version info <urlopen error _ssl.c:983: The handshake operation timed out>
  data = fetch_version_info()
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 27, in <module>
    from scripts.reactor_faceswap import (
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 14, in <module>
    from scripts.reactor_swapper import (
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 25, in <module>
    from scripts.r_faceboost import swapper, restorer
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_faceboost\restorer.py", line 17, in <module>
    from r_basicsr.utils.registry import ARCH_REGISTRY
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\r_basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\r_basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'r_basicsr.archs.{file_name}') for file_name in arch_filenames]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\r_basicsr\archs\basicvsrpp_arch.py", line 7, in <module>
    from r_basicsr.archs.arch_util import flow_warp
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\r_basicsr\archs\arch_util.py", line 6, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'distutils'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉


Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\AuraSR-ComfyUI
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-eesahesNodes
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.4 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.8 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   2.2 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
```

**Comment by zpavic** [comment]
Came across this bug so adding some context as far as I know it.

The 'distutils' module has been deprecated and now removed in Python 3.12.
A workaround could be to downgrade your version of Python to < 3.12 (you might get deprecation warnings).

I suppose that the reactor code would need to be updated to use the setuptools module instead. There should be equivalents there things in distutils.

**Comment by Jungro-hub** [comment]
> Came across this bug so adding some context as far as I know it.
> 
> The 'distutils' module has been deprecated and now removed in Python 3.12. A workaround could be to downgrade your version of Python to < 3.12 (you might get deprecation warnings).
> 
> I suppose that the reactor code would need to be updated to use the setuptools module instead. There should be equivalents in there for things in distutils.

----
Wow!! Following your advice, it actually worked on Python 3.12! Thank you so much. I'll document how I fixed the code.

File path: ComfyUI\custom_nodes\comfyui-reactor-node\r_basicsr\archs\arch_util.py

before: `from distutils.version import LooseVersion`
after: `from packaging.version import Version`

before: 
```
class DCNv2Pack(ModulatedDeformConvPack):
    """Modulated deformable conv for deformable alignment.

    Different from the official DCNv2Pack, which generates offsets and masks
    from the preceding features, this DCNv2Pack takes another different
    features to generate offsets and masks.

    Ref:
        Delving Deep into Deformable Alignment in Video Super-Resolution.
    """

    def forward(self, x, feat):
        out = self.conv_offset(feat)
        o1, o2, mask = torch.chunk(out, 3, dim=1)
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)

        offset_absmean = torch.mean(torch.abs(offset))
        if offset_absmean > 50:
            logger = get_root_logger()
            logger.warning(f'Offset abs mean is {offset_absmean}, larger than 50.')

        if LooseVersion(torchvision.__version__) >= LooseVersion('0.9.0'):
            return torchvision.ops.deform_conv2d(x, offset, self.weight, self.bias, self.stride, self.padding,
                                                 self.dilation, mask)
        else:
            return modulated_deform_conv(x, offset, mask, self.weight, self.bias, self.stride, self.padding,
                                         self.dilation, self.groups, self.deformable_groups)
```

after:
```
class DCNv2Pack(ModulatedDeformConvPack):
    """Modulated deformable conv for deformable alignment.

    Different from the official DCNv2Pack, which generates offsets and masks
    from the preceding features, this DCNv2Pack takes another different
    features to generate offsets and masks.

    Ref:
        Delving Deep into Deformable Alignment in Video Super-Resolution.
    """

    def forward(self, x, feat):
        out = self.conv_offset(feat)
        o1, o2, mask = torch.chunk(out, 3, dim=1)
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)

        offset_absmean = torch.mean(torch.abs(offset))
        if offset_absmean > 50:
            logger = get_root_logger()
            logger.warning(f'Offset abs mean is {offset_absmean}, larger than 50.')

        # 변경된 조건: packaging.version.Version 사용
        if Version(torchvision.__version__) >= Version('0.9.0'):
            return torchvision.ops.deform_conv2d(
                x, offset, self.weight, self.bias, self.stride, self.padding, self.dilation, mask
            )
        else:
            return modulated_deform_conv(
                x, offset, mask, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups, self.deformable_groups
            )
```

**Comment by Eagle07-Sudo** [comment]
> > Came across this bug so adding some context as far as I know it.
> > The 'distutils' module has been deprecated and now removed in Python 3.12. A workaround could be to downgrade your version of Python to < 3.12 (you might get deprecation warnings).
> > I suppose that the reactor code would need to be updated to use the setuptools module instead. There should be equivalents in there for things in distutils.
> 
> Wow!! Following your advice, it actually worked on Python 3.12! Thank you so much. I'll document how I fixed the code.
> 
> File path: ComfyUI\custom_nodes\comfyui-reactor-node\r_basicsr\archs\arch_util.py

Worked like a charm
Thank you

**Comment by godjerry228** [comment]
The problem solved!! Thanks!
