### ISSUE TITLE
Conflict with Mediapipe

### ISSUE THREAD

**Issue by Alien6666** [Gourieff/comfyui-reactor-node#49]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

If I put comfyui-reactor-node in custom_nodes it breaks the MediaPipe-FaceMeshPreprocessor from InspirePack. I can't figure out why it's causing it to break but would like to use both custom nodes. 

### Steps to reproduce the problem

Use the MediaPipe-FaceMeshPreprocessor from InspirePack with comfyui-reactor-node installed and it errors at that point when the process gets to that node. Removing comfyui-reactor-node from the custom_nodes folder fixes it.

### Sysinfo

AMD Threadripper, Windows 10, Firefox, 3060TI.

### Relevant console log

```Shell
Error occurred when executing MediaPipe-FaceMeshPreprocessor:

A Message class can only inherit from Message

  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\mediapipe_face.py", line 41, in detect
    import mediapipe
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\__init__.py", line 16, in 
    import mediapipe.python.solutions as solutions
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in 
    import mediapipe.python.solutions.drawing_styles
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in 
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in 
    from mediapipe.framework.formats import detection_pb2
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 14, in 
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 14, in 
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 20, in 
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe.framework.formats.annotation.rasterization_pb2', _globals)
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 82, in BuildMessage
    create_dict[name] = BuildMessage(nested_msg)
  File "F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
```

### Additional information

I also tried removing the requirements.txt content from comfyui-reactor-node to see if it was changing a package but it doesn't change anything. I haven't added a node from comfyui-reactor-node.

**Comment by Gourieff** [comment]
You don't need to edit requirements
Try this https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node

**Comment by d8ahazard** [comment]
@Gourieff - Still getting this error, even after trying the suggestion above.

Cannot import /opt/rd/ComfyUI/custom_nodes/models module for custom nodes: [Errno 2] No such file or directory: '/opt/rd/ComfyUI/custom_nodes/models/__init__.py'
Traceback (most recent call last):
  File "/opt/rd/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/rd/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/opt/rd/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "/opt/rd/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_swapper import swap_face
  File "/opt/rd/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 11, in <module>
    import insightface
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/insightface/__init__.py", line 16, in <module>
    from . import model_zoo
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/insightface/model_zoo/__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/insightface/model_zoo/arcface_onnx.py", line 10, in <module>
    import onnx
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/onnx/__init__.py", line 13, in <module>
    from onnx.external_data_helper import (
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/onnx/external_data_helper.py", line 11, in <module>
    from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/onnx/onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/onnx/onnx_ml_pb2.py", line 19, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onnx.onnx_ml_pb2', globals())
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/google/protobuf/internal/builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/google/protobuf/internal/builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

Cannot import /opt/rd/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: A Message class can only inherit from Message


Any suggestions?

**Comment by Gourieff** [comment]
> TypeError: A Message class can only inherit from Message

Try to read here about this error:
https://github.com/protocolbuffers/protobuf/issues/3276

**Comment by d8ahazard** [comment]
> > TypeError: A Message class can only inherit from Message
> 
> Try to read here about this error: [protocolbuffers/protobuf#3276](https://github.com/protocolbuffers/protobuf/issues/3276)

I gave it a read, but nothing is immediately jumping out at me as being applicable.

**Comment by Gourieff** [comment]
What the version of protobuf do you use?

**Comment by storyicon** [comment]
I have another magic that may help you solve this problem.
Add the following code to the header of the `main.py` file in the comfyui root directory (like: [main.py#L1](https://github.com/comfyanonymous/ComfyUI/blob/master/main.py#L1))

```
import onnx
from google.protobuf import reflection
```

Then restart ComfyUI. Maybe you can see something different.
