### ISSUE TITLE
无法安装reactor节点

### ISSUE THREAD

**Issue by Zing-desire** [Gourieff/comfyui-reactor-node#493]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

就是安装了comfyui-reactor-node插件，加载也正常，但是就是导致进不去comfyui了

### Steps to reproduce the problem

Manager插件下载reactor插件，下载完成后重启，如果删掉reactor插件，又能够重新进入comfyui
![微信图片_20241125122641](https://github.com/user-attachments/assets/3011d31b-3b15-419d-80d1-db3318743dc0)
![微信图片_20241125122645](https://github.com/user-attachments/assets/376a412e-4e55-4aed-b80c-b341f080d076)

### Sysinfo

使用的linux操作系统

### Relevant console log

```Shell
[ERROR] An error occurred while retrieving information for the 'ReActorRestoreFace' node.
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/home/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 662, in INPUT_TYPES
    "model": (get_model_names(get_restorers),),
  File "/home/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 115, in get_model_names
    models = get_models()
  File "/home/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 109, in get_restorers
    download(model_url, model_path, model_name)
  File "/home/ComfyUI/custom_nodes/comfyui-reactor-node/reactor_utils.py", line 113, in download
    request = urllib.request.urlopen(url)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
```

### Additional information

使用的torch2.5.1 +cuda121

**Comment by Zing-desire** [comment]
已经解决了，需要将修复模型GFPGANv1.3.pth这一类的随便下一个放在相对应文件夹就好了

**Comment by Daliuq** [comment]
> 已经解决了，需要将修复模型GFPGANv1.3.pth这一类的随便下一个放在相对应文件夹就好了

能详细一点吗
