### ISSUE TITLE
An error occurred during installation regarding version ` GLIBCXX-3.4.32 'not found

### ISSUE THREAD

**Issue by fullstackpeng** [Gourieff/comfyui-reactor-node#494]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Help me, I encountered an error during installation, prompting ImportError:/home/ubuntu/naconda3/env/comfyenv/bin// lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpython-311-x86_64-linux-gnu.so)

### Steps to reproduce the problem

Your workflow
[wav2lip fix.json](https://github.com/user-attachments/files/17899021/wav2lip.fix.json)

### Sysinfo

Linux、python3.11、nvidia 4090

### Relevant console log

```Shell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-25 15:25:59.041626
** Platform: Linux
** Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
** Python executable: /home/ubuntu/anaconda3/envs/comfyenv/bin/python
** ComfyUI Path: /mnt/code/ComfyUI
** Log path: /mnt/code/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.6 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24217 MB, total RAM 64301 MB
pytorch version: 2.2.0+cu121
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /mnt/code/ComfyUI/web
Adding extra search path checkpoints /mnt/sdmodels/Stable-diffusion
Adding extra search path configs /mnt/sdmodels/Stable-diffusion
Adding extra search path vae /mnt/sdmodels/VAE
Adding extra search path loras /mnt/sdmodels/Lora
Adding extra search path loras /mnt/sdmodels/LyCORIS
Adding extra search path upscale_models /mnt/sdmodels/ESRGAN
Adding extra search path upscale_models /mnt/sdmodels/RealESRGAN
Adding extra search path upscale_models /mnt/sdmodels/SwinIR
Adding extra search path embeddings /mnt/embeddings
Adding extra search path hypernetworks /mnt/sdmodels/hypernetworks
Adding extra search path controlnet /mnt/sdmodels/ControlNet
### Loading: ComfyUI-Inspire-Pack (V1.6)
weigths_current_path: /mnt/code/ComfyUI/models/echo_mimic
FFmpeg is installed at: /home/ubuntu/anaconda3/envs/comfyenv/bin/ffmpeg
Adding FFMPEG_PATH to PATH
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2748 [203942c8] | Released on '2024-10-08'
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Easy-Use/web_version/v2 Loaded
Base directory: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip
Checkpoints path: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip/Wav2Lip/checkpoints
Model path: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip/Wav2Lip/checkpoints/wav2lip_gan.pth
Wav2Lip path added to sys.path: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip
Directory created or exists: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip/facedetection
Current directory: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip
Wav2Lip path: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Using cuda for inference.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
Traceback (most recent call last):
  File "/mnt/code/ComfyUI/nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/code/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/mnt/code/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "/home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/__init__.py", line 18, in <module>
    from . import app
  File "/home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/app/mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "/home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
    from . import mesh
  File "/home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: /home/ubuntu/anaconda3/envs/comfyenv/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpython-311-x86_64-linux-gnu.so)

Cannot import /mnt/code/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: /home/ubuntu/anaconda3/envs/comfyenv/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/ubuntu/anaconda3/envs/comfyenv/lib/python3.11/site-packages/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpython-311-x86_64-linux-gnu.so)
### Loading: ComfyUI-Impact-Pack (V7.11.3)
[Impact Pack] Failed to import due to several dependencies are missing!!!!
Traceback (most recent call last):
  File "/mnt/code/ComfyUI/nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/code/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 53, in <module>
    raise e
  File "/mnt/code/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 31, in <module>
    import impact.subpack_nodes  # This import must be done before cv2.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'impact.subpack_nodes'

Cannot import /mnt/code/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.subpack_nodes'
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/mnt/code/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

	"Art is the light that shines even in the darkest corners." - Unknown


Import times for custom nodes:
   0.0 seconds: /mnt/code/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /mnt/code/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds (IMPORT FAILED): /mnt/code/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.1 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.3 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI_wav2lip
   0.7 seconds (IMPORT FAILED): /mnt/code/ComfyUI/custom_nodes/comfyui-reactor-node
   0.9 seconds: /mnt/code/ComfyUI/custom_nodes/ComfyUI_EchoMimic
   1.0 seconds: /mnt/code/ComfyUI/custom_nodes/was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
To see the GUI go to: http://[::]:8188
```

**Comment by q5sys** [comment]
I ran into something similar:
```
Traceback (most recent call last):
  File "/home/q5/ai/clothingswap/ComfyUI/nodes.py", line 2036, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/q5/ai/clothingswap/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/q5/ai/clothingswap/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "/home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/__init__.py", line 18, indule>
    from . import app
  File "/home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/app/mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "/home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
    from . import mesh
  File "/home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: /home/q5/.conda/envs/clothingswap/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpython-312-x86_64-linux-gnu.so)

Cannot import /home/q5/ai/clothingswap/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: /home/q5/.conda/envs/clothingswap/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/q5/.conda/envs/clothingswap/lib/python3.12/site-packages/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpython-312-x86_64-linux-gnu.so)
```

running `strings` on the `libstdc++.so.6` in my conda env also showed that `GLIBCXX_3.4.32` was not found in the lib.  For a quick and dirty fix on my system I sym-linked my system `libstdc++.so.6` which does have the `GLIBCXX_3.4.32` and then Reactor started properly.  Not the best way to fix it, but it worked in a pinch. @fullstackpeng , your environment needs to be updated to have a libstdc++ file that does support 3.4.32.

**Comment by CambridgeComputing** [comment]
The above comments helped me also resolve this in Ubuntu in WSL2. I had to make a few changes, but here's what worked for me:
```shell
cd ~/miniconda3/envs/comfyui/lib
mv libstdc++.so libstdc++.so.BAK
mv libstdc++.so.6 libstdc++.so.6.BAK
ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6
ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33 libstdc++.so.6.0.33
```
