### ISSUE TITLE
load the nodes error

### ISSUE THREAD

**Issue by the2ndface** [Gourieff/comfyui-reactor-node#56]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I installed the nodes and started comfyui, an error occurred, causing the other three nodes to not work properly:1、comfyui_controlnet_aux 2.SeargeSDXL3.was-node-suite-comfyui
Error content：partially initialized module 'cv2' has no attribute 'mat_wrapper' (most likely due to a circular import)
opencv-python,opencv-contrib-python,opencv-python-headless are last version4.8.1.78

so,How should this problem be solved?

### Steps to reproduce the problem

install it from comfyui manager

### Sysinfo

ubuntu22 

other nodes:
SDXLAspectRatio.py
   ComfyUi_PromptStylers
  ComfyUI-Custom-Scripts
  ComfyUI_UltimateSDUpscale
   efficiency-nodes-comfyui
   comfyui_controlnet_aux
   AIGODLIKE-COMFYUI-TRANSLATION
   ComfyUI-Manager
   SeargeSDXL
   was-node-suite-comfyui

### Relevant console log

```Shell
Total VRAM 16128 MB, total RAM 31325 MB
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 13475, in <module>
    import cv2
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/typing/__init__.py", line 94, in <module>
    MatLike = typing.Union[cv2.mat_wrapper.Mat, NumPyArrayGeneric]
AttributeError: partially initialized module 'cv2' has no attribute 'mat_wrapper' (most likely due to a circular import)

Cannot import /home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: partially initialized module 'cv2' has no attribute 'mat_wrapper' (most likely due to a circular import)
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 4, in <module>
    import cv2
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/typing/__init__.py", line 94, in <module>
    MatLike = typing.Union[cv2.mat_wrapper.Mat, NumPyArrayGeneric]
AttributeError: partially initialized module 'cv2' has no attribute 'mat_wrapper' (most likely due to a circular import)

Cannot import /home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: partially initialized module 'cv2' has no attribute 'mat_wrapper' (most likely due to a circular import)
```

**Comment by Gourieff** [comment]
Yes, known issue of OpenCV 4.8
Try this:
`pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless`
`pip install opencv-python==4.7.0.72`
and if you use mediapipe:
`pip install opencv-contrib-python==4.7.0.72`
If there are any other extensions trying to reinstall opencv to 4.8 - just edit their requirements
