### ISSUE TITLE
The constant `IS_HIGH_VERSION` doesn't take into account dev versions

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [Gourieff/comfyui-reactor-node#58]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

This is a manually installed ComfyUI with its own venv. I did a fresh install of commit 9138e960286f8ded9969b9770d4071d058fd528e from this repo and tried to run ComfyUI, but I get the following error:
```
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 13, in <module>
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\facelib\utils\face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\facelib\detection\__init__.py", line 12, in <module>
    from .yolov5face.face_detector import YoloDetector
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\facelib\detection\yolov5face\face_detector.py", line 20, in <module>
    IS_HIGH_VERSION = tuple(map(int, torch.__version__.split('+')[0].split('.'))) >= (1, 9, 0)
ValueError: invalid literal for int() with base 10: 'dev20231005'

Cannot import F:\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: invalid literal for int() with base 10: 'dev20231005'
```
I don't fully understand it, but it looks like it is expecting integer numbers only, and so the "dev" in the name is causing the error.

### Steps to reproduce the problem

Install custom nodes from ComfyUI manager and restart ComfyUI.

### Sysinfo

Windows 11
Chrome
RTX 4090

### Relevant console log

```Shell
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 13, in <module>
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\facelib\utils\face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\facelib\detection\__init__.py", line 12, in <module>
    from .yolov5face.face_detector import YoloDetector
  File "F:\ComfyUI\custom_nodes\comfyui-reactor-node\facelib\detection\yolov5face\face_detector.py", line 20, in <module>
    IS_HIGH_VERSION = tuple(map(int, torch.__version__.split('+')[0].split('.'))) >= (1, 9, 0)
ValueError: invalid literal for int() with base 10: 'dev20231005'

Cannot import F:\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: invalid literal for int() with base 10: 'dev20231005'
```
```


### Additional information

_No response_

**Comment by GalaxyTimeMachine** [comment]
I managed to workaround it by editing the face_detector.py:

```
import re
...
...
# Use regular expression to extract the numeric part of the version string
version_match = re.match(r'(\d+\.\d+\.\d+)', torch.__version__)
if version_match:
    numeric_version = tuple(map(int, version_match.group(1).split('.')))
else:
    numeric_version = (0, 0, 0)  # Set a default version if no match is found

# Check if the numeric version is greater than or equal to (1, 9, 0)
IS_HIGH_VERSION = numeric_version >= (1, 9, 0)
```

**Comment by Gourieff** [comment]
Yes, you're using some dev version of torch and it has 'dev20231005' in the version number
And yes, I fully agree
`IS_HIGH_VERSION = tuple(map(int, torch.__version__.split('+')[0].split('.'))) >= (1, 9, 0)`
This is a very strange method of checking package version
Facelib - is not my code, so I will fix it with the next update
"Packaging" lib can easily resolve such things

**Comment by Gourieff** [comment]
And thank you for spotting this

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/comfyui-reactor-node/commit/a35c0258e63a887faddf572d95ad51cc91a8c8c8
