### ISSUE TITLE
[SOLVED] cannot import mesh_core_cython - node fails to load

### ISSUE THREAD

**Issue by telemole** [Gourieff/comfyui-reactor-node#78]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

after installation into standalone version (using it's own python) the node fails to load displaying errors shown below.  Many searches seem to lead to various cludges like adding a blank __init__.py etc - I am hoping to understand the issue and resolve it properly - any help appreciated!

### Steps to reproduce the problem

Your workflow
- Build from scratch
- install custom nodes through the manager with success
- load server and observe errors

### Sysinfo

Windows, firefox, Nvidia GEforce 3080Ti

### Relevant console log

```Shell
Total VRAM 12287 MB, total RAM 32619 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1588 [d44a2de4] | Released on '2023-10-17'
Traceback (most recent call last):
  File "H:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_swapper import swap_face
  File "H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 11, in <module>
    import insightface
  File "H:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "H:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "H:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "H:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "H:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)

Cannot import H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
Import times for custom nodes:
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.3 seconds (IMPORT FAILED): H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.3 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.4 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
   1.9 seconds: H:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server
```

### Additional information

I know it's something small - the pieces are installed - but something about the installation must be in the wrong place? Pulling out my hair what little is left ;) thanks in advance!

**Comment by ParticleDog** [comment]
I encountered the same problem. 
"DLL load failed while importing mesh_core_cython"

**Comment by telemole** [comment]
I specifically went back to the new Readme which was updated with comfyui instructions - in the troubleshooting section about manually installing: 
 [I. (For Windows users) If you still cannot build Insightface for some reasons or just don't want to install Visual Studio or VS C++ Build Tools - do the following:]
 
 make sure you check your python version and download the appropriate install file - run that process - restart your comfyui - install those facerestore models to the right directory also! All listed in those new Readme instructions - thanks very much to the author

**Comment by xingzhaoyang** [comment]
我遇到同样的问题 
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: DLL load failed while importing mesh_core_cython: 找不到指定的模块。

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: DLL load failed while importing mesh_core_cython: 找不到指定的模块。
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
就是按照步骤一步一步做的，但是任然是 报错
