### ISSUE TITLE
Unable to install reactor

### ISSUE THREAD

**Issue by Trobinou** [Gourieff/comfyui-reactor-node#87]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

ComfyUI is up to date, this is the portable version.

### Steps to reproduce the problem

Your workflow

### Sysinfo

Windows 10, Firefox

### Relevant console log

```Shell
D:\ComfyUI_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-31 19:48:50.775029

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'insightface==0.7.3']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Collecting insightface==0.7.3
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnx>=1.14.0']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Requirement already satisfied: onnx>=1.14.0 in d:\comfyui_portable\python_embeded\lib\site-packages (1.15.0)
 Requirement already satisfied: numpy in d:\comfyui_portable\python_embeded\lib\site-packages (from onnx>=1.14.0) (1.24.4)
 Requirement already satisfied: protobuf>=3.20.2 in d:\comfyui_portable\python_embeded\lib\site-packages (from onnx>=1.14.0) (3.20.3)

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnxruntime>=1.15.1']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Requirement already satisfied: onnxruntime>=1.15.1 in d:\comfyui_portable\python_embeded\lib\site-packages (1.16.1)
 Requirement already satisfied: coloredlogs in d:\comfyui_portable\python_embeded\lib\site-packages (from onnxruntime>=1.15.1) (15.0.1)
 Requirement already satisfied: flatbuffers in d:\comfyui_portable\python_embeded\lib\site-packages (from onnxruntime>=1.15.1) (23.5.26)
 Requirement already satisfied: numpy>=1.24.2 in d:\comfyui_portable\python_embeded\lib\site-packages (from onnxruntime>=1.15.1) (1.24.4)
 Requirement already satisfied: packaging in d:\comfyui_portable\python_embeded\lib\site-packages (from onnxruntime>=1.15.1) (23.2)
 Requirement already satisfied: protobuf in d:\comfyui_portable\python_embeded\lib\site-packages (from onnxruntime>=1.15.1) (3.20.3)
 Requirement already satisfied: sympy in d:\comfyui_portable\python_embeded\lib\site-packages (from onnxruntime>=1.15.1) (1.12)
 Requirement already satisfied: humanfriendly>=9.1 in d:\comfyui_portable\python_embeded\lib\site-packages (from coloredlogs->onnxruntime>=1.15.1) (10.0)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_portable\python_embeded\lib\site-packages (from sympy->onnxruntime>=1.15.1) (1.3.0)
 Requirement already satisfied: pyreadline3 in d:\comfyui_portable\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.15.1) (3.4.1)

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'opencv-python>=4.7.0.72']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Requirement already satisfied: opencv-python>=4.7.0.72 in d:\comfyui_portable\python_embeded\lib\site-packages (4.8.1.78)
 Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_portable\python_embeded\lib\site-packages (from opencv-python>=4.7.0.72) (1.24.4)

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'numpy']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Requirement already satisfied: numpy in d:\comfyui_portable\python_embeded\lib\site-packages (1.24.4)

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'torch']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Requirement already satisfied: torch in d:\comfyui_portable\python_embeded\lib\site-packages (2.1.0+cu121)
 Requirement already satisfied: filelock in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.12.4)
 Requirement already satisfied: typing-extensions in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (4.8.0)
 Requirement already satisfied: sympy in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (1.12)
 Requirement already satisfied: networkx in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.1)
 Requirement already satisfied: jinja2 in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
 Requirement already satisfied: fsspec in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (2023.9.2)
 Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.3)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'torchvision']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Requirement already satisfied: torchvision in d:\comfyui_portable\python_embeded\lib\site-packages (0.16.0+cu121)
 Requirement already satisfied: numpy in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (1.24.4)
 Requirement already satisfied: requests in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
 Requirement already satisfied: torch==2.1.0+cu121 in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (2.1.0+cu121)
 Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (9.5.0)
 Requirement already satisfied: filelock in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (3.12.4)
 Requirement already satisfied: typing-extensions in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (4.8.0)
 Requirement already satisfied: sympy in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (1.12)
 Requirement already satisfied: networkx in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (3.1)
 Requirement already satisfied: jinja2 in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (3.1.2)
 Requirement already satisfied: fsspec in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (2023.9.2)
 Requirement already satisfied: charset-normalizer<4,>=2 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.3.0)
 Requirement already satisfied: idna<4,>=2.5 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
 Requirement already satisfied: urllib3<3,>=1.21.1 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (2.0.6)
 Requirement already satisfied: certifi>=2017.4.17 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.7.22)
 Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch==2.1.0+cu121->torchvision) (2.1.3)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch==2.1.0+cu121->torchvision) (1.3.0)

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_portable\\python_embeded\\python.exe', 'install.py']

## Execute install/(de)activation script for 'D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
[!] D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node\install.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
[!]   import pkg_resources
 Collecting insightface==0.7.3
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\ComfyUI_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
 Requirement already satisfied: numpy in d:\comfyui_portable\python_embeded\lib\site-packages (1.24.4)
 Requirement already satisfied: torch in d:\comfyui_portable\python_embeded\lib\site-packages (2.1.0+cu121)
 Requirement already satisfied: filelock in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.12.4)
 Requirement already satisfied: typing-extensions in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (4.8.0)
 Requirement already satisfied: sympy in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (1.12)
 Requirement already satisfied: networkx in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.1)
 Requirement already satisfied: jinja2 in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
 Requirement already satisfied: fsspec in d:\comfyui_portable\python_embeded\lib\site-packages (from torch) (2023.9.2)
 Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.3)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)
 Requirement already satisfied: torchvision in d:\comfyui_portable\python_embeded\lib\site-packages (0.16.0+cu121)
 Requirement already satisfied: numpy in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (1.24.4)
 Requirement already satisfied: requests in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
 Requirement already satisfied: torch==2.1.0+cu121 in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (2.1.0+cu121)
 Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (9.5.0)
 Requirement already satisfied: filelock in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (3.12.4)
 Requirement already satisfied: typing-extensions in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (4.8.0)
 Requirement already satisfied: sympy in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (1.12)
 Requirement already satisfied: networkx in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (3.1)
 Requirement already satisfied: jinja2 in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (3.1.2)
 Requirement already satisfied: fsspec in d:\comfyui_portable\python_embeded\lib\site-packages (from torch==2.1.0+cu121->torchvision) (2023.9.2)
 Requirement already satisfied: charset-normalizer<4,>=2 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.3.0)
 Requirement already satisfied: idna<4,>=2.5 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
 Requirement already satisfied: urllib3<3,>=1.21.1 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (2.0.6)
 Requirement already satisfied: certifi>=2017.4.17 in d:\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.7.22)
 Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch==2.1.0+cu121->torchvision) (2.1.3)
 Requirement already satisfied: mpmath>=0.19 in d:\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch==2.1.0+cu121->torchvision) (1.3.0)
 Installing...
 Error: The 'insightface==0.7.3' distribution was not found and is required by the application
 Error: expected string or bytes-like object, got 'NoneType'
 Error: expected string or bytes-like object, got 'NoneType'
 Error: expected string or bytes-like object, got 'NoneType'
 Ok

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\rgthree-comfy
  25.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 32604 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.28.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Inspire-Pack (V0.33)
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1631 [c837a173] | Released on '2023-10-30'
Traceback (most recent call last):
  File "D:\ComfyUI_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_swapper import swap_face
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 11, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
### Loading: ComfyUI-Workflow-Component (V0.43.3) !! WARN: This is an experimental extension. Extremely unstable. !!
Comfyroll Custom Nodes: Loaded
Registered sys.path: ['D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\comfyui-reactor-node', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', 'D:\\ComfyUI_portable\\python_embeded\\Lib\\site-packages\\git\\ext\\gitdb', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\cg-prompt-info', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\cg-image-picker', 'D:\\ComfyUI_portable\\ComfyUI\\comfy', 'D:\\ComfyUI_portable\\ComfyUI', 'D:\\ComfyUI_portable\\python_embeded\\python311.zip', 'D:\\ComfyUI_portable\\python_embeded', 'D:\\ComfyUI_portable\\python_embeded\\Lib\\site-packages', 'D:\\ComfyUI_portable\\python_embeded\\Lib\\site-packages\\win32', 'D:\\ComfyUI_portable\\python_embeded\\Lib\\site-packages\\win32\\lib', 'D:\\ComfyUI_portable\\python_embeded\\Lib\\site-packages\\Pythonwin', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..', 'D:\\ComfyUI_portable\\ComfyUI\\custom_nodes\\ComfyUI-Workflow-Component']
D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

[rgthree] Loaded 15 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\ComfyUI_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 197 nodes successfully.

        "Art is the triumph over chaos." - John Cheever


Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\cg-prompt-info
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\cg_custom_core
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_SeeCoder
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Component
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.8 seconds: D:\ComfyUI_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
```

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/25#issuecomment-1716047558

**Comment by Trobinou** [comment]
Désolé pour cette erreur de ma part...
Tout fonctionne en suivant vos instructions.
