### ISSUE TITLE
torch.dml not available

### ISSUE THREAD

**Issue by WeeBull** [Gourieff/comfyui-reactor-node#91]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

On Linux, after updating to the latest version, I get:

```
  File "/home/pauls/StableDiffusion/ComfyUI/custom_nodes/comfyui-reactor-node/r_facelib/detection/retinaface/retinaface.py", line 19, in <module>
    elif torch.dml.is_available():
         ^^^^^^^^^
AttributeError: module 'torch' has no attribute 'dml'
```

This is because torch does not export a direct_ml device on Linux. Guarding the test with `torch.hasattr('dml')` should suffice.

### Steps to reproduce the problem

1. Install facedetector via comfyui-manager
2. restart comfyui
3. Observe error in log

### Sysinfo

OS: Arch Linux x86_64
Kernel: 6.5.4-arch2-1
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: AMD ATI Radeon RX 7700S/7600/7600S/7600M XT/PRO W7600
Memory: 8333MiB / 48098MiB

### Relevant console log

```Shell
Traceback (most recent call last):
  File "/home/pauls/StableDiffusion/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pauls/StableDiffusion/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/pauls/StableDiffusion/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 14, in <module>
    from r_facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/pauls/StableDiffusion/ComfyUI/custom_nodes/comfyui-reactor-node/r_facelib/utils/face_restoration_helper.py", line 7, in <module>
    from r_facelib.detection import init_detection_model
  File "/home/pauls/StableDiffusion/ComfyUI/custom_nodes/comfyui-reactor-node/r_facelib/detection/__init__.py", line 11, in <module>
    from .retinaface.retinaface import RetinaFace
  File "/home/pauls/StableDiffusion/ComfyUI/custom_nodes/comfyui-reactor-node/r_facelib/detection/retinaface/retinaface.py", line 19, in <module>
    elif torch.dml.is_available():
         ^^^^^^^^^
AttributeError: module 'torch' has no attribute 'dml'
```

**Comment by lord-lethris** [comment]
Same ^

```
  File "D:\apps\SD-WebUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 14, in <module>
    from r_facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\r_facelib\utils\face_restoration_helper.py", line 7, in <module>
    from r_facelib.detection import init_detection_model
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\r_facelib\detection\__init__.py", line 11, in <module>
    from .retinaface.retinaface import RetinaFace
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\r_facelib\detection\retinaface\retinaface.py", line 19, in <module>
    elif torch.dml.is_available():
AttributeError: module 'torch' has no attribute 'dml'
```

**Comment by Gourieff** [comment]
@WeeBull Thanks for spotting 👍🏻
Fixed https://github.com/Gourieff/comfyui-reactor-node/commit/429d342a7b8a1fa6f57d731c5546f01f7d29b5a7
