### ISSUE TITLE
Getting an ImportError for 'mesh_core_cythong' on startup

### ISSUE THREAD

**Issue by k1ngm0** [Gourieff/comfyui-reactor-node#94]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I've been trying to get this node installed correctly for the past couple of days, but I always seem to find a new issue.

I got to a point where the install script finished successfully every time I clone the repository. However, on startup it now says the following:

```
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
```

I tried adding the file as a PATH variable, but that didn't fix the issue. I don't really know where to start here, so any help is appreciated. 

### Steps to reproduce the problem

Your workflow
I tried the following methods of installing the node:

1. Go to custom_nodes folder, open CMD and clone repository. Then use the install script
2. Use comfyUI Manager to install the reactor node from there. 
3. Use a fixed release version (0.3.0) with a manual download and the rest like 1.

I made major problem installing insightface and had to manually download the version to install via command. Now, that that's gone, I have the issue described above. 

### Sysinfo

OS: Win11
GPU: 3080

### Relevant console log

```Shell
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_swapper import swap_face
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 11, in <module>
    import insightface
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
```

**Comment by Gourieff** [comment]
Smth wrong with the Insightface library
Did you try the following? https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by k1ngm0** [comment]
Thanks for answering!

I had done that already, but I decided to do a "clean" install now by running:

1: `python_embeded\python.exe -m pip uninstall insightface`
2: `python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl`

I got this warning after the installation, could that be the issue?

 ```
WARNING: The script insightface-cli.exe is installed in 'C:\AI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
img2texture 1.0.6 requires pillow<10,>=9.2, but you have pillow 10.0.1 which is incompatible.
Successfully installed Pillow-10.0.1 insightface-0.7.3
```
